# Using Timelink in notebooks: tutorial

> First time use: follow instructions in the [README.md](README.md) file in this directory.

In [1]:
import timelink
timelink.version

'1.1.27'

## Initial setup

Create a TimelinkNotebook object. This will be the interface for most of your interactions with Timelink.

The first time you run this notebook, you will be prompted to install ìpykernel. This is required to run Timelink in a notebook.

Note:
* First time run takes a little time as the required Docker images are downloaded.
* Timelink will default to using sqlite as the database, see [Receipts notebook for more control](1-receipts.ipynb)

In [2]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook()

WARNING:root:Kleio server not ready, retrying in 1 seconds: [Errno 54] Connection reset by peer

TimelinkNotebook created a database to store data and a Kleio server to 
translate transcriptions in Kleio notation into data that can be imported
into a database.

To get information about the database and the Kleio server do ```tnlb.print_info()```

In [3]:
tlnb.print_info()

Timelink version: 1.1.27
Project name: dehergne
Project home: /Users/jrc/mhk-home/sources/dehergne
Database type: sqlite
Database name: dehergne
Kleio image: timelinkserver/kleio-server
Kleio server token: k1CA4...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/mhk-home/sources/dehergne
Kleio server container: recursing_lovelace
Kleio version requested: latest
Kleio server version: 12.9.588 (2025-06-06 16:04:22)
SQLite directory: /Users/jrc/mhk-home/sources/dehergne/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne, project_home=/Users/jrc/mhk-home/sources/dehergne, db_type=sqlite, db_name=dehergne, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

### Database status

Count the number of rows in each table in the database.

In [4]:
tlnb.table_row_count_df()

               table  count
0               acts     28
1    alembic_version      1
2         aregisters      0
3         attributes  26821
4             blinks     98
5   class_attributes     58
6            classes     10
7           entities  32974
8        geoentities    359
9         kleiofiles     38
10             links    114
11           objects      0
12           persons   2132
13         relations   3547
14         rentities     48
15           sources     29
16            syslog      0
17            syspar      0

### Show the kleio files available

In [5]:
kleio_files = tlnb.get_kleio_files()
kleio_files

,path,name,modified,status,translated,errors,warnings,import_status,import_errors,import_warnings,import_error_rpt,import_warning_rpt,imported,rpt_url,xml_url
0,sources/dehergne-0-abrev.cli,dehergne-0-abrev.cli,2025-12-25 14:12:05.739063+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:51:45.672830,/rest/reports/sources/dehergne-0-abrev.rpt,/rest/exports/sources/dehergne-0-abrev.xml
1,sources/dehergne-a.cli,dehergne-a.cli,2025-12-25 17:11:42.187196+00:00,V,2025-12-25 17:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:13:06.832915,/rest/reports/sources/dehergne-a.rpt,/rest/exports/sources/dehergne-a.xml
2,sources/dehergne-b.cli,dehergne-b.cli,2025-12-25 17:11:47.552616+00:00,V,2025-12-25 17:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:13:18.919915,/rest/reports/sources/dehergne-b.rpt,/rest/exports/sources/dehergne-b.xml
3,sources/dehergne-c.cli,dehergne-c.cli,2025-12-25 16:24:38.056422+00:00,V,2025-07-20 11:39:00+00:00,0,0,I,0,0,No errors,No warnings,2025-09-12 13:31:08.413259,/rest/reports/sources/dehergne-c.rpt,/rest/exports/sources/dehergne-c.xml
4,sources/dehergne-d.cli,dehergne-d.cli,2025-12-25 15:55:00.831785+00:00,V,2025-09-08 03:29:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:13:28.110657,/rest/reports/sources/dehergne-d.rpt,/rest/exports/sources/dehergne-d.xml
5,sources/dehergne-e.cli,dehergne-e.cli,2026-01-18 13:01:47.281034+00:00,V,2026-01-18 13:01:00+00:00,0,0,I,0,0,No errors,No warnings,2026-01-18 13:02:03.244530,/rest/reports/sources/dehergne-e.rpt,/rest/exports/sources/dehergne-e.xml
6,sources/dehergne-f.cli,dehergne-f.cli,2025-12-25 15:55:00.835741+00:00,V,2025-09-08 03:30:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:13:41.153621,/rest/reports/sources/dehergne-f.rpt,/rest/exports/sources/dehergne-f.xml
7,sources/dehergne-g.cli,dehergne-g.cli,2025-12-26 08:41:18.020851+00:00,V,2025-12-26 08:41:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-26 08:42:17.514045,/rest/reports/sources/dehergne-g.rpt,/rest/exports/sources/dehergne-g.xml
8,sources/dehergne-h.cli,dehergne-h.cli,2025-12-25 14:12:05.768887+00:00,V,2025-05-28 07:32:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 09:14:04.630554,/rest/reports/sources/dehergne-h.rpt,/rest/exports/sources/dehergne-h.xml
9,sources/dehergne-i.cli,dehergne-i.cli,2025-12-25 14:12:05.771061+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:54:01.277609,/rest/reports/sources/dehergne-i.rpt,/rest/exports/sources/dehergne-i.xml
10,sources/dehergne-j.cli,dehergne-j.cli,2025-12-25 17:19:28.410327+00:00,V,2025-12-25 17:19:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:20:28.833185,/rest/reports/sources/dehergne-j.rpt,/rest/exports/sources/dehergne-j.xml
11,sources/dehergne-k.cli,dehergne-k.cli,2025-12-25 15:55:00.847789+00:00,V,2025-09-08 04:04:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:13:57.682527,/rest/reports/sources/dehergne-k.rpt,/rest/exports/sources/dehergne-k.xml
12,sources/dehergne-l.cli,dehergne-l.cli,2026-01-18 12:20:28.224437+00:00,V,2026-01-18 12:20:00+00:00,0,0,I,0,0,No errors,No warnings,2026-01-18 12:23:02.853893,/rest/reports/sources/dehergne-l.rpt,/rest/exports/sources/dehergne-l.xml
13,sources/dehergne-locations-1644.cli,dehergne-locations-1644.cli,2025-12-25 14:12:05.779319+00:00,V,2025-06-06 02:43:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:54:44.943804,/rest/reports/sources/dehergne-locations-1644.rpt,/rest/exports/sources/dehergne-locations-1644.xml
14,sources/dehergne-locations-1701.cli,dehergne-locations-1701.cli,2025-12-25 14:12:05.784365+00:00,V,2025-06-05 03:13:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:54:51.052823,/rest/reports/sources/dehergne-locations-1701.rpt,/rest/exports/sources/dehergne-locations-1701.xml
15,sources/dehergne-m.cli,dehergne-m.cli,2025-12-25 16:24:38.079613+00:00,V,2025-07-20 11:37:00+00:00,0,0,I,0,0,No errors,No warnings,2025-09-12 13:31:19.556811,/rest/reports/sources/dehergne-m.rpt,/rest/exports/sources/dehergne-m.xml
16,sources/dehergne-n.cli,dehergne-n.cli,2025-12-25 15:55:00.856346+00:00,V,2025-09-08 03:22:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:14:17.136968,/rest/reports/sources/dehergne-n.rpt,/rest/exports/sources/dehergne-n.xml
17,sources/dehergne-o.cli,dehergne-o.cli,2025-12-25 14:12:05.793152+00:00,V,2025-06-04 00:22:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:55:22.823860,/rest/reports/sources/dehergne-o.rpt,/rest/exports/sources/dehergne-o.xml
18,sources/dehergne-p.cli,dehergne-p.cli,2025-12-25 15:55:00.858155+00:00,V,2025-09-08 04:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:14:30.608855,/rest/reports/sources/dehergne-p.rpt,/rest/exports/sources/dehergne-p.xml
19,sources/dehergne-q.cli,dehergne-q.cli,2025-12-25 14:12:05.798200+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:55:38.814140,/rest/reports/sources/dehergne-q.rpt,/rest/exports/sources/dehergne-q.xml
20,sources/dehergne-r.cli,dehergne-r.cli,2025-12-25 17:21:18.606275+00:00,V,2025-12-25 17:21:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:22:23.584527,/rest/reports/sources/dehergne-r.rpt,/rest/exports/sources/dehergne-r.xml
21,sources/dehergne-s.cli,dehergne-s.cli,2025-12-25 16:21:35.382880+00:00,V,2025-12-04 08:48:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-04 08:49:18.543318,/rest/reports/sources/dehergne-s.rpt,/rest/exports/sources/dehergne-s.xml
22,sources/dehergne-t.cli,dehergne-t.cli,2026-01-18 13:41:44.864458+00:00,T,2025-09-08 04:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:14:38.734093,/rest/reports/sources/dehergne-t.rpt,/rest/exports/sources/dehergne-t.xml
23,sources/dehergne-u.cli,dehergne-u.cli,2025-12-25 14:12:05.814019+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:56:27.105279,/rest/reports/sources/dehergne-u.rpt,/rest/exports/sources/dehergne-u.xml
24,sources/dehergne-v.cli,dehergne-v.cli,2025-12-25 15:55:00.872474+00:00,V,2025-09-08 04:04:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:14:49.790468,/rest/reports/sources/dehergne-v.rpt,/rest/exports/sources/dehergne-v.xml
25,sources/dehergne-w.cli,dehergne-w.cli,2025-12-25 14:12:05.818212+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:56:38.731607,/rest/reports/sources/dehergne-w.rpt,/rest/exports/sources/dehergne-w.xml
26,sources/dehergne-x.cli,dehergne-x.cli,2025-12-25 14:12:05.819237+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:56:41.251361,/rest/reports/sources/dehergne-x.rpt,/rest/exports/sources/dehergne-x.xml
27,sources/dehergne-y.cli,dehergne-y.cli,2025-12-25 14:12:05.820443+00:00,V,2025-05-28 08:31:00+00:00,0,0,I,0,0,No errors,No warnings,2025-07-10 08:56:42.851893,/rest/reports/sources/dehergne-y.rpt,/rest/exports/sources/dehergne-y.xml
28,sources/dehergne-z.cli,dehergne-z.cli,2025-12-25 15:55:00.875730+00:00,V,2025-09-08 04:04:00+00:00,0,0,I,0,0,No errors,No warnings,2025-12-25 17:14:52.107156,/rest/reports/sources/dehergne-z.rpt,/rest/exports/sources/dehergne-z.xml

## Optionally clean translations

In [7]:
tlnb.kleio_server.translation_clean("", recurse="yes")

['sources/dehergne-z.cli',
 'sources/dehergne-y.cli',
 'sources/dehergne-x.cli',
 'sources/dehergne-w.cli',
 'sources/dehergne-v.cli',
 'sources/dehergne-u.cli',
 'sources/dehergne-t.cli',
 'sources/dehergne-s.cli',
 'sources/dehergne-r.cli',
 'sources/dehergne-q.cli',
 'sources/dehergne-p.cli',
 'sources/dehergne-other.cli',
 'sources/dehergne-o.cli',
 'sources/dehergne-n.cli',
 'sources/dehergne-m.cli',
 'sources/dehergne-locations-1701.cli',
 'sources/dehergne-locations-1644.cli',
 'sources/dehergne-l.cli',
 'sources/dehergne-k.cli',
 'sources/dehergne-j.cli',
 'sources/dehergne-i.cli',
 'sources/dehergne-h.cli',
 'sources/dehergne-g.cli',
 'sources/dehergne-f.cli',
 'sources/dehergne-e.cli',
 'sources/dehergne-d.cli',
 'sources/dehergne-c.cli',
 'sources/dehergne-b.cli',
 'sources/dehergne-a.cli',
 'identifications/mhk_identification_toliveira.cli']


# Update the database from Kleio sources.

Updates source translations and imports into database sources with no errors.

Only changed files since last import, or new files, will be processed.

In [12]:
import logging
logging.basicConfig(level=logging.INFO)

tlnb.update_from_sources()

INFO:root:Request translation of T sources/dehergne-locations-1644.cli
INFO:root:Importing sources/dehergne-locations-1644.cli
INFO:root:Importing sources/dehergne-locations-1644.cli

## Check the status of the files

Check the import status of the translated files

I: Imported

E: Imported with error

W: Imported with warnings no errors

N: Not imported

U: Translation updated need to reimport

In [6]:
imported_files_df = tlnb.get_import_status()
imported_files_df[["import_status","import_errors","import_warnings","name","errors","warnings","path"]].sort_values("name")

,import_status,import_errors,import_warnings,name,errors,warnings,path
0,I,0,0,dehergne-0-abrev.cli,0,0,sources/dehergne-0-abrev.cli
1,I,0,0,dehergne-a.cli,0,0,sources/dehergne-a.cli
2,I,0,0,dehergne-b.cli,0,0,sources/dehergne-b.cli
3,I,0,0,dehergne-c.cli,0,0,sources/dehergne-c.cli
4,I,0,0,dehergne-d.cli,0,0,sources/dehergne-d.cli
5,I,0,0,dehergne-e.cli,0,0,sources/dehergne-e.cli
6,I,0,0,dehergne-f.cli,0,0,sources/dehergne-f.cli
7,I,0,0,dehergne-g.cli,0,0,sources/dehergne-g.cli
8,I,0,0,dehergne-h.cli,0,0,sources/dehergne-h.cli
9,I,0,0,dehergne-i.cli,0,0,sources/dehergne-i.cli
10,I,0,0,dehergne-j.cli,0,0,sources/dehergne-j.cli
11,I,0,0,dehergne-k.cli,0,0,sources/dehergne-k.cli
12,I,0,0,dehergne-l.cli,0,0,sources/dehergne-l.cli
13,I,0,0,dehergne-locations-1644.cli,0,0,sources/dehergne-locations-1644.cli
14,I,0,0,dehergne-locations-1701.cli,0,0,sources/dehergne-locations-1701.cli
15,I,0,0,dehergne-m.cli,0,0,sources/dehergne-m.cli
16,I,0,0,dehergne-n.cli,0,0,sources/dehergne-n.cli
17,I,0,0,dehergne-o.cli,0,0,sources/dehergne-o.cli
18,I,0,0,dehergne-p.cli,0,0,sources/dehergne-p.cli
19,I,0,0,dehergne-q.cli,0,0,sources/dehergne-q.cli
20,I,0,0,dehergne-r.cli,0,0,sources/dehergne-r.cli
21,I,0,0,dehergne-s.cli,0,0,sources/dehergne-s.cli
22,I,0,0,dehergne-t.cli,0,0,sources/dehergne-t.cli
23,I,0,0,dehergne-u.cli,0,0,sources/dehergne-u.cli
24,I,0,0,dehergne-v.cli,0,0,sources/dehergne-v.cli
25,I,0,0,dehergne-w.cli,0,0,sources/dehergne-w.cli
26,I,0,0,dehergne-x.cli,0,0,sources/dehergne-x.cli
27,I,0,0,dehergne-y.cli,0,0,sources/dehergne-y.cli
28,I,0,0,dehergne-z.cli,0,0,sources/dehergne-z.cli

### Check the translation report

In [7]:
rpt = tlnb.get_translation_report(imported_files_df, 12)
print(rpt)

KleioTranslator - server version 12.9 - build 588 2025-06-06 16:04:22
18-1-2026 12-20

Processing data file dehergne-l.cli
-------------------------------------------
Generic Act translation module with geoentities (XML).
     Joaquim Ramos de Carvalho (joaquim@uc.pt)
** New document: kleio
=========================
kleio translation started
=========================
Structure: gacto2.str
Prefix:
Autorel:
Translation count: 190
Obs:
** Processing source fonte$dehergne-l
13: lista$dehergne-notices-l
*** End of File

Line 400 "SAME AS" TO EXTERNAL REFERENCE EXPORTED (deh-gabriel-leonard-de-brossard) CHECK IF IT EXISTS BEFORE IMPORTING THIS FILE.
Line 1066 "SAME AS" TO EXTERNAL REFERENCE EXPORTED (deh-pierre-martial-cibot) CHECK IF IT EXISTS BEFORE IMPORTING THIS FILE.
Line 1579 "SAME AS" TO EXTERNAL REFERENCE EXPORTED (deh-manuel-mendes) CHECK IF IT EXISTS BEFORE IMPORTING THIS FILE.

Structure file: /kleio-home/structures/sources.str
Structure processing report: /kleio-home/structures/sources.srpt
Structure in JSON: /kleio-home/structures/sources.str.json

Kleio file: /kleio-home/sources/dehergne-l.cli
Original file: /kleio-home/sources/dehergne-l.org
Previous version: /kleio-home/sources/dehergne-l.old
Temp file with ids: /kleio-home/sources/dehergne-l.ids
** - /kleio-home/sources/dehergne-l.cli-renamed to- /kleio-home/sources/dehergne-l.old
0  errors.
0  warnings.
Groups in this file:[irmao,referida,rel,referido,mae,pai,ls,n,lista,fonte,link,kleio]
Translation finished.

### Get the import report for a file

In case there are errors in the import phase check the import report.

In [8]:
rpt = tlnb.get_import_rpt(imported_files_df, rows=[13])
print(rpt)

dehergne-locations-1644.cli
No errors
No warnings

## Todo

This as data frame in a single function
* TimelinkNotebook.translate([files_df,paths=List[str], rows=List[int],status="T"])
* TimelinkNotebook.import([files_df,paths=List[str], rows=List[int],status="V"])


# Obter dados /  Getting data

### Procurar pessoa, mostrar em notação Kleio

---
### Search for people, show in Kleio notation

In [9]:
from timelink.api.models import Person

show_only=10

with tlnb.db.session() as session:
    ricci = session.query(Person).filter(Person.name.like('%Ricci')).all()

    for mr in ricci[:show_only]:
        print(mr.to_kleio())
        print()

referido$Matteo Ricci/m/id=deh-lazzaro-cattaneo-ref1
  ls$jesuita-tarefa/Toma o hábito de letrado/
  ls$tarefa/Romaniza os cinco tons do chinês/
  <rel$sociabilidade/Companheiro/Lazzaro Cattaneo/deh-lazzaro-cattaneo/1594
  ls$estadia/Shiuchow (Chao-tcheou)#@wikidata:Q1346617/1594
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1346617"%Shiuchow (Chao-tcheou)/1594

referido$Matteo Ricci/m/id=deh-giovanni-cola-niccolo-ref1
  <rel$sociabilidade/Companheiro/Giovanni Cola Niccolò/deh-giovanni-cola-niccolo/1582-08-07
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1582-08-07
  ls$chegada/Macau#@wikidata:Q14773/1582-08-07

referido$Matteo Ricci/m/id=deh-joao-barradas-ref1
  rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
  <rel$sociabilidade/Companheiro/João Barradas/deh-joao-barradas/1594
  ls$estadia/rio Kan#Rio Nam Khan, em Laos?/1594

referido$Matteo Ricci/m/id=deh-sabatino-de-ursis-ref1
  rel$institucional/Envia a Pequim/Sabatino De Ursis/deh-sabatino-de-ursis-ref1/
  rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
  <rel$sociabilidade/Companheiro/Sabatino De Ursis/deh-sabatino-de-ursis/1617-03-18

referido$Matteo Ricci/m/id=deh-jean-fernandes-tchong-ref1
  rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
  rel$sociabilidade/Envia em auxílio de Bento de Góis/Jean Fernandes Tchong/deh-jean-fernandes-tchong-ref1/1606

referido$Matteo Ricci/m/id=deh-sebastien-fernandes-tchong-ref2
  rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
  ls$tarefa/Estuda chinês e latim#com Tchong/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nanchang (Nantch'ang, Kiangsi)/
  ls$estadia/Nanchang (Nantch'ang, Kiangsi)#@wikidata:Q171943/
  <rel$sociabilidade/Companheiro/Sébastien Fernandes Tchong/deh-sebastien-fernandes-tchong/1591-01-01
  ls$jesuita-cargo/Mestre dos Noviços/1591-01-01
  <rel$sociabilidade/Companheiro/Sébastien Fernandes Tchong/deh-sebastien-fernandes-tchong/1598-09-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1598-09-07
  ls$estadia/Pequim#@wikidata:Q956/1598-09-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1598-11-05
  ls$estadia/Pequim#@wikidata:Q956/1598-11-05

referido$Matteo Ricci/m/id=deh-manuel-pereira-yeou-ref1
  rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1610
  ls$morte/Pequim#@wikidata:Q956/1610

n$Matteo Ricci/m/id=deh-matteo-ricci
  <rel$identification/same as/Matteo Ricci/deh-joao-barradas-ref1/
  <rel$identification/same as/Matteo Ricci/deh-sabatino-de-ursis-ref1/
  <rel$identification/same as/Matteo Ricci/deh-jean-fernandes-tchong-ref1/
  <rel$identification/same as/Matteo Ricci/deh-sebastien-fernandes-tchong-ref2/
  <rel$identification/same as/Matteo Ricci/deh-manuel-pereira-yeou-ref1/
  <rel$parentesco/pai/Giovanni Battista Ricci/deh-matteo-ricci-pai/
  <rel$parentesco/mae/Giovanna Angiolelli/deh-matteo-ricci-mae/
  <rel$identification/same as/Matteo Ricci/deh-michele-ruggiere-ref4/
  <rel$identification/same as/Matteo Ricci/deh-bento-de-gois-ref2/
  ls$nacionalidade/Itália/
  ls$jesuita-estatuto/Padre/
  ls$nome-chines/Li Ma-teou/
  ls$nome-chines/Si-T'ai/
  ls$tarefa/Calendário cristão na China#introduz?/
  ls$dehergne/684//obs=Ricci, Matteo (ital.) P. 684 Li Ma-teou, Si-T'al (Pf.., et non Ki-Jen, RBS 218)., en portugais Richo (DI. XI, 155, n. 19). N. 6 oct. 1552, Macerata, dans la Marche d'Ancône. E. noviciat St André du Quirinal, Rome, 16 août 1571 (Rom. 171A, 16: il signe: Matteo Riccio). Emb. sur le S. Luis, 24 mars 1578 (W 200)., arr. Goa, 13 sept., et Macao, 7 août 1582., août 1583, Canton., 10 sept. 1583, Shiuhing (Tchao-k'ing fou), où il fonde une résidence., oct. 1589, résidence à Shiuchow (Chao-tcheou)., du 21 mai 1595 au 15 juin, Nankin., 28 juin 1596 au 25 juin 1598, Nan-tch'ang fou., 5 juill. 1599, Nankin., 19 mai 1600, départ pour Pékin où il arr. le 24 janv. 1601, et où il fonde la mission du Hopei, 1601., Supérieur de la mission de Chine, d'août 1597 à sa mort., 1609, congrégation mariale. Pékin., calendrier chrétien en Chine (Pf. 117).
  ls$dehergne/684//obs=P. 25 juill. 1580, à Cochin, où il célèbre sa première messe le 26 juill. (D'Elia III, 22). V. Nan-tch'ang 1er janv. 1596 (D'Elia I, 374 et II, 4) pr. « Nanciani » ... Riccius (Lus. 2, 128). M. 11 mai 1610, Pékin (JS 113, 120-146., Planchet p. 222). Fils de Giovanni Battista Ricci, pharmacien, et de Giovanna Angiolelli, famille noble, marquis de Castelvecchio (D'Elia I, cii et II, 550). HS 43, 58 le fait mourir d'abord en 1609, puis le 11 mai 1610. Portrait: Pf. 31., D'Elia I, p. vi., ARSI Rom. 185, f° 97-98., BN: Estampes, Ne 100., en couleurs dans Bortone, P. Fernando,- Gesuiti alla corte di Pechino, 1969, pl. II p. 1., cf. Hamy. Pf. 22., Koch., NCE (F. A. Rouleau)., EC (Cel. Testore)., EB (J.S. Sebes)., CE (J. Brucker)., El (Tacchi Venturi). Bibliographie: SiRErr IV, p. 525-528., XII, p. 275-283., XIV. 1. p. 778.,
  ls$dehergne/684//obs=D'Elu III, 239-243. Biographie: en chinois: BN: Courant 9 (anonyme), 1014-1016 I, par Aleni, 1321 (par Pantoja, de Ursis)., et 6832 I, poème sur Rica. BernardE-MaÎtre], H., Le P. Matthieu Ricci et la société chinoise de son temps (1552-1610), Tientsin, 1937, 2 vol.., trad. chinoise par Wang Tch'ang-Tche, J., 1943., du même, Iles Philippines, 213-218 (sur la pensée de Ricci)., Cronin, Vincent, The Wise Man front the West, Londres, 1955., Dunne, G. H., Génération of Giants, 1962, p. 23-108., trad. franç. Chinois avec les Chinois, te P. Ricci et ses compagnons, Paris, 1964., Bortone, Fernando, P. Matteo Ricci, SJ.: Il « Saggio d'Occidente », 2' éd., 1965., trad. franç. en préparation. Le ms de Pires, Francisco, montre qu'il a failli être envoyé au Japon.Son oeuvre: Nocentini, Lod., --primo Sinologo, P.M.R., Florence, 1882.,
  ls$dehergne/684//obs=Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,. Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1., Son oeuvre: Nocentini, Lod., -- primo Sinologo, P.M.R., Florence, 1882., Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,- Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1.,
  ls$dehergne/684//obs=id.. L'apport scientifique du P. M. R à la Chine, Tientsin, 1935, dont trad. anglaise par Chalmers Werner, Edw., Pékin, 1935., id., L'attitude du P. M. R. en face des coutumes et rites chinois, RSRel. 28 (1938), 31-47., id., Les étapes de la cartographie scientifique pour ta Chine et tes pays voisins, MS I (1936), 428-477., Brou, A., Les tâtonnements du P. M. R., RHM 15 (1938), 228-244., Szczesniak, B., The Seventeenth Maps of China, Imago Mundi 17 (1956), 116-136, 9 cartes., id., Matteo Ricci's Maps of China, ibid , 11 (1954), 127-134., cf Giles, L., Geographicat Journal 52 (1918), 367-385 et 53 (1919), 19-30., Wallis, Helen, The Influence of Father R. on Far Eastern Cartography, Imago Mundi 19 (1965), 38-45, 5 cartes., Harris, George L., The Mission of M. R. A case study of an effort at guided culture change in the Sixteenth Century, MS 25 (1968), 1-168.,
  ls$dehergne/684//obs=Bettray, Johannes, S.V.D., Die akkomodationmethode des P. M. R., S.J., in China, Analecta Gregoriana, nº 76, Rome, 411 p.., Rule, Paul A., Jestât and Confucian? Chinese Religion in the journal of M.R, Journal of Religious History (Sidney, 1969), 105-124., D'Elia, P. M., Récent discoveries and New Studies (1938-1960) on the World Map in Chinese of F. M.R., SJ., MS XX (1961), 82-164., Danibl-Rops, Histoire de t'Eglise du Christ VI (Paris, 1966), 272-276, Le Christ entre au « Cathay » avec « Li Mateou »., Schutte, 996., DI. XII, 1031. Et nombre d'études sur des points spéciaux., par exemple, sur la Congré- gation mariale de Pékin: Du Manoir, Hubert, Maria t. IV, 968-972., NZM 1962, 255 citant Margiotti...
  ls$dehergne/684//obs=Sur l'art chinois: Sepp Schûller, P. M. Ricci und die christliche Kunst, Die Kath. Miss. LXIV (Diisseldorf, 1936), 3-8., H. Bernard [Maître], L'Art chré- tien en Chine au temps du P. M. R., RHM 12 (1935), 199-229., D'Elia, Le origini delt'arte cristiana cinese, Rome 1939. Sur l'influence au Japon des cartes de Ricci, Aleni et Verbiest, l'art, de Shintarô Ayusawa, MNipp. 19 (1964), 45-49. Sur le Ki-jen che p'ien, RBS 228 et 399. Principaux autographes de RICCI: — Son catéchisme, B. Casanatense ms 2136 G. I 1, daté de 1603, cf. JS 195.
  ls$dehergne/684//obs=— Délia Entrata delta Comp. nella Cina, avec additions de N. Trigault, JS 106a. Cf D'Elia. Une édition nouvelle, avec un important appareil documentaire et critique est en préparation à l'Université de Paris VII (Bulletin de Liaison, Ecole Pratique des Hautes Etudes, VI* section, 54 bd Raspail, 75006 Paris, vol. V (1972) p. 42. — La Carte de Chine, 28 sept. 1584, reproduite dans Colin, Francisco & Pastells, Pablo, Labor Evangelica .... Barcelone, 1902, III, planche, p. 448 (Arch. d. Ind., 145-7-7). Sa carte du Monde, supra. Gaibandi, Pietro, -- P. M.R e ta geografia délia Cina, Rivista di fisica, matematica e scienze naturali, Padua, VIII, 1903, 321-355, 459-464.
  ls$dehergne/684//obs=pécimen d'écriture, nom chinois et romanisation, Allan, pl. p. 49 (noter le -RI de Ricci, écrit à la fois RI et LI. Copie de la lettre du P. « Matheo Risi y Saliano » (1584) à Juan Bautista RomAn, facteur des îles Philippines à Macao, dans Carlos Sanz, Primitivas Relaciones de Espana con Asia y Oceania, Madrid, 1958, 372-384 (Archivos de Indias 67-6-29) et l'art, de Léon Lopetegui, Miss. Hisp. I, 1944, 341-352., Razén y Fe IV, 1902, 463477.
  ls$nota/JRC//obs="""

            Schutte, Monumenta historica japoniae I. 1280
            “18. Maji 1577 Roma discessit, in Lusitaniam se
            contulit, Conimbricae studio deditus;
            24. Martii 1578 e Lusitania in Indiam solvit,
            13. Sept. 1578 Goam advenit. Cochini deinceps
            et Goae studium prosecu-tus. litt. quoque human. docuit.”

            """
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q13135"%Macerata/1552-10-06
  ls$nascimento/Macerata#@wikidata:Q13135/1552-10-06
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q220"%Roma/1571-08-16
  ls$jesuita-entrada/Roma#@wikidata:Q220%(Noviciado de Sant'Andrea al Quirinale)/1571-08-16
  ls$partida-x/Roma#@wikidata:Q220/1577-05-18/obs=Schutte, Monumenta historica japoniae I.1280
  ls$partida-x@wikidata/"https://www.wikidata.org/wiki/Q220"%Roma/1577-05-18
  ls$estadia-x@wikidata/"https://www.wikidata.org/wiki/Q45412"%Coimbra/1577-06
  ls$estadia-x/Coimbra#@wikidata:Q45412/1577-06/obs="""
                  Ricci and Tacchi Venturi, Opere Storiche Del p. Matteo Ricci s. i.
                     de Junho de 1577 a fim de março de 1578, p. lxiii

                  Schutte, Monumenta historica japoniae I. 1280"""
  ls$embarque/S. Luís/1578-03-24
  ls$wicky/200/1578-03-24
  ls$wicky-viagem/25/1578-03-24
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q1171"%Goa/1578-09-13
  ls$chegada/Goa#@wikidata:Q1171/1578-09-13
  ls$jesuita-ordenacao-padre@wikidata/"https://www.wikidata.org/wiki/Q1800"%Cochim/1580-07-25
  ls$jesuita-ordenacao-padre/Cochim#@wikidata:Q1800/1580-07-25
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1800"%Cochim/1580-07-26
  ls$estadia/Cochim#@wikidata:Q1800/1580-07-26
  ls$tarefa/Celebra a primeira missa/1580-07-26
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1582-08-07
  ls$chegada/Macau#@wikidata:Q14773/1582-08-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16572"%Cantão/1583-08
  ls$estadia/Cantão#@wikidata:Q16572/1583-08
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q59164"%Shiuhing (Tchao-k'ing fou)/1583-09-10
  ls$estadia/Shiuhing (Tchao-k'ing fou)#@wikidata:Q59164/1583-09-10
  ls$jesuita-tarefa/Funda uma residência em Shiuhing/1583-09-10#depois
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1346617"%Shiuchow (Chao-tcheou)/1589-10
  ls$estadia/Shiuchow (Chao-tcheou)#@wikidata:Q1346617/1589-10
  ls$jesuita-tarefa/Funda uma residência em Shiuchow#?/1589-10#depois
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1595-05-21
  ls$estadia/Nanquim#@wikidata:Q16666/1595-05-21
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1595-06-15
  ls$estadia/Nanquim#@wikidata:Q16666/1595-06-15
  ls$jesuita-votos/4V/1596-01-01
  ls$jesuita-votos-local@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang/1596-01-01
  ls$jesuita-votos-local/Nan-tch'ang#@wikidata:Q171943/1596-01-01
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang fou/1596-06-28
  ls$estadia/Nan-tch'ang fou#@wikidata:Q171943/1596-06-28
  ls$jesuita-cargo/Superior da missão da China/1597-08
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang fou/1598-06-25
  ls$estadia/Nan-tch'ang fou#@wikidata:Q171943/1598-06-25
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1599-07-05
  ls$estadia/Nanquim#@wikidata:Q16666/1599-07-05
  ls$partida@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1600-05-19
  ls$partida/Pequim#@wikidata:Q956/1600-05-19
  ls$jesuita-tarefa/Funda a missão do Hopei/1601
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1601-01-24
  ls$chegada/Pequim#@wikidata:Q956/1601-01-24
  ls$estadia/Pequim#@wikidata:Q956/1609
  ls$jesuita-tarefa/Congregação marial de Pequim#funda?/1609
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1609
  ls$jesuita-cargo/Superior da missão da China/1610-05-11
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1610-05-11
  ls$morte/Pequim#@wikidata:Q956/1610-05-11
  pai$Giovanni Battista Ricci/m/id=deh-matteo-ricci-pai
    rel$parentesco/pai/Matteo Ricci/deh-matteo-ricci-pai/
    rel$parentesco/marido/Giovanna Angiolelli/deh-matteo-ricci-pai/
    ls$profissao/Boticário/
    ls$ec/c/1588
  mae$Giovanna Angiolelli/f/id=deh-matteo-ricci-mae/obs="""      Dehergne menciona família nobre, marqueses de Castelvecchio, mas não diz de
  que lado
  """
    <rel$parentesco/marido/Giovanni Battista Ricci/deh-matteo-ricci-pai/
    rel$parentesco/mae/Matteo Ricci/deh-matteo-ricci-mae/
    ls$ec/c/1588

pai$Giovanni Battista Ricci/m/id=deh-matteo-ricci-pai
  rel$parentesco/pai/Matteo Ricci/deh-matteo-ricci-pai/
  rel$parentesco/marido/Giovanna Angiolelli/deh-matteo-ricci-pai/
  ls$profissao/Boticário/
  ls$ec/c/1588

referido$Mateo Ricci/m/id=deh-joao-rodrigues-tcuzu-ref2
  <rel$institucional/Adversário/João Rodrigues Tçuzu/deh-joao-rodrigues-tcuzu/

In [23]:
from sqlalchemy import select

from timelink.api.models import Person, Attribute

show_only=10

with tlnb.db.session() as session:
    stmt = select(Person).join(Person.attributes.and_(Attribute.the_type == 'estadia',
                                                      Attribute.the_value.like('Pequim')))
    print(stmt)
    persons = session.execute(stmt).scalars().all()

    for person in persons[:show_only]:
        p = tlnb.db.get_person(person.id)
        print(p.to_kleio())

/var/folders/bc/41rz3hqn5335_y1tbvy1w2_w0000gp/T/ipykernel_64210/1907413544.py:10: SAWarning: An alias is being generated automatically against joined entity Mapper[Attribute(attributes)] due to overlapping tables.  This is a legacy pattern which may be deprecated in a later release.  Use the aliased(<entity>, flat=True) construct explicitly, see the linked example. (Background on this warning at: https://sqlalche.me/e/20/xaj2)
  print(stmt)
/var/folders/bc/41rz3hqn5335_y1tbvy1w2_w0000gp/T/ipykernel_64210/1907413544.py:11: SAWarning: An alias is being generated automatically against joined entity Mapper[Attribute(attributes)] due to overlapping tables.  This is a legacy pattern which may be deprecated in a later release.  Use the aliased(<entity>, flat=True) construct explicitly, see the linked example. (Background on this warning at: https://sqlalche.me/e/20/xaj2)
  persons = session.execute(stmt).scalars().all()

SELECT persons.id, entities.id AS id_1, entities.class, entities.inside, entities.the_order, entities.the_level, entities.the_line, entities.groupname, entities.updated, entities.indexed, persons.name, persons.sex, persons.obs
FROM entities JOIN persons ON entities.id = persons.id JOIN (entities AS entities_1 JOIN attributes AS attributes_1 ON attributes_1.id = entities_1.id) ON entities.id = attributes_1.entity AND attributes_1.the_type = :the_type_1 AND attributes_1.the_value LIKE :the_value_1
n$Joseph de Aguiar Souen/m/id=deh-joseph-de-aguiar-souen
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/China/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/Souen Jo-chö Kio-Jen To-Yin/0
  ls$nome/Suen Jo-chö Kio-Jen Touo-In/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q1015805"/17141125
  ls$nascimento/Changshu, Kiang-sou, China/17141125
  ls$jesuita-entrada/?/17420921
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/17510000
  ls$estadia/Pequim/17510000
  ls$jesuita-ordenacao-padre/?/17510000/obs=é capaz de ter sido em Pequim, dadas as datas
  ls$morte@/"https://www.wikidata.org/wiki/Q956"/17520101
  ls$morte/Pequim/17520101
  ls$dehergne/8/0/obs="""
      Aguiar Souen, Joseph de (chin.) P. 8 Souen Jo-chô Kio-Jen To-Yin (Pf.: Suen ... Touo-In). N. 25 nov. 1714, Changshu (Tch'ang-chou), Kiang-sou. E. 21 sept. 1742
  """
n$Giulio Aleni/m/id=deh-giulio-aleni
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/Itália/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/Giulio Alenis/0
  ls$nome/Giulio de Leni/0
  ls$nome/Giulio de Lenes/0
  ls$nome/Giulio Anhelis/0
  ls$nome/Giulio de Elenis/0
  ls$nome-chines/Ngai Jou-lio Sseu-Ki/0
  ls$nome-chines/Ngai Jou-lio Se-Ki/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q6221"/15820000
  ls$nascimento/Brescia/15820000
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q111218"/16001101
  ls$jesuita-entrada/Novellara/16001101
  ls$jesuita-tarefa/Pede para ir em missão ao Peru ou para outro local/16030516
  ls$jesuita-ordenacao-padre/?/16080000
  ls$embarque/Nossa Senhora da Piedade/16090323
  ls$wicky/550/16090323
  ls$wicky-viagem/50/16090323
  ls$estadia@/"https://www.wikidata.org/wiki/Q117196"/16100100
  ls$estadia/Salcete, Índia/16100100
  ls$tarefa/Observa um eclipse/16100100
  ls$estadia@/"https://www.wikidata.org/wiki/Q14773"/16100000
  ls$estadia/Macau/16100000
  ls$tarefa/Observa um eclipse/16110000
  ls$tarefa/Observa um eclipse/16120000
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/16130000
  ls$estadia/Pequim/16130000
  ls$estadia/Kaifeng, K'ai-fong fou (sinagoga)/0
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/0
  ls$estadia/Nanquim/0
  ls$estadia@/"https://www.wikidata.org/wiki/Q8686"/0
  ls$estadia/Shanghai/0
  ls$estadia@/"https://www.wikidata.org/wiki/Q57906"/0
  ls$estadia/Yangchow, Yang-tcheou/0
  ls$estadia@/"https://www.wikidata.org/wiki/Q4970"/16190000
  ls$estadia/Hangchow, Hang-tcheou, Chekiang, Tchô-kiang/16190000
  ls$jesuita-tarefa/Faz 250 baptismos/16190000
  ls$estadia/Kiangchow/16200000
  ls$jesuita-tarefa/Funda a missão do Shansi, Chan-si/16200000
  ls$estadia@/"https://www.wikidata.org/wiki/Q1015805"/16230000
  ls$estadia/Changshu, Tch'ang-chou, Kiangsu/16230000
  ls$jesuita-tarefa/Funda a missão de Fukien/16250400
  ls$estadia@/"https://www.wikidata.org/wiki/Q14773"/16390000
  ls$estadia/Macau/16390000
  ls$jesuita-cargo/Vice-Provincial da China/16410000
  ls$estadia/Yenping, Yen-p'ing, Fukien/16480000
  ls$jesuita-votos/4V/16240300
  ls$morte/Yean-sam, perto do monte chamado da Cruz, Yenping, Fukien/16490610
  ls$dehergne/17/0/obs="""
      Aleni (Alenis), Giulio (ital.) P. 17 Alenis, JS 134, 315., De Leni., De Lenes., Anhells., De Elenis. Ngal Jou-lio Sseu-Ki (Pf.: Ngal... Se-Kl). N. 1582, « Italus Brixensis » (JS 134, 303v) (Vert. 38, 36v): Brescia. E. 1 nov. 1600, Novellara. Demande le 16 mai 1603 les missions, et il précise: « Le Pérou, ou ailleurs ». P. vers 1608. Emb. sur le Na. Sra. da Piedade le 23 mars 1609 (W 550: P. Giulio De Leni)., janv. 1610, Salsette, où il observe une éclipse., 1610, Macao, d'où il tente vainement d'aller à Canton, et où il observe une éclipse, 1611-1612 (citée dans MARS VII, 705 et 798.,) 1613, Pékin., Kaifeng, K'ai-fong fou (synagogue), LEP IV 140., Nankin., Shanghai., Yangchow, Yang-tcheou., 1619, Hangchow, Hang-tcheou, Chekiang, Tchô-kiang, 250 baptêmes., 1620, Kiangchow, il fonde la mission du Shansi, Chan-si., 1623 Changshu, Tch'ang-chou, Kiangsu., avril 1625, il fonde la mission du Fukien, Fou-kien., 1639 exil à Macao.,
  """
  ls$dehergne/17/0/obs="""
      vice-provincial de Chine, 1641 (JS 134, 319) à Yenping, Yen-p'ing, Fukien, durant la conquête tartare, 1648.V. mars ou avril 1624, les documents sont perdus. M. 10 juin 1649, à Yen-sam «para o monte qua chamao da Cruz», près du mont appelé de la Croix (JA 49-V-13, 483v), Yenping, Fukien (HS 47, 72, suivi par Pf., dit: en août 1649). Pf. 126i., DHGE (E. M. Rivière)., EC (Lamalle)., DBI (P. Pirri)., NCE (J. V. Mentag).Biographies: Le « Confucius de l'Occident» (D'Elu, II 42 n. I., III 69)., Santambrogio, Mario, --Confucio dell'Occidente, Memorie Storiche delta Diocesi di Brescia, XVIII, Brescia, 1950, p. 21-32., vies chinoises, BN: Courant 1016-1017. Son oeuvre artistique et scientifique: AHSI, Ven. 37, 231, Catalogue de ses oeuvres., A. Favaro, Carteggio inedito de Tico Brahe, Giovanni Keptero e di altri celebri astronomi, Bologne, 1886, 347-349.,
  """
  ls$dehergne/17/0/obs="""
      H. Bernard-CMaitre], Les Etapes de la cartographie scientifique pour la Chine, MS I, 1936, 428477., Caraci, Gius. e Muccioli, Marcello, II mappamondo cinese del Padre G. A., Bollettino délia R. Società Geogr. ltaliana, VII, 3, Rome 1938, 386426., D'Elia, Le origini dell'arte cristiana cinese (1583-1640), Rome, 1939, 121 sq., L'Italia aile origini degli studi sulla Cina, Nuova Antologia LXXVII, 1942, vol. 422, p. 148-169., Galileo in Cina 1947, 29-33., Le « Generalità suite scienze occidentali di G. A.», Riv. degli studi orientait, XXV, 1950, 58-76., Dehergne, J., Une vie illustrée de N.S. au temps des Ming, NZM 14 (1958), 103-115., Brunner, 95-96., Needham, III, 584, carte de 1623., Mish, John L., Creating an Image of Europe for China, Aleni's Hsi-fang ta-wen, MS 23 (1964), 4-87., Van Hecken, J. L., Une version mongole du Wan-ou-tchen-yuen du P. A., NZM 22 (1966), 98-108.,
  """
  ls$dehergne/17/0/obs="""
      vice-provincial de Chine, 1641 (JS 134, 319) à Yenping, Yen-p'ing, Fukien, durant la conquête tartare, 1648.Streit V, 2075, et XII p. 564, 584., XIV, I pp. 438-441, écrits religieux etc. - Courant 1519., 9549., 10988 (72). Portrait: BN: Mss Fonds chinois 1017 (signalé par le P. Lamalle).
  """
n$José de Almeida/m/id=deh-jose-de-almeida-i
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/Portugal/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/José de Almeyda/0
  ls$chegada/?/16400000
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/16450000
  ls$estadia/Pequim/16450000
  ls$estadia@/"https://www.wikidata.org/wiki/Q14773"/16480000
  ls$estadia/Macau/16480000
  ls$estadia@/"https://www.wikidata.org/wiki/Q16572"/16630319
  ls$estadia/Cantão (missão)/16630319
  ls$dehergne/20/0/obs="""
      Almeida (Almeyda), José (port.) (I) P. 20 A. 1640., v. 1645, Pékin., 1648, Macao (JS 134, 337)., 19 mars 1663, mission de Canton (JS 25, 279).
  """
n$José Bernardo de Almeida/m/id=deh-jose-bernardo-de-almeida
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/Portugal/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/José Bernardo de Almeyda/0
  ls$nome-chines/So To-Tch'ao Yue-Tch'ang/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q576924"/17280918
  ls$nascimento/Penela, diocese de Coimbra/17280918
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q15041623"/17460223
  ls$jesuita-entrada/Lisboa/17460223
  ls$embarque/[Para a China]/17550000
  ls$embarque/[Para a China]/17580000
  ls$wicky/2099/17550000
  ls$wicky/2099/17580000
  ls$wicky-viagem/?/17550000
  ls$wicky-viagem/?/17580000
  ls$estadia@/"https://www.wikidata.org/wiki/Q148"/17590513
  ls$estadia/China/17590513
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/17590000
  ls$estadia/Pequim/17590000
  ls$cargo/Presidente do Tribunal da Matemática de Pequim/17790000
  ls$titulo/Mandarim de 3ª classe/17790000
  ls$cargo/Vice-presidente do Tribunal da Matemática de Pequim/17930000
  ls$cargo/Presidente do Tribunal da Matemática de Pequim/18000000
  ls$cargo/Chefe dos intérpretes da embaixada inglesa/17930819
  ls$profissao/Médico/0
  ls$profissao/Boticário/0
  ls$morte@/"https://www.wikidata.org/wiki/Q956"/18051112
  ls$morte/Pequim/18051112
  ls$dehergne/23/0/obs="""
      Almeida (Almeyda), José Bernardo de (por) (IV) P. 23 So Tö-Tch'ao Yue-Tch’ang (Pf.: Souo Té-Tch'ao). N. 18 sept. 1728, Penella, d. de Coïmbre (Lus. 49, 58) le 15 janv. 1728 dit PLANCHET. E. 23 févr. 1746, Arroios près de Lisbonne (Lus. 49, 129., W p. 428: Josephus BERNARDUS). Emb. entre 1755 et 1758 (W 2099 l'appelle Joäo Bernardo de ALMEIDA) non prêtre., A. 13 mai 1759 (Lus. 49, 139)., Pékin, 1759., président du Tribunal des Mathématiques à Pékin de 1779(?) à 1793 mais aussi médecin et pharmacien. V. la formule des voeux n’a pas été retrouvée. M. 12 nov. 1805, Pékin (PLANCHET p. 154). PF. 886., Rodrigues F., Jesuítas Portugueses Astrónomos na China, 1925. Revisto JRC 13-6-2020
  """
n$José Estêvão de Almeida/m/id=deh-jose-estevao-de-almeida
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/Portugal/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/José Estêvão de Almeyda/0
  ls$nome/Joseph Dalmeida/0
  ls$nome/Stephanus Almeida Fan/0
  ls$nome-chines/Fan/0
  ls$nome-chines/Mei Kao Yun-Tiao/0
  ls$nome-chines/Yue-Ts'ing/0
  ls$nome-chines/Mei/0
  ls$nome-chines/Miu/0
  ls$nome-chines/Moui Cao/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q2258588"/16120000
  ls$nascimento/Esgueira, diocese de Coimbra/16120000
  ls$jesuita-entrada/?/16280000
  ls$embarque/Sacramento/16290403
  ls$wicky/773/16290403
  ls$wicky-viagem/67/16290403
  ls$estadia/Sian (Si-ngan fou), Shensi/16400000
  ls$estadia/Puchow, Shansi/16450000
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/0
  ls$estadia/Pequim/0
  ls$morte/?/16470000
  ls$dehergne/24/0/obs="""
      Almeida (Almeyda), José Estevâo de (port.) (V) P. 24 Joseph Dalmeida (JS 134, 320)., Stephanus Almeida Fan (JS 187, 3v, 5: appelé Fan comme le José de A. (II) ci-dessus). Mei Kao Yun-ïïao (Pf.) Yue-Ts'ing. On trouve Mei transcrit Miu--Mieou (M. 443, 671). Borg. Lat. 523 f 58: Moui Cao. N. 1612, Esgueira (JS 134, 320) -E. 1628. Emb. étant novice, sur le Sacramento, 3 avril 1629 (W 773: José de A.)., 1640 ou 1641, Sian (Si-ngan fou), Shensi., 1645, Puchow, Shansi., puis Pékin (Margiotti, p. 139). M. 1647 (HS 47, 68v: Joseph de A.). Pf. dit: 1644, massacré près de Nanchang (Nan-tch'ang fou) durant la guerre civile. Pf. 248.
  """
n$Sebastião de Almeida/m/id=deh-sebastiao-de-almeida
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/Portugal/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/Sebastião de Almeyda/0
  ls$nascimento/Lagéas/16220000
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q1171"/16370000
  ls$jesuita-entrada/Goa/16370000
  ls$embarque/S. Pedro de Alcântara/16650420
  ls$wicky/1068/16650420
  ls$wicky-viagem/93/16650420
  ls$estadia@/"https://www.wikidata.org/wiki/Q1171"/0
  ls$estadia/Goa/0
  ls$jesuita-cargo/Reitor/0
  ls$jesuita-cargo/Procurador/0
  ls$estadia@/"https://www.wikidata.org/wiki/Q220"/0
  ls$estadia/Roma/0
  ls$embarque/?/16680422
  ls$wicky/1102a/16680422
  ls$wicky-viagem/96/16680422
  ls$cargo/Bispo eleito do Japão/0/obs=nunca foi sagrado
  ls$jesuita-cargo/Visitador do Japão e da China/16770803
  ls$jesuita-cargo/Visitador do Japão e da China/16800000
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/16780113
  ls$estadia/Pequim/16780113
  ls$jesuita-votos/4V/16591202
  ls$jesuita-votos-local@/"https://www.wikidata.org/wiki/Q1171"/16591202
  ls$jesuita-votos-local/Goa/16591202
  ls$morte/?/16830000
  ls$dehergne/26/0/obs="""
      Almeida (Almeyda), Sebastiâo de (port.) P. 26 N. 1622, à Lagéas -E. Goa, 1637 (Goa 25, 122v). Emb. sur le S. Pedro de Alcantara, 20 avril 1665 (W 1068) pour Goa, où recteur., nommé procureur, il va à Rome et revient, emb. 22 avril 1668 (W 1102a) comme évêque élu du Japon., mais il ne sera jamais sacré., visiteur de Chine et du Japon du 25 janv. 1674 (JS 25, 293), en fait, de 1677 à 1680., il écrit de Pékin le 13 janv. 1678 (JS 124, 114). V. 2 déc. 1659, pr., Goa (Lus. 7, 271). Il signe: «Dalm.da». M. après 1682, HS 49, 242v: M. en 1683. Il signe: Seb.am d'Alm.da> (août 1678, JS 19, 80v etc.).
  """
n$Jean-Joseph-Marie Amiot/m/id=deh-jean-joseph-marie-amiot
  rel$function-in-act/n/dehergne-notices-a/0
  ls$nacionalidade/França/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/Jean-Joseph-Marie Amyot/0
  ls$nome-chines/Ts'ien Tö-Ming/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q44160"/17180208
  ls$nascimento/Toulon/17180208
  ls$baptizado@/"https://www.wikidata.org/wiki/Q44160"/17180208
  ls$baptizado/Toulon/17180208
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q6397"/17370927
  ls$jesuita-entrada/Avignon/17370927
  ls$estadia@/"https://www.wikidata.org/wiki/Q71724"/17491229
  ls$estadia/Lorient/17491229
  ls$embarque/Villeflix/17491229
  ls$estadia@/"https://www.wikidata.org/wiki/Q16572"/17500727
  ls$estadia/Cantão/17500727
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/17510822
  ls$estadia/Pequim/17510822
  ls$profissao/Astrónomo/0
  ls$profissao/Escrivão/0
  ls$jesuita-cargo/Procurador da missão francesa/17610000
  ls$jesuita-ordenacao-padre/?/17461221
  ls$jesuita-votos/4V/17541101
  ls$jesuita-votos-local@/"https://www.wikidata.org/wiki/Q956"/17541101
  ls$jesuita-votos-local/Pequim/17541101
  ls$morte@/"https://www.wikidata.org/wiki/Q956"/17931008
  ls$morte/Pequim/17931008
  ls$dehergne/35/0/obs="""
      Amiot (Amyot), Jean-Joseph-Marie (franç.) P. 35 Tsïen Tô-Ming (Pf.). N. « Telonensis », Toulon 8 févr. 1718 -E. 27 sept. 1737, Avignon (Ly) Emb. Lorient 29 déc. 1749 sur le Villeflix avec les PP. Lieou et K'ang (AN: Col. F5B 49). Arr. Canton 27 juill. 1750 (JS 134, 444)., Pékin 22 août 1751., astronome., écrivain., 1761, procureur de la mission française., 18 nov. 1779, Louis XVI lui signe le brevet de supérieur des missions françaises en Chine, en cas d'empêchement du P. Bourgeois (AN: Col. F5A 80 f° 194). En 1780 Vergennes le propose comme vicaire apostolique de Pékin (Col. F5A 23 f° 33, 40 et 64). P. 21 déc. 1746 par Mgr Franç. Hugon, évêque Philadelph., suffragant de l'évêque de Besançon (Liste 1700-1760, Arch. S.J., Lyon). V. Pékin, 1 nov. 1754, pr. Il signe: Josephus-Maria Amiot (Gai. 23, 170).
  """
  ls$dehergne/35/0/obs="""
      M. nuit du 8 au 9 oct. 1793, Pékin (B. Inst. ms. 1517 f° 147v). Acte de naissance: fils aîné de Louis Amiot, notaire royal à Toulon., « est né et a été baptisé le huict février 1718 en la paroisse cathédrale Ste Marie de la Seds, à Toulon » (photocopie aimablement envoyée par M. Louis Janvier). Ses parents sont dits « gens de mer ».Portrait: MCC t. XV, 1791, frontispice avec ce titre: M. Amyot, Correspondant de l'Acad. des Inscriptions et Belles Lettres., Hamy, Alfred, Gâterie illustrée de la Compagnie de Jésus, Paris, 1893. M. George Loehr a retrouvé le portrait dessiné (avant 1790) par Panzi, à BN: Estampes 951-N.4., cf. B. Inst., Paris ms 1515 au début (en couleurs) et ms 1516, en-tête (gravé à Paris par Helman) et ms 1519.
  """
  ls$dehergne/35/0/obs="""
      Beaucoup de ses mss sont à BN. ms fr.., ms chin.., ms Bréquigny., Estampes et à B. Inst. — Il signe toujours Amiot, jamais Amyot. Streit VII, 3419 a souligné l'importance d'AMiOT pour l'histoire de la sinologie: il fit connaître à la France l'empereur K'Ien Long, et, à ce titre, il se trouva tout désigné pour prendre la relève de Yang et Kao (v. ces mots) dans la préparation de sa Correspondance littéraire, et autres travaux publiés en la collection connue sous ce titre résumé Mémoires concernant les Chinois (cf. MCC t. I, p. IV) depuis 1776 à 1814. Cf. aussi La Chine au temps des Lumières, t. I, Henri Bertin dans le sillage de la Chine (par J. S. de Sacy et M. Antoine, Paris, Les Belles Lettres, 1970).
  """
  ls$dehergne/35/0/obs="""
      Pf. 837., DHGE (E.M. Rivière)., DBF (H. Chomon)., NCE (B. Lahiff) - Rochbmonteix, C. de, Joseph Amiot et les derniers survivants de la Mission française à Pékin 1750-1795, Paris, 1915 ., Amyot, Alphonse, Vie et testament du R. P. Amiot, Paris, 1881., Davin, Emm., dans Bull. Association Guill. Budé, Paris, 1961, 380-395., Huard, Sonolet, Wong, Mesmer en Chine, Trois lettres médicales du R. P. Amiot, Rev. de Synthèse t. 81 (i960), 61-98., Streit VII 3419., XII 1135. Dissertation on the Music of the Chinese, Ancient and Modem. By JeanJoseph-Marie Amiot. Translated by Bryna Lieberman, edited by Frédéric Lmberman, Brown University, Providence, Rhode Island. En préparation.
  """
  pai$Louis Amiot/m/id=deh-jean-joseph-marie-amiot-pai
    rel$function-in-act/pai/dehergne-notices-a/0
    ls$profissao/Notário/0
    ls$cargo/Notário régio em Touloun/0
  referido$Jean-Régis-Lieou/m/id=deh-jean-joseph-marie-amiot-ref1
    rel$function-in-act/referido/dehergne-notices-a/0
    ls$estadia@/"https://www.wikidata.org/wiki/Q71724"/17491229
    ls$estadia/Lorient/17491229
    ls$embarque/Villeflix/17491229
  referido$Philippe-Stanislas K'ang/m/id=deh-jean-joseph-marie-amiot-ref2
    rel$function-in-act/referido/dehergne-notices-a/0
    ls$estadia@/"https://www.wikidata.org/wiki/Q71724"/17491229
    ls$estadia/Lorient/17491229
    ls$embarque/Villeflix/17491229
  referido$Luís XIV/m/id=deh-deh-jean-joseph-marie-amiot-ref3
    rel$function-in-act/referido/dehergne-notices-a/0
    ls$tarefa/Assina o brevete de Amiot como superior das missões francesas na China em caso de impedimento do P. Bourgeois/17791118
  referido$François Bourgeois/m/id=deh-jean-joseph-marie-amiot-ref4
    rel$function-in-act/referido/dehergne-notices-a/0
    ls$jesuita-cargo/Superior das missões francesas na China/17791118
  referido$Vergennes/m/id=deh-jean-joseph-marie-amiot-ref5
    rel$function-in-act/referido/dehergne-notices-a/0
    rel$eclesiástica/Propõe como vigário apostólico de Pequim/Jean-Joseph-Marie Amiot/deh-jean-joseph-marie-amiot/17800000
  referido$François Hugon/m/id=deh-jean-joseph-marie-amiot-ref6
    rel$function-in-act/referido/dehergne-notices-a/0
    rel$eclesiastica/Ordena/Jean-Joseph-Marie Amiot/deh-jean-joseph-marie-amiot/17461221
    ls$cargo/Bispo de Filadélfia/17461221
    ls$cargo/Sufragâneo do bispo de Besançon/17461221
  rel$sociabilidade/Companheiro/Jean-Régis-Lieou/deh-jean-joseph-marie-amiot-ref1/17491229
  rel$sociabilidade/Companheiro/Philippe-Stanislas K'ang/deh-jean-joseph-marie-amiot-ref2/17491229
  rel$identification/same as/Jean-Régis-Lieou/deh-jean-regis-lieou/0
n$Florian Joseph Bahr/m/id=deh-florian-joseph-bahr
  rel$function-in-act/n/dehergne-notices-b/0
  ls$nacionalidade/Alemanha/0
  ls$jesuita-estatuto/Padre/0
  ls$nome/Florian Joseph Baal/0
  ls$nome-chines/Wei Fouleang Ki-Tsin Chan-Sieou/0
  ls$nome-chines/Kouei Ki-Pou/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q1003112"/17060814
  ls$nascimento/Falkenberg, Silésia/17060814
  ls$grau-academico/Mestre em Artes/0
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q14960"/17261009
  ls$jesuita-entrada/Brno, República Checa/17261009
  ls$embarque/[Para a Índia]/17370000
  ls$wicky/1841/17370000
  ls$wicky-viagem/156/17370000
  ls$estadia@/"https://www.wikidata.org/wiki/Q14773"/17380805
  ls$estadia/Macau/17380805
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/17390301
  ls$estadia/Pequim/17390301
  ls$profissao/Músico/0
  ls$cargo/Músico da corte/17390301
  ls$jesuita-cargo/Visitador do Japão e da China/17620000
  ls$jesuita-cargo/Visitador do Japão e da China/17710000
  ls$jesuita-tarefa/Obra das crianças abandonadas/0
  ls$jesuita-votos/4V/17410202



###  Obter um dataframe a partir de atributos

---


###  Get a Dataframe from attributes

#### Exemplo: Missionários que estiveram em Pequim, onde entraram
na ordem, e que nacionalidade tinham.

In [24]:
from timelink.pandas import entities_with_attribute


# Get list of people with with a certain value in a specific attribute
df = entities_with_attribute(
                    entity_type='person',
                    the_type='estadia',
                    the_value='Pequim',
                    more_info=['name'],
                    more_cols=['jesuita-entrada','nacionalidade'],
                    db=tlnb.db,
                    sql_echo=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 247 entries, deh-adrien-grelon to deh-vicent-caun
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  247 non-null    object
 1   estadia               247 non-null    object
 2   estadia.date          247 non-null    object
 3   estadia.obs           15 non-null     object
 4   jesuita-entrada       206 non-null    object
 5   jesuita-entrada.date  206 non-null    object
 6   jesuita-entrada.obs   3 non-null      object
 7   nacionalidade         222 non-null    object
 8   nacionalidade.date    222 non-null    object
 9   nacionalidade.obs     1 non-null      object
dtypes: object(10)
memory usage: 21.2+ KB

In [25]:
df.head(55).sort_values('jesuita-entrada')

,name,estadia,estadia.date,estadia.obs,jesuita-entrada,jesuita-entrada.date,jesuita-entrada.obs,nacionalidade,nacionalidade.date,nacionalidade.obs
id,,,,,,,,,,
deh-adrien-grelon,Adrien Grelon,Pequim,16650613,None,?,16430601,None,França,0,None
deh-bernhard-diestel,Bernhard Diestel,Pequim,0,None,?,16391022,None,Alemanha,0,None
deh-bernard-rodes,Bernard Rodes,Pequim,0,None,?,16740707,None,França,0,None
deh-antonio-simoes-i,António Simões,Pequim,17480000,None,?,16780000,None,Portugal,0,None
deh-antonio-leitao,António Leitão,Pequim,16030000,None,?,16030000,None,China,0,None
deh-antonio-de-barros,António de Barros,Pequim,17010700,None,?,16810612,None,Portugal,0,None
deh-antonio-de-barros,António de Barros,Pequim,16971000,None,?,16810612,None,Portugal,0,None
deh-anton-gogeisl,Anton Gogeisl,Pequim,17390301,None,?,17200913,None,Alemanha,0,None
deh-caetano-lopes,Caetano Lopes,Pequim,17270000,None,?,17070217,None,Portugal,0,None
deh-felix-da-rocha,Félix da Rocha,Pequim,17560321,None,?,17280501,None,Portugal,0,None
deh-antoine-de-beauvollier,Antoine de Beauvollier,Pequim,17061017,None,?,16720907,None,França,0,None
deh-alexandre-de-la-charme,Alexandre de La Charme,Pequim,17290300,None,?,17120907,None,França,0,None
deh-andre-palmeiro,André Palmeiro,Pequim,16280000,None,?,15840114,None,Portugal,0,None
deh-adrien-grelon,Adrien Grelon,Pequim,16940900,None,?,16430601,None,França,0,None
deh-andre-pereira,André Pereira,Pequim,17240905,None,?,17070617,None,Portugal,0,None
deh-dominique-parrenin,Dominique Parrenin,Pequim,0,None,Avignon,16850901,None,França,0,None
deh-claude-motel,Claude Motel,Pequim,16650700,None,Avignon,16381111,None,França,0,None
deh-charles-de-belleville,Charles de Belleville,Pequim,16990000,None,Bordeaux,16801125,None,França,0,None
deh-claudio-filippo-grimaldi,Claudio Filippo Grimaldi,Pequim,16940828,None,Chieri,16580113,None,Itália,0,None
deh-claudio-filippo-grimaldi,Claudio Filippo Grimaldi,Pequim,16851107,None,Chieri,16580113,None,Itália,0,None
deh-claudio-filippo-grimaldi,Claudio Filippo Grimaldi,Pequim,16710000,None,Chieri,16580113,None,Itália,0,None
deh-feliciano-da-silva,Feliciano da Silva,Pequim,16110503,None,Coimbra,15931215,None,Portugal,0,None
deh-antonio-de-magalhaes,António de Magalhães,Pequim,17160000,None,Coimbra,16921019,None,Portugal,0,None
deh-antonio-gomes,António Gomes,Pequim,17440000,None,Coimbra,17250528,None,Portugal,0,None
deh-antonio-de-magalhaes,António de Magalhães,Pequim,17261119,com o embaixador português Metello e audiência...,Coimbra,16921019,None,Portugal,0,None
deh-cristoforo-fiori,Cristoforo Fiori,Pequim,16941000,None,Goa,16910000,None,Itália,0,None
deh-antonio-faglia,Antonio Faglia,Pequim,0,None,Génova,16830127,None,Itália,0,None
deh-ehrenbert-xaver-fridelli,Ehrenbert Xaver Fridelli,Pequim,17100000,None,Leoben,16881012,None,Áustria,0,None
deh-ehrenbert-xaver-fridelli,Ehrenbert Xaver Fridelli,Pequim,17210724,None,Leoben,16881012,None,Áustria,0,None
deh-ehrenbert-xaver-fridelli,Ehrenbert Xaver Fridelli,Pequim,17070000,None,Leoben,16881012,None,Áustria,0,None
deh-carlos-de-resende,Carlos de Resende,Pequim,17250000,None,Lisboa,16800218,None,Portugal,0,None
deh-cristoforo-fiori,Cristoforo Fiori,Pequim,16941000,None,Lisboa,16921106,None,Itália,0,None
deh-carlos-de-resende,Carlos de Resende,Pequim,0,None,Lisboa,16800218,None,Portugal,0,None
deh-andrea-giovanni-lubelli,Andrea-Giovanni Lubelli,Pequim,16650000,None,Nápoles,16280330,None,Itália,0,None
deh-etienne-yang,Etienne Yang,Pequim,17890000,None,Paris,17590310,None,China,0,None
deh-etienne-rousset,Etienne Rousset,Pequim,17191100,None,Paris,17140425,None,França,0,None
deh-claude-de-visdelou,Claude de Visdelou,Pequim,16880207,None,Paris,16730905,None,França,0,None
deh-cyr-contancin,Cyr Contancin,Pequim,17110000,None,Paris,16880909,None,França,0,None
deh-aloys-kao,Aloys Kao,Pequim,17510107,None,Paris,17590310,None,China,0,None
deh-aloys-kao,Aloys Kao,Pequim,17660509,None,Paris,17590310,None,China,0,None
deh-emmanuel-de-silva-tchang,Emmanuel de Silva Tchang,Pequim,17430000,None,Pequim,17331031,None,China,0,None
deh-emmanuel-de-silva-tchang,Emmanuel de Silva Tchang,Pequim,17440000,None,Pequim,17331031,None,China,0,None
deh-emmanuel-de-silva-tchang,Emmanuel de Silva Tchang,Pequim,17660000,None,Pequim,17331031,None,China,0,None
deh-domingos-mendes-kieou,Domingos Mendes K'ieou,Pequim,16130000,None,Shiuchow,16050000,None,China,0,None
deh-antoine-gaubil,Antoine Gaubil,Pequim,17400000,None,Toulouse,17040912,None,França,0,None
deh-antoine-thomas,Antoine Thomas,Pequim,16861107,None,Tournai,16600924,None,Bélgica,0,None
deh-christian-wolfgang-henriques-herdtrich,Christian Wolfgang Henriques Herdtrich,Pequim,16730600,None,"Viena, Áustria",16411027,None,Áustria,0,None
deh-august-von-hallerstein,August von Hallerstein,Pequim,17390301,None,"Viena, Áustria",17211027,None,Áustria,0,"território austríaco, actualmente é Eslovénia"
deh-antoine-thomas-ref4,Charles Thomas Maillard de Tournon,Pequim,17052104,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-antonio-de-magalhaes-ref1,Alexandre Metelo de Sousa e Meneses,Pequim,17261119,None,NaN,NaN,NaN,Portugal,0,None
deh-antonio-de-magalhaes-ref2,Yong-Tcheng,Pequim,17261124,None,NaN,NaN,NaN,China,0,None
deh-antonio-francesco-giuseppe-provana-ref1,Charles Thomas Maillard de Tournon,Pequim,17050800,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-caetano-lopes-ref1,Alexandre Metelo de Sousa e Meneses,Pequim,17270000,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-claudio-filippo-grimaldi-ref3,Charles Thomas Maillard de Tournon,Pequim,17060520,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-etienne-rousset-ref1,François Xavier Dentrecolles,Pequim,1721215,None,NaN,NaN,NaN,NaN,NaN,NaN



###  Remover colunas sem valores

---



###  Remove empty columns

In [27]:
df.dropna(how='all', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 247 entries, deh-adrien-grelon to deh-vicent-caun
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  247 non-null    object
 1   estadia               247 non-null    object
 2   estadia.date          247 non-null    object
 3   estadia.obs           15 non-null     object
 4   jesuita-entrada       206 non-null    object
 5   jesuita-entrada.date  206 non-null    object
 6   jesuita-entrada.obs   3 non-null      object
 7   nacionalidade         222 non-null    object
 8   nacionalidade.date    222 non-null    object
 9   nacionalidade.obs     1 non-null      object
dtypes: object(10)
memory usage: 21.2+ KB

In [28]:
df.head(5)

,name,estadia,estadia.date,estadia.obs,jesuita-entrada,jesuita-entrada.date,jesuita-entrada.obs,nacionalidade,nacionalidade.date,nacionalidade.obs
id,,,,,,,,,,
deh-adrien-grelon,Adrien Grelon,Pequim,16650613,None,?,16430601,None,França,0,None
deh-adrien-grelon,Adrien Grelon,Pequim,16940900,None,?,16430601,None,França,0,None
deh-alexandre-de-la-charme,Alexandre de La Charme,Pequim,17290300,None,?,17120907,None,França,0,None
deh-aloys-kao,Aloys Kao,Pequim,17510107,None,Paris,17590310,None,China,0,None
deh-aloys-kao,Aloys Kao,Pequim,17660509,None,Paris,17590310,None,China,0,None


## Contagens

---

## Counting


###  Contagem de atributos a partir de uma tabela em memória

---

###  Count attributes from an existing dataframe

In [29]:
# create a column with the index values which are the id numbers
df['id'] = df.index.values

col = 'jesuita-entrada' # subotal by this column

# Use pandas groupby and specify unique value count for id
df_totals = df.groupby(col).agg({'id':'nunique',
                                                  'estadia':'min',
                                                  'estadia':'max'})

df_totals.sort_values('id',ascending= False).head(30)

                                              id estadia
jesuita-entrada
?                                             58  Pequim
Paris                                         16  Pequim
Lisboa                                         7  Pequim
Nancy                                          7  Pequim
Coimbra                                        6  Pequim
Avignon                                        6  Pequim
Roma                                           5  Pequim
Viena, Áustria                                 4  Pequim
Génova                                         4  Pequim
Nápoles                                        4  Pequim
Roma (Noviciado de Sant'Andrea al Quirinale)   3  Pequim
Landsberg                                      3  Pequim
Bordeaux                                       3  Pequim
Brno, República Checa                          2  Pequim
Macau                                          2  Pequim
Japão                                          2  Pequim
Pequim                                         2  Pequim
Goa                                            2  Pequim
Chieri                                         1  Pequim
Cracóvia                                       1  Pequim
Leoben                                         1  Pequim
Douai                                          1  Pequim
Novellara                                      1  Pequim
Nanquim                                        1  Pequim
Nan-tch'ang                                    1  Pequim
Messina, Sicília                               1  Pequim
Mainz                                          1  Pequim
Mechelen                                       1  Pequim
Portugal                                       1  Pequim
Palermo, Sicília                               1  Pequim


### Contagens na base de dados

Quando o atributo tem muitos valores e não é necessário
ter todas as pessoas em memória: contagem feita na base de dados

---

### Counting directly in the database
When there are many values and it is not
necessary to have all the people in memory:
count directly in the database.

In [44]:
from timelink.pandas import attribute_values

df_totals = attribute_values('estadia', dates_between=("1580-00-00","1610-00-00"),db=tlnb.db)
df_totals.head(20)

                                        count  date_min  date_max
value
Macau                                      38  15800000  16080000
Goa                                        15  15820426  16010501
Japão                                      15  15820220  16090000
Nanquim                                    14  15950521  16090000
Cantão                                     11  15800400  16060200
Nagasaki                                    8  15830725  16060000
Pequim                                      7  15980907  16090000
Roma                                        6  15820000  16080000
Shiuchow (Chao-tcheou)                      6  15891000  16080000
Chao-tcheou                                 4  15910700  16050100
Arima (seminário), Japão                    3  15830000  15880000
China                                       3  15820000  15930000
Malaca                                      3  15820600  16040000
Nan-tch'ang fou                             3  15960628  16090515
Sciaochino (Shiuhing, Tchao-k'ing fou)      3  15820000  15820000
Cantão (feira)                              2  15810400  15810400
Chao-hing                                   2  15850000  15850000
Cochim                                      2  15800726  15970429
Lisboa                                      2  15860411  15960410
México                                      2  15820000  15920000

#### Filtrar por datas

---

#### Filter by dates

In [45]:
df_totals = attribute_values('jesuita-entrada',dates_between=('1580','1600'),db=tlnb.db)

In [47]:
df_totals.head(10)

                           count  date_min  date_max
value
?                             25  15830000  15980000
Coimbra                        7  15840000  15961216
Roma                           5  15800317  15941106
Douai                          2  15941109  15990512
Nápoles                        2  15910908  15971106
Shiuchow, Chao-tcheou fou      2  15891100  15891100
Arona                          1  15960921  15960921
Goa                            1  15870000  15870000
Japão                          1  15801200  15801200
Messina, Sicília               1  15820000  15820000

## Visualizar registos

---

## View records

### Visualizar uma pessoa

---

### View a person

#### Atributos de uma pessoa numa tabela, uma linha por attributo

---

#### Person attributes in a dataframe, one line per attribute

In [48]:
import pandas as pd
from timelink.pandas import group_attributes as person_attributes

pd.set_option('display.max_rows',1000)

id = 'deh-matteo-ricci'
pdf = person_attributes([id],db=tlnb.db)  # note id in a list
pdf[['date','type','value','attr_obs']].sort_values(['date','type'])

,date,type,value,attr_obs
id,,,,
deh-matteo-ricci,0,dehergne,684,"Ricci, Matteo (ital.) P. 684 Li Ma-teou, Si-T'..."
deh-matteo-ricci,0,dehergne,684,"P. 25 juill. 1580, à Cochin, où il célèbre sa ..."
deh-matteo-ricci,0,dehergne,684,"D'Elu III, 239-243. Biographie: en chinois: BN..."
deh-matteo-ricci,0,dehergne,684,"Tacchi-Venturi, Opère storiche del P. M. R., M..."
deh-matteo-ricci,0,dehergne,684,id.. L'apport scientifique du P. M. R à la Chi...
deh-matteo-ricci,0,dehergne,684,"Bettray, Johannes, S.V.D., Die akkomodationmet..."
deh-matteo-ricci,0,dehergne,684,"Sur l'art chinois: Sepp Schûller, P. M. Ricci ..."
deh-matteo-ricci,0,dehergne,684,"— Délia Entrata delta Comp. nella Cina, avec a..."
deh-matteo-ricci,0,dehergne,684,"pécimen d'écriture, nom chinois et romanisatio..."
deh-matteo-ricci,0,jesuita-estatuto,Padre,None
deh-matteo-ricci,0,nacionalidade,Itália,None
deh-matteo-ricci,0,nome-chines,Li Ma-teou,None
deh-matteo-ricci,0,nome-chines,Si-T'ai,None
deh-matteo-ricci,0,tarefa,Calendário cristão na China,None
deh-matteo-ricci,15521006,nascimento,Macerata,None
deh-matteo-ricci,15521006,nascimento@,https://www.wikidata.org/wiki/Q13135,None
deh-matteo-ricci,15710816,jesuita-entrada,Roma (Noviciado de Sant'Andrea al Quirinale),None
deh-matteo-ricci,15710816,jesuita-entrada@,https://www.wikidata.org/wiki/Q220,None
deh-matteo-ricci,15780324,embarque,S. Luís,None
deh-matteo-ricci,15780324,wicky,200,None
deh-matteo-ricci,15780324,wicky-viagem,25,None
deh-matteo-ricci,15780913,chegada,Goa,None
deh-matteo-ricci,15780913,chegada@,https://www.wikidata.org/wiki/Q1171,None
deh-matteo-ricci,15800725,jesuita-ordenacao-padre,Cochim,None
deh-matteo-ricci,15800725,jesuita-ordenacao-padre@,https://www.wikidata.org/wiki/Q1800,None
deh-matteo-ricci,15800726,estadia,Cochim,None
deh-matteo-ricci,15800726,estadia@,https://www.wikidata.org/wiki/Q1800,None
deh-matteo-ricci,15800726,tarefa,Celebra a primeira missa,None
deh-matteo-ricci,15820807,chegada,Macau,None
deh-matteo-ricci,15820807,chegada@,https://www.wikidata.org/wiki/Q14773,None
deh-matteo-ricci,15830800,estadia,Cantão,None
deh-matteo-ricci,15830800,estadia@,https://www.wikidata.org/wiki/Q16572,None
deh-matteo-ricci,15830910,estadia,Shiuhing (Tchao-k'ing fou),None
deh-matteo-ricci,15830910,jesuita-tarefa,Funda uma residência em Shiuhing,None
deh-matteo-ricci,15891000,estadia,Shiuchow (Chao-tcheou),None
deh-matteo-ricci,15891000,jesuita-tarefa,Funda uma residência em Shiuchow,None
deh-matteo-ricci,15950521,estadia,Nanquim,None
deh-matteo-ricci,15950521,estadia@,https://www.wikidata.org/wiki/Q16666,None
deh-matteo-ricci,15950615,estadia,Nanquim,None
deh-matteo-ricci,15950615,estadia@,https://www.wikidata.org/wiki/Q16666,None
deh-matteo-ricci,15960101,jesuita-votos,4V,None
deh-matteo-ricci,15960101,jesuita-votos-local,Nan-tch'ang,None
deh-matteo-ricci,15960628,estadia,Nan-tch'ang fou,None
deh-matteo-ricci,15970800,jesuita-cargo,Superior da missão da China,None
deh-matteo-ricci,15980625,estadia,Nan-tch'ang fou,None
deh-matteo-ricci,15990705,estadia,Nanquim,None
deh-matteo-ricci,15990705,estadia@,https://www.wikidata.org/wiki/Q16666,None
deh-matteo-ricci,16000519,partida,Pequim,None
deh-matteo-ricci,16000519,partida@,https://www.wikidata.org/wiki/Q956,None
deh-matteo-ricci,16010000,jesuita-tarefa,Funda a missão do Hopei,None
deh-matteo-ricci,16010124,chegada,Pequim,None
deh-matteo-ricci,16010124,chegada@,https://www.wikidata.org/wiki/Q956,None
deh-matteo-ricci,16090000,estadia,Pequim,None
deh-matteo-ricci,16090000,estadia@,https://www.wikidata.org/wiki/Q956,None
deh-matteo-ricci,16090000,jesuita-tarefa,Congregação marial de Pequim,None
deh-matteo-ricci,16100511,jesuita-cargo,Superior da missão da China,None
deh-matteo-ricci,16100511,morte,Pequim,None
deh-matteo-ricci,16100511,morte@,https://www.wikidata.org/wiki/Q956,None

In [66]:
p = tlnb.db.get_person(id)
print(p.to_kleio())

n$Matteo Ricci/m/id=deh-matteo-ricci
  rel$function-in-act/n/dehergne-notices-r/0
  ls$nacionalidade/Itália/0
  ls$jesuita-estatuto/Padre/0
  ls$nome-chines/Li Ma-teou/0
  ls$nome-chines/Si-T'ai/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q13135"/15521006
  ls$nascimento/Macerata/15521006
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q220"/15710816
  ls$jesuita-entrada/Roma (Noviciado de Sant'Andrea al Quirinale)/15710816
  ls$embarque/S. Luís/15780324
  ls$wicky/200/15780324
  ls$wicky-viagem/25/15780324
  ls$chegada@/"https://www.wikidata.org/wiki/Q1171"/15780913
  ls$chegada/Goa/15780913
  ls$estadia@/"https://www.wikidata.org/wiki/Q1800"/15800726
  ls$estadia/Cochim/15800726
  ls$tarefa/Celebra a primeira missa/15800726
  ls$chegada@/"https://www.wikidata.org/wiki/Q14773"/15820807
  ls$chegada/Macau/15820807
  ls$estadia@/"https://www.wikidata.org/wiki/Q16572"/15830800
  ls$estadia/Cantão/15830800
  ls$estadia/Shiuhing (Tchao-k'ing fou)/15830910
  ls$jesuita-tarefa/Funda uma residência em Shiuhing/15830910
  ls$estadia/Shiuchow (Chao-tcheou)/15891000
  ls$jesuita-tarefa/Funda uma residência em Shiuchow/15891000
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/15950521
  ls$estadia/Nanquim/15950521
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/15950615
  ls$estadia/Nanquim/15950615
  ls$estadia/Nan-tch'ang fou/15960628
  ls$jesuita-cargo/Superior da missão da China/15970800
  ls$estadia/Nan-tch'ang fou/15980625
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/15990705
  ls$estadia/Nanquim/15990705
  ls$partida@/"https://www.wikidata.org/wiki/Q956"/16000519
  ls$partida/Pequim/16000519
  ls$chegada@/"https://www.wikidata.org/wiki/Q956"/16010124
  ls$chegada/Pequim/16010124
  ls$jesuita-tarefa/Funda a missão do Hopei/16010000
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/16090000
  ls$estadia/Pequim/16090000
  ls$jesuita-tarefa/Congregação marial de Pequim/16090000
  ls$tarefa/Calendário cristão na China/0
  ls$jesuita-cargo/Superior da missão da China/16100511
  ls$jesuita-ordenacao-padre@/"https://www.wikidata.org/wiki/Q1800"/15800725
  ls$jesuita-ordenacao-padre/Cochim/15800725
  ls$jesuita-votos/4V/15960101
  ls$jesuita-votos-local/Nan-tch'ang/15960101
  ls$morte@/"https://www.wikidata.org/wiki/Q956"/16100511
  ls$morte/Pequim/16100511
  ls$dehergne/684/0/obs="""
      Ricci, Matteo (ital.) P. 684 Li Ma-teou, Si-T'al (Pf.., et non Ki-Jen, RBS 218)., en portugais Richo (DI. XI, 155, n. 19). N. 6 oct. 1552, Macerata, dans la Marche d'Ancône. E. noviciat St André du Quirinal, Rome, 16 août 1571 (Rom. 171A, 16: il signe: Matteo Riccio). Emb. sur le S. Luis, 24 mars 1578 (W 200)., arr. Goa, 13 sept., et Macao, 7 août 1582., août 1583, Canton., 10 sept. 1583, Shiuhing (Tchao-k'ing fou), où il fonde une résidence., oct. 1589, résidence à Shiuchow (Chao-tcheou)., du 21 mai 1595 au 15 juin, Nankin., 28 juin 1596 au 25 juin 1598, Nan-tch'ang fou., 5 juill. 1599, Nankin., 19 mai 1600, départ pour Pékin où il arr. le 24 janv. 1601, et où il fonde la mission du Hopei, 1601., Supérieur de la mission de Chine, d'août 1597 à sa mort., 1609, congrégation mariale. Pékin., calendrier chrétien en Chine (Pf. 117).
  """
  ls$dehergne/684/0/obs="""
      P. 25 juill. 1580, à Cochin, où il célèbre sa première messe le 26 juill. (D'Elia III, 22). V. Nan-tch'ang 1er janv. 1596 (D'Elia I, 374 et II, 4) pr. « Nanciani » ... Riccius (Lus. 2, 128). M. 11 mai 1610, Pékin (JS 113, 120-146., Planchet p. 222). Fils de Giovanni Battista Ricci, pharmacien, et de Giovanna Angiolelli, famille noble, marquis de Castelvecchio (D'Elia I, cii et II, 550). HS 43, 58 le fait mourir d'abord en 1609, puis le 11 mai 1610. Portrait: Pf. 31., D'Elia I, p. vi., ARSI Rom. 185, f° 97-98., BN: Estampes, Ne 100., en couleurs dans Bortone, P. Fernando,- Gesuiti alla corte di Pechino, 1969, pl. II p. 1., cf. Hamy. Pf. 22., Koch., NCE (F. A. Rouleau)., EC (Cel. Testore)., EB (J.S. Sebes)., CE (J. Brucker)., El (Tacchi Venturi). Bibliographie: SiRErr IV, p. 525-528., XII, p. 275-283., XIV. 1. p. 778.,
  """
  ls$dehergne/684/0/obs="""
      D'Elu III, 239-243. Biographie: en chinois: BN: Courant 9 (anonyme), 1014-1016 I, par Aleni, 1321 (par Pantoja, de Ursis)., et 6832 I, poème sur Rica. BernardE-MaÎtre], H., Le P. Matthieu Ricci et la société chinoise de son temps (1552-1610), Tientsin, 1937, 2 vol.., trad. chinoise par Wang Tch'ang-Tche, J., 1943., du même, Iles Philippines, 213-218 (sur la pensée de Ricci)., Cronin, Vincent, The Wise Man front the West, Londres, 1955., Dunne, G. H., Génération of Giants, 1962, p. 23-108., trad. franç. Chinois avec les Chinois, te P. Ricci et ses compagnons, Paris, 1964., Bortone, Fernando, P. Matteo Ricci, SJ.: Il « Saggio d'Occidente », 2' éd., 1965., trad. franç. en préparation. Le ms de Pires, Francisco, montre qu'il a failli être envoyé au Japon.Son oeuvre: Nocentini, Lod., --primo Sinologo, P.M.R., Florence, 1882.,
  """
  ls$dehergne/684/0/obs="""
      Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,. Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1., Son oeuvre: Nocentini, Lod., -- primo Sinologo, P.M.R., Florence, 1882., Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,- Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1.,
  """
  ls$dehergne/684/0/obs="""
      id.. L'apport scientifique du P. M. R à la Chine, Tientsin, 1935, dont trad. anglaise par Chalmers Werner, Edw., Pékin, 1935., id., L'attitude du P. M. R. en face des coutumes et rites chinois, RSRel. 28 (1938), 31-47., id., Les étapes de la cartographie scientifique pour ta Chine et tes pays voisins, MS I (1936), 428-477., Brou, A., Les tâtonnements du P. M. R., RHM 15 (1938), 228-244., Szczesniak, B., The Seventeenth Maps of China, Imago Mundi 17 (1956), 116-136, 9 cartes., id., Matteo Ricci's Maps of China, ibid , 11 (1954), 127-134., cf Giles, L., Geographicat Journal 52 (1918), 367-385 et 53 (1919), 19-30., Wallis, Helen, The Influence of Father R. on Far Eastern Cartography, Imago Mundi 19 (1965), 38-45, 5 cartes., Harris, George L., The Mission of M. R. A case study of an effort at guided culture change in the Sixteenth Century, MS 25 (1968), 1-168.,
  """
  ls$dehergne/684/0/obs="""
      Bettray, Johannes, S.V.D., Die akkomodationmethode des P. M. R., S.J., in China, Analecta Gregoriana, nº 76, Rome, 411 p.., Rule, Paul A., Jestât and Confucian? Chinese Religion in the journal of M.R, Journal of Religious History (Sidney, 1969), 105-124., D'Elia, P. M., Récent discoveries and New Studies (1938-1960) on the World Map in Chinese of F. M.R., SJ., MS XX (1961), 82-164., Danibl-Rops, Histoire de t'Eglise du Christ VI (Paris, 1966), 272-276, Le Christ entre au « Cathay » avec « Li Mateou »., Schutte, 996., DI. XII, 1031. Et nombre d'études sur des points spéciaux., par exemple, sur la Congré- gation mariale de Pékin: Du Manoir, Hubert, Maria t. IV, 968-972., NZM 1962, 255 citant Margiotti...
  """
  ls$dehergne/684/0/obs="""
      Sur l'art chinois: Sepp Schûller, P. M. Ricci und die christliche Kunst, Die Kath. Miss. LXIV (Diisseldorf, 1936), 3-8., H. Bernard [Maître], L'Art chré- tien en Chine au temps du P. M. R., RHM 12 (1935), 199-229., D'Elia, Le origini delt'arte cristiana cinese, Rome 1939. Sur l'influence au Japon des cartes de Ricci, Aleni et Verbiest, l'art, de Shintarô Ayusawa, MNipp. 19 (1964), 45-49. Sur le Ki-jen che p'ien, RBS 228 et 399. Principaux autographes de RICCI: — Son catéchisme, B. Casanatense ms 2136 G. I 1, daté de 1603, cf. JS 195.
  """
  ls$dehergne/684/0/obs="""
      — Délia Entrata delta Comp. nella Cina, avec additions de N. Trigault, JS 106a. Cf D'Elia. Une édition nouvelle, avec un important appareil documentaire et critique est en préparation à l'Université de Paris VII (Bulletin de Liaison, Ecole Pratique des Hautes Etudes, VI* section, 54 bd Raspail, 75006 Paris, vol. V (1972) p. 42. — La Carte de Chine, 28 sept. 1584, reproduite dans Colin, Francisco & Pastells, Pablo, Labor Evangelica .... Barcelone, 1902, III, planche, p. 448 (Arch. d. Ind., 145-7-7). Sa carte du Monde, supra. Gaibandi, Pietro, -- P. M.R e ta geografia délia Cina, Rivista di fisica, matematica e scienze naturali, Padua, VIII, 1903, 321-355, 459-464.
  """
  ls$dehergne/684/0/obs="""
      pécimen d'écriture, nom chinois et romanisation, Allan, pl. p. 49 (noter le -RI de Ricci, écrit à la fois RI et LI. Copie de la lettre du P. « Matheo Risi y Saliano » (1584) à Juan Bautista RomAn, facteur des îles Philippines à Macao, dans Carlos Sanz, Primitivas Relaciones de Espana con Asia y Oceania, Madrid, 1958, 372-384 (Archivos de Indias 67-6-29) et l'art, de Léon Lopetegui, Miss. Hisp. I, 1944, 341-352., Razén y Fe IV, 1902, 463477.
  """
  pai$Giovanni Battista Ricci/m/id=deh-matteo-ricci-pai
    rel$function-in-act/pai/dehergne-notices-r/0
    ls$profissao/Boticário/0
    ls$ec/c/15880000
  mae$Giovanna Angiolelli/f/id=deh-matteo-ricci-mae/obs=Dehergne menciona família nobre, marqueses de Castelvecchio, mas não diz de que lado
    rel$function-in-act/mae/dehergne-notices-r/0
    ls$ec/c/15880000

#### Atributos de uma pessoa numa tabela, attributos em colunas

---

#### Person attributes in a dataframe, attributes in columns

In [55]:
# Get list of people with with a certain value in a specific attribute

id = 'deh-matteo-ricci'  # matheo ricci
# id = 'deh-antonio-de-magalhaes-ref1'  # Alexandre Metelo de Sousa
df = entities_with_attribute(
                    entity_type='person',
                    the_type='estadia',  # we need a base attribute
                    the_value='Pequim',
                    more_info=['name'],
                    more_cols=['jesuita-entrada','jesuita-estatuto','morte'],
                    dates_in=('1580','1610'),
                    db=tlnb.db,
                    sql_echo=False)
view_cols = ['name','estadia','estadia.date','morte.date','jesuita-entrada','jesuita-entrada.date']
df.info()
df[view_cols].sort_values('estadia.date')

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, deh-antonio-leitao to deh-sebastien-fernandes-tchong-ref2
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   13 non-null     object
 1   estadia                13 non-null     object
 2   estadia.date           13 non-null     object
 3   estadia.obs            0 non-null      object
 4   jesuita-entrada        11 non-null     object
 5   jesuita-entrada.date   11 non-null     object
 6   jesuita-entrada.obs    0 non-null      object
 7   jesuita-estatuto       11 non-null     object
 8   jesuita-estatuto.date  11 non-null     object
 9   jesuita-estatuto.obs   0 non-null      object
 10  morte                  10 non-null     object
 11  morte.date             10 non-null     object
 12  morte.obs              0 non-null      object
dtypes: object(13)
memory usage: 1.4+ KB

,name,estadia,estadia.date,morte.date,jesuita-entrada,jesuita-entrada.date
id,,,,,,
deh-lazzaro-cattaneo,Lazzaro Cattaneo,Pequim,15980907,16400119,Roma (Noviciado de Sant'Andrea al Quirinale),15810227
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,15980907,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-sebastien-fernandes-tchong-ref2,Matteo Ricci,Pequim,15980907,NaN,NaN,NaN
deh-lazzaro-cattaneo,Lazzaro Cattaneo,Pequim,15981105,16400119,Roma (Noviciado de Sant'Andrea al Quirinale),15810227
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,15981105,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-sebastien-fernandes-tchong-ref2,Matteo Ricci,Pequim,15981105,NaN,NaN,NaN
deh-jacques-niva-ni,Jacques Niva Ni,Pequim,16020700,16381026,Nan-tch'ang,16080000
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,16020920,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-antonio-leitao,António Leitão,Pequim,16030000,16111010,?,16030000
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,16040000,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-jean-fernandes-tchong,Jean Fernandes Tchong,Pequim,16071029,NaN,Nanquim,16080300
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,16080000,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-matteo-ricci,Matteo Ricci,Pequim,16090000,16100511,Roma (Noviciado de Sant'Andrea al Quirinale),15710816

#### Examinar potenciais duplicados

---

#### Examine potentital duplicates

In [71]:
from timelink.pandas.group_attributes import display_group_attributes
pd.set_option('display.max_rows',250)

no_show=['dehergne']

dup_ids = ricci.index.unique()  #

display_group_attributes(dup_ids,
                             header_cols=['estadia'],
                             exclude_attributes=no_show,
                             sort_attributes=['date','type','value'],
                             cmap_name='Pastel1')

ImportError: cannot import name 'display_group_attributes' from 'timelink.pandas' (/Users/jrc/mhk-home/sources/dehergne-locations/.venv/lib/python3.10/site-packages/timelink/pandas/__init__.py)