# Database overview notebook

> First time use: follow instructions in the README.md file in this directory.

In [1]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook()
tlnb.print_info()

WARNING:root:Reusing existing container zen_elion

Timelink version: 1.1.26
Project name: dehergne
Project home: /Users/jrc/mhk-home/sources/dehergne
Database type: sqlite
Database name: dehergne
Kleio image: timelinkserver/kleio-server
Kleio server token: EtS0x...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/mhk-home/sources/dehergne
Kleio server container: zen_elion
Kleio version requested: latest
Kleio server version: 12.9.588 (2025-06-06 16:04:22)
SQLite directory: /Users/jrc/mhk-home/sources/dehergne/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne, project_home=/Users/jrc/mhk-home/sources/dehergne, db_type=sqlite, db_name=dehergne, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

## Ligar à base de dados

---

## Connect to database

In [2]:
from timelink.api.database import TimelinkDatabase

db: TimelinkDatabase = tlnb.db

## Database status

In [3]:
tlnb.table_row_count_df()

               table  count
0               acts     28
1    alembic_version      1
2         aregisters      0
3         attributes  26820
4             blinks     96
5   class_attributes     58
6            classes     10
7           entities  32973
8        geoentities    359
9         kleiofiles     38
10             links    114
11           objects      0
12           persons   2132
13         relations   3547
14         rentities     48
15           sources     29
16            syslog      0
17            syspar      0

## Recent sources

In [4]:
number_of_sources = 100

Source = db.get_model('source')

with db.session() as session:
    sources = session.query(Source).order_by(Source.updated.desc()).all()
    for source in sources[:number_of_sources]:
        print(f"{source.id:32} {source.updated:%Y-%m-%d %H:%M:%S} {source.kleiofile}")

dehergne-r                       2025-12-25 17:22:03 /kleio-home/sources/dehergne-r.cli
dehergne-j                       2025-12-25 17:20:27 /kleio-home/sources/dehergne-j.cli
dehergne-z                       2025-12-25 17:14:51 /kleio-home/sources/dehergne-repertoire/sources/dehergne-z.cli
dehergne-v                       2025-12-25 17:14:42 /kleio-home/sources/dehergne-repertoire/sources/dehergne-v.cli
dehergne-t                       2025-12-25 17:14:32 /kleio-home/sources/dehergne-repertoire/sources/dehergne-t.cli
dehergne-p                       2025-12-25 17:14:21 /kleio-home/sources/dehergne-repertoire/sources/dehergne-p.cli
dehergne-n                       2025-12-25 17:14:13 /kleio-home/sources/dehergne-repertoire/sources/dehergne-n.cli
dehergne-l                       2025-12-25 17:14:01 /kleio-home/sources/dehergne-l.cli
dehergne-k                       2025-12-25 17:13:55 /kleio-home/sources/dehergne-repertoire/sources/dehergne-k.cli
dehergne-g                       2025-12-25 17:13:44 /kleio-home/sources/dehergne-repertoire/sources/dehergne-g.cli
dehergne-f                       2025-12-25 17:13:32 /kleio-home/sources/dehergne-repertoire/sources/dehergne-f.cli
dehergne-d                       2025-12-25 17:13:21 /kleio-home/sources/dehergne-repertoire/sources/dehergne-d.cli
dehergne-b                       2025-12-25 17:13:10 /kleio-home/sources/dehergne-b.cli
dehergne-a                       2025-12-25 17:12:59 /kleio-home/sources/dehergne-a.cli
dehergne-s                       2025-12-04 08:49:09 /kleio-home/sources/dehergne-s.cli
dehergne-m                       2025-09-12 13:31:11 /kleio-home/sources/dehergne-m.cli
dehergne-c                       2025-09-12 13:30:59 /kleio-home/sources/dehergne-c.cli
dehergne-h                       2025-07-10 09:14:03 /kleio-home/sources/dehergne-h.cli
dehergne-e                       2025-07-10 09:13:52 /kleio-home/sources/dehergne-e.cli
dehergne-y                       2025-07-10 08:56:42 /kleio-home/sources/dehergne-y.cli
dehergne-x                       2025-07-10 08:56:39 /kleio-home/sources/dehergne-x.cli
dehergne-w                       2025-07-10 08:56:37 /kleio-home/sources/dehergne-w.cli
dehergne-u                       2025-07-10 08:56:26 /kleio-home/sources/dehergne-u.cli
dehergne-q                       2025-07-10 08:55:38 /kleio-home/sources/dehergne-q.cli
dehergne-o                       2025-07-10 08:55:20 /kleio-home/sources/dehergne-o.cli
dehergne-locations-1701          2025-07-10 08:54:46 /kleio-home/sources/dehergne-locations-1701.cli
dehergne-locations-1644          2025-07-10 08:54:37 /kleio-home/sources/dehergne-locations-1644.cli
dehergne-i                       2025-07-10 08:54:00 /kleio-home/sources/dehergne-i.cli
dehergne-0-abrev                 2025-07-10 08:51:45 /kleio-home/sources/dehergne-0-abrev.cli

### Tipos de attributos

---

### Attribute types

In [5]:
import pandas as pd

from sqlalchemy import func
from sqlalchemy import select


pd.set_option('display.max_rows', 500)

attr_table = tlnb.db.get_table('attributes')
tlnb.db.describe('attributes', show=True)
print()
stmt = select(
    attr_table.c.the_type,
    func.count().label('count'),
    func.count(func.distinct(attr_table.c.the_value)).label('distinct_value')
    ).group_by('the_type')
print(stmt)
print()

with tlnb.db.session() as session:
    # nml2 = session.query(Attribute.the_type,func.count().label('tot')).group_by(Attribute.the_type).all()
    nml = session.execute(stmt)
    attribute_df = pd.DataFrame(nml)

attribute_df

attributes (model_table)
id                   entities             VARCHAR
class                entities             VARCHAR
inside               entities             VARCHAR    {ForeignKey('entities.id')}
the_source           entities             VARCHAR
the_order            entities             INTEGER
the_level            entities             INTEGER
the_line             entities             INTEGER
groupname            entities             VARCHAR
extra_info           entities             JSON
updated              entities             DATETIME
indexed              entities             DATETIME
id                   attributes           VARCHAR    {ForeignKey('entities.id')}
entity               attributes           VARCHAR    {ForeignKey('entities.id')}
the_type             attributes           VARCHAR
the_value            attributes           VARCHAR
the_date             attributes           VARCHAR
obs                  attributes           VARCHAR

SELECT attributes.the_type, count(*) AS count, count(distinct(attributes.the_value)) AS distinct_value
FROM attributes GROUP BY attributes.the_type

                            the_type  count  distinct_value
0                             activa    286               3
1                   alternative-name      4               4
2          alternative-name@wikidata      3               3
3                          baptizado     28              28
4                 baptizado@wikidata     26              26
5                       bibliografia      9               9
6                              cargo    356             225
7                            chegada    487              71
8                   chegada@wikidata    422              63
9                           dehergne   1454            1211
10                  dehergne@archive      4               4
11                dehergne@bdconline      1               1
12                                ec    210               1
13                          embarque    781              92
14                 embarque@wikidata      3               2
15                           estadia   3633             687
16                         estadia-x     17               8
17                estadia-x@wikidata     17               8
18                  estadia@wikidata   3591             383
19                          estatuto     17              11
20           geoentity:name@dehergne      4               4
21           geoentity:name@geonames      1               1
22           geoentity:name@wikidata    313             237
23                    grau-academico     63               7
24                  grau-academico-x      1               1
25     historical-source:id@dehergne      1               1
26                             idade     20              11
27                     jesuita-cargo    877             236
28                   jesuita-entrada    962              67
29          jesuita-entrada@wikidata    478              66
30    jesuita-entradaLisboa, Arroios      1               1
31                  jesuita-estatuto   1327              16
32                  jesuita-fundador      3               1
33         jesuita-fundador@wikidata      3               2
34           jesuita-ordenacao-padre    419              48
35  jesuita-ordenacao-padre@wikidata    125              47
36                    jesuita-tarefa    361             251
37                  jesuita-tarefa-x      6               6
38                     jesuita-votos    613              14
39               jesuita-votos-local    516             256
40      jesuita-votos-local@wikidata    478             155
41                             morte    886             295
42                    morte@wikidata    704             189
43                     nacionalidade   1120              30
44            nacionalidade@wikidata     10               3
45                        nascimento   1012             577
46               nascimento@wikidata    902             499
47                              nome    990             975
48                       nome-chines    711             667
49                      nome-japones      2               2
50                              nota     10               7
51                     nota@wikidata      1               1
52                              note      1               1
53                           partida    249              54
54                         partida-x      3               3
55                partida-x@wikidata      2               2
56                  partida@wikidata    248              46
57                         profissao    261              62
58                        pseudonimo     10              10
59                        residencia     28              20
60                 residencia-missao    105              10
61                 residencia-missão      8               4
62               residencia@wikidata     25              17
63                        residência      3               1
64               residência@wikidata      3               1
65                            tarefa    212             145
66                            titulo    253              70
67                              todo      2               2
68                           trajeto      1               1
69                  trajeto@wikidata      1               1
70                             wicky    554             549
71                      wicky-viagem    582             136

## Vocabulary of attributes

In [6]:
from timelink.pandas import attribute_values

df_totals = attribute_values('jesuita-fundador',db=tlnb.db)
df_totals

       count  date_min  date_max
value
Paris      3  15340815  15340815

## Mostrar uma fonte

---

## Show a source

In [7]:
id = 'dehergne-locations-1644'
with db.session() as session:
    source = session.get(Source,id)
    print(source.to_kleio())

fonte$dehergne-locations-1644/0/type=geoinformation/ref=None/loc=None/kleiofile="/kleio-home/sources/dehergne-locations-1644.cli""/replaces=None/obs="""
      Planche: Carte des Chrétientés Chinoises de la fin des Ming (1644).p. 353

      _Diocèse_
      Depuis 1514, l'évêché de Funchal (île de Madère)
      s'étend jusqu'aux extrémi-
      tés de l'Asie. Depuis le 3 nov. 1534 est
      créé l'évêché de Goa, dont est déta-
      ché, le 23 janv. 1576, le diocèse de
      Macao, qui sera amputé, 14 février
      1588, du Japon (évêché de Funai):
      l'évêché de Macao comprend théori-
      quement tout l'empire de Chine.

      _Provinces Jésuites_

      la vice-province du Japon (province en
      1611); en 1623, la vice-province de Chine
      indépendante du Japon en est déta-
      chée; mais un visiteur jésuite contrôle
      l'une et l'autre.

      La Chine impériale distingue dans chaque province civile les _fou_, préfec-
      tures ou villes de premier ordre, dont dépendent les _tcheou_ et les _hien_. D'au-
      tres agglomérations importantes comme Tientsin (alors wei) ou encore Amoy
      et Fatshan n'ont pas reçu le titre de hien. Dans notre tableau, les villes autres
      que les fou sont mises en italiques, et la capitale de chaque province, en
      majuscule. Sur la carte, nous mettons en lettres majuscules les seuls fou et
      tcheou possédant une chrétienté (pour les tcheou, majuscules penchées); les
      hien, en lettres ordinaires, et nous n'inscrivons (en petites lettres) que les
      bourgs et demeures chrétiennes antérieures à la persécution de 1615.
         Pour les jésuites de l'époque, le mot collège désigne une résidence prin-
      cipale d'où dépendent (d'un point de vue économique beaucoup plus que juri-
      dique), un certain nombre de petites résidences qui lui sont rattachées. La
      carte, qui accompagne ces pages comme celle des résidences en 1701, est due au
      Père Pierre Moreau, SJ., et nous lui exprimons ici nos remerciements.
         Une résidence est une maison propriété de la mission: elle est soit occupée
      par un ou plusieurs missionnaire (ici: R) ou cette anné-là, sans prêtre
      à demeure (R'); tandis que le mot église s'applique à une chapelle, un oratoire
      ou un temple plus important ; d'autres fois, le prêtre dit la messe chez des fidè-
      les, dans leur propre maison. Toute résidence possède une église ou oratoire.
      Sur la carte, les Résidences sont marquées par un cercle. Résidences et chré-
      tientés sont, à l'époque, presque toutes aux Jésuites. Dans le cas contraire,
      nous faisons suivre le nom de la localité de la mention de l'Ordre qui les pos-
      sède: (OP), Dominicains; (OFM), Franciscains; (OESA), Augustins.
         On observera que le cours du Fleuve Jaune n'était pas le même qu'actuel-
      lement, et que les chrétientés se sont développées le long des grandes routes
      (le fait est frappant pour la région du Kiangnan). Pour les chrétientés an-
      ciennes des Ming voir aussi MS XVI, 1957 (avec carte en couleurs).

      N.B. N.B. Pour compléter ce tableau des antiquités chrétiennes de la Chine, rap-
      pelons qu'en Mongolie à Olon-Sume, ancienne capitale des Ongiit nestoriens,
      il y eut, outre une église nestorienne, une église catholique de Giovanni de Mon-
      tecorvino (1247-1328) « le plus ancien exemple de sanctuaire catholique en Ex-
      trême-Orient » Egami, Namio dans Journal Asiatique, CCXL 1952, 155-167 cf NZM
      1954, p. 56); du même, Découverte 'l'église romaine' établie au XIII' siècle
      en Mongolie, Conferenze, Rome, 1955, 41-55; cf BernahdC-Maitrb], Henri, La dé-
      couverte des Nestoriens Mongols aux Ordos et l'Histoire ancienne du Christia-
      nisme en Extrême-Orient, Tientsin, 1935. — Les ruines de l'église franciscaine
      de Nankin au XIV* siècle ont été décrites par Prip-Molleb dans la revue
      danoise Artes; résumé dans Chinese Recorder, 1935, 654-656 et hors-texte 641.
      Etc.

      NOTA TRANSCRIÇÃO

      "geo1$ = Provincia"
      "geo2$ = fou (perfeitura ou cidade de 1ª ordem)"
      "geo3$ = tcheou-hien"

      Em cada entrada o formato é

         "geoN$Nome geográfico/Tipo (província, fou, tcheou-hien)/id=deh-r1644-nome"

      Exº
         "geo1$Chekiang#Zhejiang/província/deh-r1644-chekiang"
         "geo2$Hangchou#Hangzhou/capital provincial/deh-r1644-hangzhou"
         "geo3$Fuyang/tcheou-hien/deh-r1644-fuyang"

      Nos locais onde há presença de missionários:

         "atr$residencia-missao/Jesuíta/1611 (onde aparece R)"
         "atr$residencia-missao/Dominicanos%OP/1656"
                        (quando passa a residência de outra ordem
                         ver abreviaturas na legenda do mapa, exº p.354 em Kinhua)
         "atr$activa/sim/1611"         (onde só aparece uma data)

      edited by Skye
      and Joaquim Carvalho
      and Alicia
      """
  atr$historical-source:id@dehergne/"https://archive.org/details/bhsi37/page/n396/mode/1up"#@dehergne:396%396/
  geodesc$deh-chre-1644/16440000/type=geodesc/ref=None/loc=None
    geo1$Chekiang#Tche-kiang, today Zhejiang, 浙江, @wikidata:Q16967 @dehergne:396/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q16967"#Tche-kiang, today Zhejiang, 浙江, @wikidata:Q16967 @dehergne:396%Q16967/1644
      atr$geoentity:name@dehergne/"https://archive.org/details/bhsi37/page/n396/mode/1up"#Tche-kiang, today Zhejiang, 浙江, @wikidata:Q16967 @dehergne:396%396/1644
    geo1$Fukien#Fou-kien, today Fujian, 福建, @wikidata:Q41705 @dehergne:397/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q41705"#Fou-kien, today Fujian, 福建, @wikidata:Q41705 @dehergne:397%Q41705/1644
      atr$geoentity:name@dehergne/"https://archive.org/details/bhsi37/page/n397/mode/1up"#Fou-kien, today Fujian, 福建, @wikidata:Q41705 @dehergne:397%397/1644
    geo1$Honan#today Henan, 河南, @wikidata:Q43684/geo1/obs=(12 ou 13 chrétientés en 1641)
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q43684"#today Henan, 河南, @wikidata:Q43684%Q43684/1644
    geo1$Hukwang#"""Huguang?, Hou-Quang, today Huguang,湖广, @wikidata:Q2235155, for coordinates we use Wuchang District wikidata:Q1014420 (coordinates:30°33'23"N, 114°18'38"E), where the head quarters of vice-roy of Huguang (wikidata:Q11563236) were located."""/geo1/obs=Former province of China, corresponding to modern-day Hubei and Hunan provinces
      <rel$geografica/pertence região/Hukwang/deh-r1644-hukwang/1644
      <rel$geografica/pertence região/Hunan/deh-r1644-hunan/1644
      <rel$geografica/pertence região/Hukwang/deh-r1644-hukwang/1644
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q2235155"#"""Huguang?, Hou-Quang, today Huguang,湖广, @wikidata:Q2235155, for coordinates we use Wuchang District wikidata:Q1014420 (coordinates:30°33'23"N, 114°18'38"E), where the head quarters of vice-roy of Huguang (wikidata:Q11563236) were located."""%Q2235155/1644
      atr$alternative-name@wikidata/"https://www.wikidata.org/wiki/Q46862"%Houpeh/1644
      atr$alternative-name/Houpeh#Hou-pe, today Hubei,湖北， @wikidata:Q46862/1644
    geo1$Hunan#Hou-nan, today Hunan, 湖南, @wikidata:Q45761/geo1
      rel$geografica/pertence região/Hukwang/deh-r1644-hunan/1644
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q45761"#Hou-nan, today Hunan, 湖南, @wikidata:Q45761%Q45761/1644
    geo1$Kiangnan#"""Jiangnan?today Jiangnan, 江南, @wikidata:Q11133842 (no coordinates), former province of China, corresponding to modern-day Jiangsu and Anhui provinces, coordinates:32°3'39"N, 118°46'44"E (Nankjing)"""%KIANGNAN ou NANKING/geo1/obs="""No Repertoire, na lista de 1641, os locais aparecem separados por províncas atuais (Anhwei e Kiangsu), mas na lista de 1701, eles aparecem juntos como região Kiangnan. In the Repertoire, in the list of 1641, the places are separated by current provinces (Anhui and Jiangsu), but in the list of 1701, they appear together as the Kiangnan(Jiangnan 江南) region.
              """
      <rel$geografica/pertence região/Anhwei/deh-r1644-anhwei/1644
      <rel$geografica/pertence região/Kiangsu/deh-r1644-kiangsu/1644
      rel$geografica/atualmente parte de/Anhwei/deh-r1644-kiangnan/1644
      rel$geografica/atualmente parte de/Kiangsu/deh-r1644-kiangnan/1644
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q11133842"#"""Jiangnan?today Jiangnan, 江南, @wikidata:Q11133842 (no coordinates), former province of China, corresponding to modern-day Jiangsu and Anhui provinces, coordinates:32°3'39"N, 118°46'44"E (Nankjing)"""%Q11133842/1644
    geo1$Anhwei#Anhui, Ngon-hoei, today Anhui, 安徽, @wikidata:Q40956/geo1
      <rel$geografica/atualmente parte de/Kiangnan/deh-r1644-kiangnan/1644
      rel$geografica/pertence região/Kiangnan/deh-r1644-anhwei/1644
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q40956"#Anhui, Ngon-hoei, today Anhui, 安徽, @wikidata:Q40956%Q40956/1644
    geo1$Kiangsu#Jiangju, today Jiangsu, 江苏, @wikidata:Q16963/geo1
      <rel$geografica/atualmente parte de/Kiangnan/deh-r1644-kiangnan/1644
      rel$geografica/pertence região/Kiangnan/deh-r1644-kiangsu/1644
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q16963"#Jiangju, today Jiangsu, 江苏, @wikidata:Q16963%Q16963/1644
    geo1$Kiangsi#Jiangxi, Kiang-si, today Jiangxi, 江西, @wikidata:Q57052/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q57052"#Jiangxi, Kiang-si, today Jiangxi, 江西, @wikidata:Q57052%Q57052/1644
    geo1$Kwangsi#Guangxi, Koang-si, today Guangxi, 广西, @wikidata:Q15176/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q15176"#Guangxi, Koang-si, today Guangxi, 广西, @wikidata:Q15176%Q15176/1644
    geo1$Kwangtung#Guangdong, today Guangdong, 广东, @wikidata:Q15175/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q15175"#Guangdong, today Guangdong, 广东, @wikidata:Q15175%Q15175/1644
    geo1$Kwichow#Koei-Tcheou, today Guizhou, 贵州, @wikidata:Q47097/geo1/obs=nada
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q47097"#Koei-Tcheou, today Guizhou, 贵州, @wikidata:Q47097%Q47097/1644
    geo1$Pequim#@wikidata:Q956/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q956"#@wikidata:Q956%Q956/1644
    geo1$Shansi#Chan-si, today Shanxi, 山西, @wikidata:Q46913/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q46913"#Chan-si, today Shanxi, 山西, @wikidata:Q46913%Q46913/1644
    geo1$Shangtung#Chan-tong, Shandong, 山东, @wikidata:Q43407/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q43407"#Chan-tong, Shandong, 山东, @wikidata:Q43407%Q43407/1644
    geo1$Shensi#Chen-si @wikidata:Q47974, today Shaanxi @dehergne:399/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q47974"#Chen-si @wikidata:Q47974, today Shaanxi @dehergne:399%Q47974/1644
      atr$geoentity:name@dehergne/"https://archive.org/details/bhsi37/page/n399/mode/1up"#Chen-si @wikidata:Q47974, today Shaanxi @dehergne:399%399/1644
    geo1$Szechwan#Se-tch'oan, today Sichuan, 四川, @wikidata:Q19770/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q19770"#Se-tch'oan, today Sichuan, 四川, @wikidata:Q19770%Q19770/1644
    geo1$Yunnan#today Yunnan, 云南, @wikidata:Q43194/geo1
      atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q43194"#today Yunnan, 云南, @wikidata:Q43194%Q43194/1644
      atr$activa/sim/<1638#antes desta data havia lá cristãos

## Obter modelos para acesso aos dados

---

## Obtain models for data access

In [8]:
db.get_models_ids()

['entity',
 'attribute',
 'relation',
 'act',
 'source',
 'aregister',
 'person',
 'object',
 'geoentity',
 'rentity',
 'class']

In [9]:
Model = db.get_model('geoentity')

with db.session() as session:
    entities = session.query(Model).all()
    for entity in entities[:10]:
        print(entity.to_kleio())
        print()

geo1$Chekiang#Tche-kiang, today Zhejiang, 浙江, @wikidata:Q16967 @dehergne:396/geo1
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q16967"#Tche-kiang, today Zhejiang, 浙江, @wikidata:Q16967 @dehergne:396%Q16967/1644
  atr$geoentity:name@dehergne/"https://archive.org/details/bhsi37/page/n396/mode/1up"#Tche-kiang, today Zhejiang, 浙江, @wikidata:Q16967 @dehergne:396%396/1644

geo2$Hangchou#Hang-tcheou, today Hangzhou, 杭州, @wikidata:Q4970/geo2
  atr$activa/sim/1611
  atr$residencia-missao/Jesuíta/1611
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q4970"#Hang-tcheou, today Hangzhou, 杭州, @wikidata:Q4970%Q4970/1644

geo3$Fuyang#Fou-yang, today Fuyang, 富阳, @wikidata:Q1011103/geo3
  atr$activa/sim/1642
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q1011103"#Fou-yang, today Fuyang, 富阳, @wikidata:Q1011103%Q1011103/1644

geo3$Jenho#Jen-houo, today Renhe, 仁和县 (@wikidata:Q9385136), Historical county name, coordinates: 30.448897N, 120.307504E/geo3/obs=no wikidata.
  atr$activa/sim/1608
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q9385136"#Jen-houo, today Renhe, 仁和县 (@wikidata:Q9385136), Historical county name, coordinates: 30.448897N, 120.307504E%Q9385136/1644

geo2$Chüchow#"""K'iu-tcheou, today Quzhou, 衢州, @wikidata:Q58235, in the Chinese translation it is recognized as “遂州”, which is wrong, both phonetically and geographically. In Dehergne(1957), it is noted as "衢州"."""/geo2/obs="""      in the Chinese translation it is recognized as “遂州”, which is wrong, both
  phonetically and geographically. In Dehergne(1957), it is noted as "衢州".
  """
  atr$activa/sim/1613
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q58235"#"""K'iu-tcheou, today Quzhou, 衢州, @wikidata:Q58235, in the Chinese translation it is recognized as “遂州”, which is wrong, both phonetically and geographically. In Dehergne(1957), it is noted as "衢州"."""%Q58235/1644

geo2$Huchow#Hou-tcheou, today Huzhou, 湖州, @wikidata:Q42664/geo2
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q42664"#Hou-tcheou, today Huzhou, 湖州, @wikidata:Q42664%Q42664/1644

geo3$Tehtsing%""""Tehtsing du Huchow, Té-ts'ingTeching# today Deqing, 德清, @wikidata:Q1191987""""/geo3
  atr$activa/sim/1620

geo2$Kashing#Kia-hing, today Jiaxing, 嘉兴, @wikidata:Q58178/geo2
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q58178"#Kia-hing, today Jiaxing, 嘉兴, @wikidata:Q58178%Q58178/1644

geo3$Kashan#Kia-chan, today Jiashan, 嘉善, @wikidata:Q1361347%Kaosham/geo3/obs="""
               The place name in the book Dehergne(1973) is "Kaoshan", and in the Chinese translation it is recognized as “高山”. But this place cannot be found. According to Dehergne(1957), it probably shoud be "Kashan 嘉善", which means in the 1973 book, this place is wrongly spelled by mistake."""
  atr$activa/sim/1640
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q1361347"#Kia-chan, today Jiashan, 嘉善, @wikidata:Q1361347%Q1361347/1644

geo3$Tangsi#""""T'ang-k'i Tangchi", today Tangqi, 塘栖 @wikidata:Q10931032, in the Chinese translation it is recognized as “塘拪”"""/geo3
  atr$activa/sim/1642
  atr$geoentity:name@wikidata/"https://www.wikidata.org/wiki/Q10931032"#"T'ang-k'i Tangchi", today Tangqi, 塘栖 @wikidata:Q10931032, in the Chinese translation it is recognized as “塘拪”%Q10931032/1644