# Dehergne repertoire analysis

> First time use: follow instructions in the [README.md](README.md) file in this directory.

## Setup

Create a TimelinkNotebook object. 

Note:
* First time run takes a little time as the required Docker images are downloaded.
* Timelink will default to using sqlite as the database, see [Receipts notebook for more control](1-receipts.ipynb)

In [151]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook()
tlnb.print_info(show_token=True)

WARNING:root:Reusing existing container eager_curie

Timelink version: 1.1.26
Project name: dehergne
Project home: /Users/jrc/mhk-home/sources/dehergne
Database type: sqlite
Database name: dehergne
Kleio image: timelinkserver/kleio-server
Kleio server token: ***REMOVED-KLEIO-TOKEN***
Kleio server URL: http://127.0.0.1:8089
Kleio server home: /Users/jrc/mhk-home/sources/dehergne
Kleio server container: eager_curie
Kleio version requested: latest
Kleio server version: 12.9.588 (2025-06-06 16:04:22)
SQLite directory: /Users/jrc/mhk-home/sources/dehergne/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne, project_home=/Users/jrc/mhk-home/sources/dehergne, db_type=sqlite, db_name=dehergne, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

### Database status

Count the number of rows in each table in the database.

In [152]:
tlnb.table_row_count_df()

               table  count
0               acts     28
1    alembic_version      1
2         aregisters      0
3         attributes  26820
4             blinks     97
5   class_attributes     58
6            classes     10
7           entities  32973
8        geoentities    359
9         kleiofiles     38
10             links    114
11           objects      0
12           persons   2132
13         relations   3547
14         rentities     48
15           sources     29
16            syslog      0
17            syspar      0

### Check the status of the files

Check the import status of the translated files

* I: Imported
* E: Imported with error
* W: Imported with warnings no errors
* N: Not imported
* U: Translation updated need to reimport

In [153]:
kleio_files = tlnb.get_kleio_files()
# kleio_files.info()
kleio_files[["name","import_status","status","errors","warnings","import_errors","import_warnings"]]

,name,import_status,status,errors,warnings,import_errors,import_warnings
0,dehergne-0-abrev.cli,I,V,0,0,0,0
1,dehergne-a.cli,I,V,0,0,0,0
2,dehergne-b.cli,I,V,0,0,0,0
3,dehergne-c.cli,I,V,0,0,0,0
4,dehergne-d.cli,I,V,0,0,0,0
5,dehergne-e.cli,I,V,0,0,0,0
6,dehergne-f.cli,I,V,0,0,0,0
7,dehergne-g.cli,I,V,0,0,0,0
8,dehergne-h.cli,I,V,0,0,0,0
9,dehergne-i.cli,I,V,0,0,0,0
10,dehergne-j.cli,I,V,0,0,0,0
11,dehergne-k.cli,I,V,0,0,0,0
12,dehergne-l.cli,I,V,0,0,0,0
13,dehergne-locations-1644.cli,I,V,0,0,0,0
14,dehergne-locations-1701.cli,I,V,0,0,0,0
15,dehergne-m.cli,I,V,0,0,0,0
16,dehergne-n.cli,I,V,0,0,0,0
17,dehergne-o.cli,I,V,0,0,0,0
18,dehergne-p.cli,I,V,0,0,0,0
19,dehergne-q.cli,I,V,0,0,0,0
20,dehergne-r.cli,I,V,0,0,0,0
21,dehergne-s.cli,I,V,0,0,0,0
22,dehergne-t.cli,I,V,0,0,0,0
23,dehergne-u.cli,I,V,0,0,0,0
24,dehergne-v.cli,I,V,0,0,0,0
25,dehergne-w.cli,I,V,0,0,0,0
26,dehergne-x.cli,I,V,0,0,0,0
27,dehergne-y.cli,I,V,0,0,0,0
28,dehergne-z.cli,I,V,0,0,0,0

Can filter by places of entry using
the ids saved above in `place_of_entry_ids`

Optionally filter by place of entry: get list of ids of people from place of entry to be used as filter

In [154]:
place_of_stay=None# set to None to show all places

In [155]:
import pandas as pd
from timelink.pandas import entities_with_attribute
from dehergne_util import calc_age_at
# show 500 rows
pd.set_option('display.max_rows', 1550)

place_of_entry = "Coimbra"

jesuits_of_place = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname','extra_info'],
    the_type='jesuita-entrada',
    the_value=place_of_entry,
    more_attributes=['dehergne','nascimento','embarque','morte'],
    db=tlnb.db,
)
place_of_entry_ids = jesuits_of_place.index.tolist()

In [156]:
import pandas as pd
from timelink.pandas import entities_with_attribute
# show 500 rows
pd.set_option('display.max_rows', 150)

place_of_entry = "Coimbra"

ids = place_of_entry_ids

places_of_stay = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname','the_line','the_order','extra_info'],
    the_type=['jesuita-entrada','partida','chegada','estadia','estadia-x',
                'jesuita-votos-local','jesuita-ordenacao-padre','morte'],
    the_value=place_of_stay,
    column_name='place',
    more_attributes=['jesuita-entrada','nascimento'],
    # filter_by=ids,
    db=tlnb.db,
)

# fillna with "?"
places_of_stay.place = places_of_stay.place.fillna('?')

# remove rows where place == '?'
places_of_stay = places_of_stay[places_of_stay.place != '?']

# this sequence replaces missing dates with the value of the previous date
# followed by ">". This allows to use the information that although the date
# is unkown it has happened after a certain date
# we need the id in a column to group by it (it is currently in the index)
# TODO: maybe an option in entities_with_attribute and compute intervals using
#       post quem and ante quem dates. See https://github.com/time-link/timelink-kleio/issues/1

places_of_stay['id_col'] = places_of_stay.index

# We try to infer the date of stay from the previous date known
# create a copy of the date column to replace the '0' values with NaN
places_of_stay['place.date_inferred'] = places_of_stay['place.date'].replace('0', pd.NA)

# order by id and line to have the missing date values filled with the previous date
places_of_stay = places_of_stay.sort_values(by=['id_col', 'place.line'])
# use ffill to fill the missing values with the previous value
places_of_stay['place.date_inferred'] = places_of_stay.groupby(['id_col'])['place.date_inferred'].ffill()
# create a column to flag the inferred dates
places_of_stay['place.date_is_inferred'] = places_of_stay['place.date_inferred'] != places_of_stay['place.date']
# reset index
places_of_stay.reset_index(inplace=True)
# if data_is_inferred set date_inferred to date_inferrred+">"
places_of_stay.loc[places_of_stay['place.date_is_inferred'], 'place.date_inferred'] = places_of_stay['place.date_inferred'] + '>'
# set missing value to ''
places_of_stay['place.date_inferred'] = places_of_stay['place.date_inferred'].fillna('')
# restore index
places_of_stay.index = places_of_stay['id_col']

places_of_stay.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6297 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             6297 non-null   object
 1   name                           6297 non-null   object
 2   groupname                      6297 non-null   object
 3   the_line                       6297 non-null   int64
 4   the_order                      6297 non-null   int64
 5   extra_info                     6297 non-null   object
 6   place.attr_id                  6297 non-null   object
 7   place.type                     6297 non-null   object
 8   place                          6297 non-null   object
 9   place.date                     6297 non-null   object
 10  place.line                     6297 non-null   int64
 11  place.level                    6297 non-null   int64
 12  place.obs                      6297 non-null   object
 13  place.extra_info               6297 non-null   object
 14  place.comment                  6192 non-null   object
 15  place.original                 225 non-null    object
 16  place.date.comment             1013 non-null   object
 17  place.date.original            12 non-null     object
 18  place.obs.original             1 non-null      object
 19  jesuita-entrada                5600 non-null   object
 20  jesuita-entrada.date           5600 non-null   object
 21  jesuita-entrada.obs            5600 non-null   object
 22  jesuita-entrada.extra_info     5600 non-null   object
 23  jesuita-entrada.date.comment   666 non-null    object
 24  jesuita-entrada.comment        3724 non-null   object
 25  jesuita-entrada.original       520 non-null    object
 26  jesuita-entrada.date.original  2 non-null      object
 27  nascimento                     5643 non-null   object
 28  nascimento.date                5643 non-null   object
 29  nascimento.obs                 5643 non-null   object
 30  nascimento.extra_info          5643 non-null   object
 31  nascimento.date.comment        1065 non-null   object
 32  nascimento.comment             5398 non-null   object
 33  nascimento.original            307 non-null    object
 34  id_col                         6297 non-null   object
 35  place.date_inferred            6297 non-null   object
 36  place.date_is_inferred         6297 non-null   bool
dtypes: bool(1), int64(4), object(32)
memory usage: 1.8+ MB

### Now extract the wikidata_id from the comments of place names

In [157]:
import pandas as pd
import re

def extract_wikidata_id(extra_info_dict):
    """
    Extract wikidata ID from place.extra_info JSON string.
    Returns the wikidata ID (e.g., 'Q6625') or NaN if not present.
    """
    if pd.isna(extra_info_dict):
        return pd.NA
    
    try:
        # Try to parse as JSON first (standard format with double quotes)
        
        comment = extra_info_dict.get('the_value', {}).get('comment', '')
        if comment and 'wikidata:' in comment:
            # Extract wikidata ID using regex pattern (Q followed by digits)
            match = re.search(r'wikidata:(Q\d+)', comment)
            if match:
                return match.group(1)
        return pd.NA
    except (ValueError, SyntaxError, TypeError):
        
        return pd.NA

# Apply the function to create the new column
places_of_stay['place.wikidata_id'] = places_of_stay['place.extra_info'].apply(extract_wikidata_id)

In [158]:

# show results
show_only=100
cols=['place','place.date_inferred','groupname','name','place.type', 'nascimento', 'nascimento.date', 'place.type','jesuita-entrada', 'jesuita-entrada.date', 'place.date_is_inferred','place.line','place.wikidata_id','place.extra_info']
places_of_stay[places_of_stay.groupname=='n'][cols].sort_values(by=['place','place.date_inferred','name',]).head(show_only)

,place,place.date_inferred,groupname,name,place.type,nascimento,nascimento.date,place.type,jesuita-entrada,jesuita-entrada.date,place.date_is_inferred,place.line,place.wikidata_id,place.extra_info
id_col,,,,,,,,,,,,,,
deh-charles-francois-xavier-de-brevedent,Abissínia,16980610,n,Charles-François Xavier de Brévedent,partida,"Genneville, Calvados",16590525,partida,Paris,16740909,False,1358,Q207521,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-antonio-sedeno,"Acapulco, México",15810329,n,Antonio Sedeño,estadia,"San Clemente, diocese de Cuenca",1535,estadia,Lorette,15590425,False,687,Q81398,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-antoine-rene-de-brasle,"Acapulco, México",<1707,n,Antoine-René de Brasle,estadia,"Château-Thierry, diocese de Soissons",16680815,estadia,?,16851006,False,1297,Q81398,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-antonio-de-magalhaes,Afeganistão,17000000,n,António de Magalhães,estadia,"Cortiços, diocese de Viseu",16770000,estadia,Coimbra,16921019,False,145,Q889,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-pierre-albier,Agen,16540712,n,Pierre Albier,jesuita-votos-local,Limousin,16200000,jesuita-votos-local,?,16440000,False,294,Q6625,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-philippe-avril,Agen,16910000,n,Philippe Avril,estadia,Angoulême (paróquia de Notre-Dame de Beaulieu),16540721,estadia,Bordeaux,16700916,False,1442,Q6625,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-bento-de-gois,Agra,16021029,n,Bento de Góis,estadia,"Vila Franca do Campo, ilha de S. Miguel, Açores",1563,estadia,?,1584,False,614,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-bento-de-gois,Agra,16021029,n,Bento de Góis,estadia,"Vila Franca do Campo, ilha de S. Miguel, Açores",1563,estadia,?,1588,False,614,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-antonio-de-andrade,Agra,16240330,n,António de Andrade,estadia,"Oleiros, diocese de Portalegre",15800000,estadia,Coimbra,15961216,False,1063,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-alano-dos-anjos,Agra,16360000,n,Alano dos Anjos,estadia,Pont-à-Mousson,15920000,estadia,?,16030919,False,819,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-heinrich-roth,Agra,1659,n,Heinrich Roth,estadia,Dillingen,16201218,estadia,?,16391025,False,1710,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-johann-grueber,Agra,16620331,n,Johann Grueber,estadia,Sankt Florian,16231028,estadia,Viena,16411013,False,1589,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-johann-grueber,Agra,16620904,n,Johann Grueber,estadia,Sankt Florian,16231028,estadia,Viena,16411013,False,1589,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-albert-le-comte-dorville,Agra,16630408,n,Albert le Comte Dorville,morte,Bruxelas,16210812,morte,Landsberg,16461102,False,742,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-heinrich-roth,Agra,16680620,n,Heinrich Roth,morte,Dillingen,16201218,morte,?,16391025,False,1710,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-albert-le-comte-dorville,Agra,<1663,n,Albert le Comte Dorville,estadia,Bruxelas,16210812,estadia,Landsberg,16461102,False,742,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-giuseppe-bruno,"Ajaccio, Córsega",16950522,n,Giuseppe Bruno,jesuita-votos-local,"Cuneo, Piemonte",16580121,jesuita-votos-local,Chieri,16801010,False,1574,Q40104,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pedro-gomez,Alcalá,15550925,n,Pedro Gómez,jesuita-entrada,"Antequera, diocese de Málaga, Andaluzia",1535,jesuita-entrada,Alcalá,15550925,False,848,Q46940,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-hernando-de-alcaraz,Alcalá,15580413,n,Hernando de Alcaraz,jesuita-entrada,"Navalafuente, diocese de Toledo",15320000,jesuita-entrada,Alcalá,15580413,False,361,Q46940,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-alonso-sanchez,Alcalá,15650702,n,Alonso Sanchéz,jesuita-entrada,"Mondéjar, Guadalajara",1545,jesuita-entrada,Alcalá,15650702,False,235,Q46940,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-melchior-mora,Alcalá,15700000,n,Melchior Mora,jesuita-entrada,"Caravaca de la Cruz, diocese de Cartagena",15450000,jesuita-entrada,Alcalá,15700000,False,1907,Q46940,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-pedro-ramon,Alcalá,1571,n,Pedro Ramón,jesuita-entrada,Saragoça,1550,jesuita-entrada,Alcalá,1571,False,42,Q46940,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-nicolas-gallardo,Alcalá,15710624,n,Nicolás Gallardo,jesuita-entrada,Valladolid,1551,jesuita-entrada,Alcalá,15710624,False,105,Q46940,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-alonso-sanchez,Alcalá,15930527,n,Alonso Sanchéz,morte,"Mondéjar, Guadalajara",1545,morte,Alcalá,15650702,False,235,Q46940,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-spinellus,Alcalá,1690,n,Spinellus,estadia,NaN,NaN,estadia,NaN,NaN,False,2174,Q46940,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-alessandro-valla,Alcácer-Quibir,1578,n,Alessandro Valla,estadia,Reggio,1529,estadia,Roma,15600507,False,378,Q52603,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pedro-martins,Alcácer-Quibir,15780804,n,Pedro Martins,estadia,Coimbra,15420000,estadia,Coimbra,15560525,False,792,Q52603,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-aloys-moriz,Alemanha,17760000,n,Aloys Moriz,estadia,"Landeck, Tirol",17380408,estadia,Landsberg,17571009,False,1986,Q183,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-philippe-avril,Alepo,,n,Philippe Avril,estadia,Angoulême (paróquia de Notre-Dame de Beaulieu),16540721,estadia,Bordeaux,16700916,True,1442,Q41183,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-louis-barnabe,Alepo,16850000,n,Louis Barnabé,estadia,Loches (Indre-et-Loire),16490830,estadia,?,16660831,False,306,Q41183,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-charles-francois-xavier-de-brevedent,Alepo,16940000,n,Charles-François Xavier de Brévedent,estadia,"Genneville, Calvados",16590525,estadia,Paris,16740909,False,1358,Q41183,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-gerard-arnould-rijckewaert,Alepo,17010222,n,Gerard Arnould Rijckewaert,estadia,"Ostend, Bélgica",16551128,estadia,?,16741003,False,675,Q41183,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jose-ramon-arxo,Alicante (convento dos franciscanos de Nossa S...,17110729,n,José Ramón Arxó,morte,"Benasque, Huesca",16630606,morte,Saragoça,16771115,False,1278,Q11959,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-fernao-mendes-pinto,Almada,15830708,n,Fernão Mendes Pinto,morte,"Montemor-o-Velho, diocese de Coimbra",15150000,morte,Goa,15540000,False,1284,Q328015,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-luis-de-almeida,Amakusa,15831000,n,Luís de Almeida,morte,Lisboa,15250000,morte,Japão,15560000,False,607,Q452622,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pedro-ramon,Amakusa,15910801,n,Pedro Ramón,jesuita-votos-local,Saragoça,1550,jesuita-votos-local,Alcalá,1571,False,42,Q452622,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-gil-martinez-de-la-mata,Amakusa,15911110,n,Gil Martínez de la Mata,jesuita-votos-local,"Logroño, diocese de Calahorra",15480000,jesuita-votos-local,?,15660312,False,947,Q452622,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-diogo-de-mesquita,Amakusa,15921122,n,Diogo de Mesquita,jesuita-votos-local,"Mesão Frio, diocese do Porto",15530000,jesuita-votos-local,Goa,15740400,False,1413,Q452622,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-diogo-pinto,"Ambon, Indonésia",,n,Diogo Pinto,estadia,"Quintela, diocese de Miranda",15440000,estadia,?,15660000,True,1328,Q219608,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-bernardino-ferrario,"Ambon, Indonésia",15840925,n,Bernardino Ferrario,morte,"Longobucco, Calábria",1537,morte,Nápoles,15560120,False,551,Q219608,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-bernard-rodes,Amesterdão,,n,Bernard Rodes,estadia,Pamiers,16460715,estadia,?,16740707,True,904,Q727,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-martino-martini,Amesterdão,16540000,n,Martino Martini,estadia,Trento,16140000,estadia,Roma,16321008,False,661,Q727,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-ignatus-hartogvelt,Amesterdão,16541127,n,Ignatus Hartogvelt,estadia,Amesterdão,16290516,estadia,Courtrai,16440926,False,226,Q727,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-ignatus-hartogvelt,Amesterdão,16541127,n,Ignatus Hartogvelt,estadia,Amesterdão,16290516,estadia,Mechelen,16441030,False,226,Q727,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-giovanni-laureati,"Amoy, Fukien",,n,Giovanni Laureati,estadia,Montecosaro,16660427,estadia,Roma,16821120,True,526,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-francisco-gayoso,"Amoy, Fukien",16780600,n,Francisco Gayoso,estadia,Soria,16470714,estadia,?,16650531,False,346,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-juan-miguel-de-irigoyen,"Amoy, Fukien",16780600,n,Juan Miguel de Irigoyen,estadia,"Pamplona, Navarra",16460419,estadia,?,16620319,False,164,Q68744,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-walter-ignazio-de-monte,"Amoy, Fukien",16780600,n,Walter Ignazio de Monte,estadia,Lucerne,16120720,estadia,?,16280907,False,1766,Q68744,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-louis-daniel-le-comte,"Amoy, Fukien",1691,n,Louis-Daniel Le Comte,estadia,Bordeaux,16551010,estadia,Bordeaux,16711015,False,697,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-nicolas-zarate,"Amoy, Fukien",16930000,n,Nicolás Zárate,estadia,Manila,16660507,estadia,?,16920303,False,62,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-nicolas-zarate,"Amoy, Fukien",16980000,n,Nicolás Zárate,estadia,Manila,16660507,estadia,?,16920303,False,62,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-bernard-rodes,"Amoy, Fukien",16990724,n,Bernard Rodes,estadia,Pamiers,16460715,estadia,?,16740707,False,904,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-francois-xavier-dentrecolles,"Amoy, Fukien",16990724,n,François-Xavier Dentrecolles,chegada,Diocese de Limoges,16640225,chegada,?,16820926,False,256,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jean-francois-foucquet,"Amoy, Fukien",16990724,n,Jean-François Foucquet,chegada,"Vézelay, diocese de Autun",16650512,chegada,Paris,16810917,False,1422,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pierre-frapperie,"Amoy, Fukien",16990724,n,Pierre Frapperie,chegada,Angoulême,16640309,chegada,?,16861002,False,1614,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jean-francois-pelisson,"Amoy, Fukien",16990725,n,Jean-François Pélisson,estadia,Gaillac,16570919,estadia,?,16730909,False,425,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jean-alexis-de-gollet,"Amoy, Fukien",17000823,n,Jean-Alexis de Gollet,estadia,Saint-Malo,16640504,estadia,?,16840915,False,722,Q68744,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jean-baptiste-chambeul-de-champeville,"Amoy, Fukien",17000829,n,Jean-Baptiste Chambeul de Champeville,chegada,Diocese de Saint-Flour,16611009,chegada,Toulouse,16800921,False,1246,Q68744,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-jacques-de-premilly,América,17090000,n,Jacques de Prémilly,partida,Poitou,16740404,partida,?,16910906,False,1805,Q30,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-guy-tachard,América do Sul,16800000,n,Guy Tachard,estadia,Marthon,16480000,estadia,Bordeaux,16680920,False,40,Q18,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-aleixo-coelho,Angola,1681,n,Aleixo Coelho,estadia,"Viana do Alentejo, diocese de Évora",1626,estadia,?,16451120,False,1654,Q916,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-patrice-comilh,Angoulême,16920202,n,Patrice Comilh,jesuita-votos-local,Bordeaux,16580411,jesuita-votos-local,?,16731119,False,1809,Q134346,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-jean-de-fontaney,Anjou,17100116,n,Jean de Fontaney,morte,"Diocese de S. Pol de Léon, Bretanha",16430217,morte,Paris,16581011,False,1315,Q107426,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-giovanni-francesco-de-ferrariis,Anking (Ngan-k'ing fou),>16710908,n,Giovanni Francesco De Ferrariis,morte,"Cuneo, Piemonte",16090000,morte,?,16241022,False,61,Q360374,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-louis-marie-dugad,"Anlo (Ngan-lo), Hupeh",,n,Louis-Marie Dugad,estadia,Lyon,17070226,estadia,Avignon,17231009,True,1049,Q557934,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jean-noellas,"Anlu (Ngan-lou), Hupei",17040000,n,Jean Noëllas,estadia,Clermont-Ferrand,16690530,estadia,?,16840228,False,266,Q557934,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-michael-pierre-boym,Annam,16471101,n,Michael-Pierre Boym,partida,Lwów,16120000,partida,Cracóvia,16310816,False,1155,Q881,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-alexandre-barvoets,Antuérpia,16401115,n,Alexandre Barvoets,estadia,Bruges,16191016,estadia,Mechelen,1636-09-30,False,493,Q12892,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-martino-martini,Antuérpia,16540000,n,Martino Martini,estadia,Trento,16140000,estadia,Roma,16321008,False,661,Q12892,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-ignace-melgar,Antuérpia,16690404,n,Ignace Melgar,morte,Dunkirk,16241204,morte,Mechelen,16420927,False,1187,Q12892,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-guillaume-van-der-beken,Antuérpia,16911214,n,Guillaume Van der Beken,estadia,Bruxelas,16591223,estadia,?,16771001,False,445,Q12892,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-gerard-arnould-rijckewaert,Antuérpia,17220106,n,Gerard Arnould Rijckewaert,morte,"Ostend, Bélgica",16551128,morte,?,16741003,False,675,Q12892,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-agostino-cappelli,"Aour, Madurai",17120908,n,Agostino Cappelli,jesuita-votos-local,Ascoli Piceno,16790828,jesuita-votos-local,?,16950310,False,321,Q228405,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-miguel-vieira,Aquilon,,n,Miguel Vieira,estadia,"Pedroso, diocese do Porto",16810929,estadia,Lisboa,17020912,True,1301,<NA>,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-simao-da-silveira,Aquilon,,n,Simão da Silveira,estadia,"Borba, diocese de Évora",16941103,estadia,Évora,17090311,True,1406,<NA>,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-pero-rodrigues,"Arima (seminário), Japão",1583,n,Pero Rodrigues,estadia,China,1568,estadia,?,15951004,False,1526,Q4790673,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pascoal-castangus,"Arima (seminário), Japão",1588,n,Pascoal Castangus,estadia,Macau,1568,estadia,?,1585,False,884,Q4790673,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-agostinho-detenes,"Arima (seminário), Japão",15880000,n,Agostinho Detenes,estadia,Macau,15670000,estadia,?,15860000,False,384,Q4790673,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-francisco-pacheco,"Arima, Japão",,n,Francisco Pacheco,estadia,"Ponte de Lima, diocese de Braga",15680000,estadia,Coimbra,15860000,True,66,Q4790673,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-melchior-mora,"Arima, Japão",,n,Melchior Mora,estadia,"Caravaca de la Cruz, diocese de Cartagena",15450000,estadia,Alcalá,15700000,True,1907,Q4790673,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-pero-rodrigues,"Arima, Japão",16111200,n,Pero Rodrigues,morte,China,1568,morte,?,15951004,False,1526,Q4790673,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-eusebio-francesco-kino,Arizona,,n,Eusebio Francesco Kino,estadia,"Segno, diocese de Trento",16450815,estadia,Landsberg,16651120,True,263,Q816,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-nicolas-trigault-junior,Armentières,16450824,n,Nicolas Trigault Junior,jesuita-votos-local,Douai,16110101,jesuita-votos-local,Tournai,16291002,False,1047,Q193925,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-jean-pierre-levert,Arménia,,n,Jean-Pierre Levert,estadia,Guyenne,16471018,estadia,?,16630917,True,977,Q399,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-philippe-avril,Arménia,,n,Philippe Avril,estadia,Angoulême (paróquia de Notre-Dame de Beaulieu),16540721,estadia,Bordeaux,16700916,True,1442,Q399,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-louis-barnabe,Arménia,16800000,n,Louis Barnabé,estadia,Loches (Indre-et-Loire),16490830,estadia,?,16660831,False,306,Q399,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-antoine-de-beauvollier,Arménia,>1689,n,Antoine de Beauvollier,estadia,Blaye (paróquia de Saint Romain),16570603,estadia,?,16720907,False,756,Q399,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-joseph-henri,Arménia (residência de Chamakii),16960000,n,Joseph Henri,estadia,?,16631030,estadia,?,16850312,False,85,Q399,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-joseph-henri,Arménia (residência de Chamakii),1711,n,Joseph Henri,estadia,?,16631030,estadia,?,16850312,False,85,Q399,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-giovanni-antonio-rubino,Arona,15960921,n,Giovanni Antonio Rubino,jesuita-entrada,"Strambino, diocese de Ivrea, Piemonte",15780301,jesuita-entrada,Arona,15960921,False,1900,Q22052,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-giacomo-rho,Arona,16140824,n,Giacomo Rho,jesuita-entrada,Pavia,15921029,jesuita-entrada,Arona,16140824,False,195,Q22052,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-francois-albert-souastre,Arras,17420508,n,François-Albert Soüastre,morte,Saint-Omer,16620306,morte,?,16800929,False,1995,Q131329,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-francois-albert-souastre,Arras (colégio),16960202,n,François-Albert Soüastre,jesuita-votos-local,Saint-Omer,16620306,jesuita-votos-local,?,16800929,False,1995,Q131329,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-simao-da-silveira,Assolna,1725,n,Simão da Silveira,estadia,"Borba, diocese de Évora",16941103,estadia,Évora,17090311,False,1406,Q4810289,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-philippe-avril,Astracã,,n,Philippe Avril,estadia,Angoulême (paróquia de Notre-Dame de Beaulieu),16540721,estadia,Bordeaux,16700916,True,1442,Q3927,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pierre-hebrard,Auch,17360109,n,Pierre Hébrard,morte,Diocese de Albi,16680112,morte,?,16821014,False,71,Q181725,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-jean-baptiste-chambeul-de-champeville,Aurillac,16960202,n,Jean-Baptiste Chambeul de Champeville,jesuita-votos-local,Diocese de Saint-Flour,16611009,jesuita-votos-local,Toulouse,16800921,False,1246,Q174234,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-etienne-faber,Avignon,,n,Etienne Faver,estadia,"Mourières, perto d'Avignon",15970214,estadia,Avignon,16150926,True,21,Q6397,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-etienne-faber,Avignon,16150926,n,Etienne Faver,jesuita-entrada,"Mourières, perto d'Avignon",15970214,jesuita-entrada,Avignon,16150926,False,21,Q6397,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-sebastiao-vieira,Avignon,16261225,n,Sebastião Vieira,estadia,"Castro Daire, diocese de Lamego",1574,estadia,Coimbra,15910203,False,1353,Q6397,"{'the_value': {'kleio_element_name': 'valor', ..."

### Save to Excel

In [159]:
places_of_stay[cols].sort_values(by=['place','place.date_inferred']).to_excel(f"../inferences/jesuita_entrada_places_of_stay.xlsx", sheet_name='wikidata', index=True)

#### Export to Excel all unlocated places

In [160]:
places_of_stay[ ~(places_of_stay['place.wikidata_id'].isna())][cols].sort_values(by=['place','place.date_inferred']).to_excel(f"../inferences/jesuita_entrada_places_of_stay_no_wikidata.xlsx", sheet_name='no_wikidata', index=True)

#### Only specific place of entry, unkown places

In [161]:
places_of_stay_specific = places_of_stay.loc[place_of_entry_ids]
places_of_stay_specific[~(places_of_stay_specific['place.wikidata_id'].isna())][cols].sort_values(by=['place','place.date_inferred'])

,place,place.date_inferred,groupname,name,place.type,nascimento,nascimento.date,place.type,jesuita-entrada,jesuita-entrada.date,place.date_is_inferred,place.line,place.wikidata_id,place.extra_info
id_col,,,,,,,,,,,,,,
deh-antonio-de-magalhaes,Afeganistão,17000000,n,António de Magalhães,estadia,"Cortiços, diocese de Viseu",16770000,estadia,Coimbra,16921019,False,145,Q889,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-antonio-de-magalhaes,Afeganistão,17000000,n,António de Magalhães,estadia,"Cortiços, diocese de Viseu",16770000,estadia,Coimbra,16921019,False,145,Q889,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-antonio-de-andrade,Agra,16240330,n,António de Andrade,estadia,"Oleiros, diocese de Portalegre",15800000,estadia,Coimbra,15961216,False,1063,Q42941,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-pedro-martins,Alcácer-Quibir,15780804,n,Pedro Martins,estadia,Coimbra,15420000,estadia,Coimbra,15560525,False,792,Q52603,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
deh-pedro-martins,Alcácer-Quibir,15780804,n,Pedro Martins,estadia,Coimbra,15420000,estadia,Coimbra,15560525,False,792,Q52603,"{'the_type': {'kleio_element_name': 'tipo', 'k..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
deh-francisco-perez,Índia,15520000,n,Francisco Pérez,estadia,"Villanueva de Barcarrota, diocese de Badajoz",15140000,estadia,Coimbra,15440125,False,867,Q668,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-antonio-de-andrade,Índia,16001002,n,António de Andrade,estadia,"Oleiros, diocese de Portalegre",15800000,estadia,Coimbra,15961216,False,1063,Q668,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-goncalo-da-fonseca,Índia,1645,n,Gonçalo da Fonseca,estadia,"Vila Real, diocese de Braga",1618,estadia,Coimbra,1634,False,1183,Q668,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-manuel-jorge,Índia,16510000,n,Manuel Jorge,jesuita-ordenacao-padre,Coimbra,16210000,jesuita-ordenacao-padre,Coimbra,16380000,False,105,Q668,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-luis-de-caldas,Índia,1722,n,Luís de Caldas,estadia,"Valadares, diocese de Braga",16891120,estadia,Coimbra,17041224,False,122,Q668,"{'the_type': {'kleio_element_name': 'tipo', 'k..."

In [162]:
places_of_stay_specific[~(places_of_stay_specific['place.wikidata_id'].isna())][cols].sort_values(by=['place','place.date_inferred']).to_excel(f"../inferences/jesuita_entrada_{place_of_entry}_places_of_stay_no_wikidata.xlsx", sheet_name='no_wikidata', index=True)

## Frequency of places / Frequência dos lugares

In [163]:
places_of_stay.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6297 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             6297 non-null   object
 1   name                           6297 non-null   object
 2   groupname                      6297 non-null   object
 3   the_line                       6297 non-null   int64
 4   the_order                      6297 non-null   int64
 5   extra_info                     6297 non-null   object
 6   place.attr_id                  6297 non-null   object
 7   place.type                     6297 non-null   object
 8   place                          6297 non-null   object
 9   place.date                     6297 non-null   object
 10  place.line                     6297 non-null   int64
 11  place.level                    6297 non-null   int64
 12  place.obs                      6297 non-null   object
 13  place.extra_info               6297 non-null   object
 14  place.comment                  6192 non-null   object
 15  place.original                 225 non-null    object
 16  place.date.comment             1013 non-null   object
 17  place.date.original            12 non-null     object
 18  place.obs.original             1 non-null      object
 19  jesuita-entrada                5600 non-null   object
 20  jesuita-entrada.date           5600 non-null   object
 21  jesuita-entrada.obs            5600 non-null   object
 22  jesuita-entrada.extra_info     5600 non-null   object
 23  jesuita-entrada.date.comment   666 non-null    object
 24  jesuita-entrada.comment        3724 non-null   object
 25  jesuita-entrada.original       520 non-null    object
 26  jesuita-entrada.date.original  2 non-null      object
 27  nascimento                     5643 non-null   object
 28  nascimento.date                5643 non-null   object
 29  nascimento.obs                 5643 non-null   object
 30  nascimento.extra_info          5643 non-null   object
 31  nascimento.date.comment        1065 non-null   object
 32  nascimento.comment             5398 non-null   object
 33  nascimento.original            307 non-null    object
 34  id_col                         6297 non-null   object
 35  place.date_inferred            6297 non-null   object
 36  place.date_is_inferred         6297 non-null   bool
 37  place.wikidata_id              6116 non-null   object
dtypes: bool(1), int64(4), object(33)
memory usage: 2.0+ MB

In [164]:
col = 'place' # subtotal by this column

# Use pandas groupby and specify unique value count for id
df_totals = places_of_stay.groupby(col).agg({'id':'nunique',
                                                'place.date_inferred':'min',
                                                'place.date':'max'})
df_totals.info()
df_totals.sort_values('id',ascending= False).head(130)

<class 'pandas.core.frame.DataFrame'>
Index: 1099 entries, Abissínia to Índia Oriental
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   1099 non-null   int64
 1   place.date_inferred  1099 non-null   object
 2   place.date           1099 non-null   object
dtypes: int64(1), object(2)
memory usage: 34.3+ KB

                                 id place.date_inferred   place.date
place
Macau                           449                            >1652
Pequim                          250                        >17410115
Goa                             209                            >1713
Cantão                          197                        >16590123
China                           180                         18050114
Lisboa                          130                         17810300
Roma                            110                        >16851112
Coimbra                          78                        <16230324
Paris                            65                         17780000
Nanquim                          64                             1780
Japão                            60                         17390425
Tonquim                          56                            <1659
Índia                            54                        <17070303
Sião                             53                         17510000
Shanghai                         47                         17451208
Cochinchina                      45                         17830512
Lorient                          43            17321110     17750627
Hangchow                         43                            >1636
Macau (colégio)                  39                         17580316
Évora                            37            15451225    <16230324
Malaca                           33                         17620517
Hainan                           33                      >1659:<1660
Hukwang                          32                      >1666:<1685
Manila                           31                        >16850206
[No mar, a caminho da China]     30                  00     17500624
Kiangsi                          29                            >1659
Europa                           29                            >1773
Filipinas                        25                            <1682
França                           23                        >17390000
Nagasaki                         22            15830725     16430322
Portugal                         22                         17820500
Moscovo                          22                         17220609
Lisboa (Forte de S. Julião)      21                1759     17770300
Bordeaux                         21                         17431107
Tartária                         21                         17890000
Kiang-nan                        20                            >1710
Vannes                           20            16540000     16541000
Cochim                           20                         17590528
México                           19                        <17110700
Kiangnan                         19                             1785
Amoy, Fukien                     18                         17000829
Itália                           18                             1817
Kwangtung                        16                            >1701
Fukien                           16                         17550000
Brest                            16             1685030     16980100
Landsberg                        15            16230729     17770411
Nancy                            15            16270929     17510827
Viena                            14            16271016     17880000
Avignon                          14                         17370927
Pérsia                           14                            <1701
Pondichéry                       14                             1773
Nápoles                          13                         17590414
Cambodja                         13                             1726
Génova                           13            16390915     17680930
Shangchuan                       13                1552     17010807
Hou-kouang                       12                         17690108
Saint-Malo                       12            17010905     17301210
Sungkiang                        12                             1781
Nanchang                         11                1600         1721
Honan                            11                         17660000
Trier                            11            16770821     17730228
Lyon                             11                         17310116
Paris (colégio Louis-le-Grand)   10                1710    >17510107
Mechelen                         10            16341015     16720424
Kiangchow, Shansi                10                            >1695
La Rochelle                      10            16420200     17090202
Batávia                          10                         17250000
Salcete, Índia                   10                       >1640:1643
Shensi                           10                             1698
Moçambique                       10                         17490705
Foochow                           9                         17001121
Soochow                           9                         17590000
Ningpo                            9                1627     17480000
Surat                             9                         17000202
Tournai                           9            15960705     16960929
Milão                             9            16160614     17170000
Port-Louis                        9            16980221     17670315
Isfahan, Pérsia                   9                         17470000
Douai                             8                             1678
Shiuchow (Chao-tcheou)            8            15891000         1612
Madrid                            8                         17370902
Kiang-si                          8                         17480128
Brasil                            8                             1758
Istambul                          8                             1723
Foochow, Fukien                   8                1631   >1626:1631
Chennai, Índia                    7                         16990708
Concépcion, Chile                 7            17040513     17110000
Goa (casa professa)               7            16500325     17400000
Fatshan                           7                         17630000
Bruxelas                          7            16540702     16541125
Toulouse                          7                            >1642
Agra                              7                            <1663
Kiangchow                         7                         17310800
Macau (colégio de S. José)        7                1732     17620705
Madurai                           7                         17141102
Alcalá                            7            15550925         1690
Marseille                         7            16880925     17250104
Tchö-kiang                        7            16171002        >1710
Shantung                          6                             1711
Leuven                            6                         16571209
Londres                           6            17031004     17050000
Shansi                            6                         17181020
Kiangchow, Chan-si                6            16241200     16960000
Castel Gandolfo                   6            17641010     17711201
Leao-tong                         6                         17430000
Kwangsi                           6                             1696
Bengala                           6                1576        >1661
[Missão]                          6                1645         1754
Antuérpia                         6            16401115     17220106
Poitiers                          6                         16930000
Arménia                           6                            >1689
Bolonha                           6            16680000     17741024
Molucas                           6                            <1623
Mysore                            6                             1754
[No mar, a caminho de Lisboa]     6                         17640512
Cracóvia                          6            16310816     17140727
Brno                              6            16060000     17261009
Esmirna, Pérsia                   6                             1695
Paris (colégio de La Flèche)      6                        >17510107
[No mar, a caminho da Índia]      6            16440502     17421200
Veneza                            5            15370624     17180424
Alepo                             5                         17010222
Lampacao                          5            15550000     15561007
Costa da Pescaria                 5                         16670202
Kiating                           5                            >1616
Síria                             5                         17151005
Florença                          5                         17140202
Chieri                            5            16280213     17240917
Tibete                            5                            >1661
Nanchang (Nan-tch'ang fou)        5            15951224     16611122

## Priesthood / Ordens sacras

Those that received the sacrament of priesthood in a given place

In [165]:
import pyuca  # to sort accented characters properly

import pandas as pd
from timelink.pandas import entities_with_attribute
# show 500 rows
pd.set_option('display.max_rows', 550)

jesuita_ordenacao_padre = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname'],
    the_type='jesuita-ordenacao-padre',
    the_value='Coimbra',
    more_attributes=['dehergne','jesuita-entrada','jesuita-votos-local','nascimento', ],
    db=tlnb.db,
)
jesuita_ordenacao_padre.info()

coll = pyuca.Collator()

# we use the Collator class to sort the names and countries properly
# since Python does not sort accented characters properly
# we create two new columns with the sort keys

# first we fill the NaN values with empty strings
jesuita_ordenacao_padre['jesuita-votos-local'] = jesuita_ordenacao_padre['jesuita-votos-local'].fillna('?')
jesuita_ordenacao_padre['jesuita-votos-local'] = jesuita_ordenacao_padre['jesuita-votos-local'].fillna('?')

# now we add two columns with sort keys
jesuita_ordenacao_padre['jesuita-votos-loc-sort'] = jesuita_ordenacao_padre['jesuita-votos-local'].apply(coll.sort_key)
jesuita_ordenacao_padre['name_sort'] = jesuita_ordenacao_padre['name'].apply(coll.sort_key)
jesuita_ordenacao_padre

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, deh-pedro-ramon to deh-manuel-de-siqueira-tcheng
Data columns (total 38 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   name                                  3 non-null      object
 1   groupname                             3 non-null      object
 2   jesuita-ordenacao-padre.attr_id       3 non-null      object
 3   jesuita-ordenacao-padre.type          3 non-null      object
 4   jesuita-ordenacao-padre               3 non-null      object
 5   jesuita-ordenacao-padre.date          3 non-null      object
 6   jesuita-ordenacao-padre.line          3 non-null      int64
 7   jesuita-ordenacao-padre.level         3 non-null      int64
 8   jesuita-ordenacao-padre.obs           3 non-null      object
 9   jesuita-ordenacao-padre.extra_info    3 non-null      object
 10  jesuita-ordenacao-padre.comment       3 non-null      object
 11  jesuita-ordenacao-padre.date.comment  1 non-null      object
 12  dehergne                              3 non-null      object
 13  dehergne.date                         3 non-null      object
 14  dehergne.obs                          3 non-null      object
 15  dehergne.extra_info                   3 non-null      object
 16  dehergne.comment                      2 non-null      object
 17  jesuita-entrada                       3 non-null      object
 18  jesuita-entrada.date                  3 non-null      object
 19  jesuita-entrada.obs                   3 non-null      object
 20  jesuita-entrada.extra_info            3 non-null      object
 21  jesuita-entrada.comment               3 non-null      object
 22  jesuita-entrada.date.comment          1 non-null      object
 23  jesuita-entrada.original              1 non-null      object
 24  jesuita-votos-local                   2 non-null      object
 25  jesuita-votos-local.date              2 non-null      object
 26  jesuita-votos-local.obs               2 non-null      object
 27  jesuita-votos-local.extra_info        2 non-null      object
 28  jesuita-votos-local.comment           2 non-null      object
 29  jesuita-votos-local.original          1 non-null      object
 30  jesuita-votos-local.date.comment      1 non-null      object
 31  nascimento                            3 non-null      object
 32  nascimento.date                       3 non-null      object
 33  nascimento.obs                        3 non-null      object
 34  nascimento.extra_info                 3 non-null      object
 35  nascimento.comment                    3 non-null      object
 36  nascimento.date.comment               1 non-null      object
 37  nascimento.original                   1 non-null      object
dtypes: int64(2), object(36)
memory usage: 1.0+ KB

,name,groupname,jesuita-ordenacao-padre.attr_id,jesuita-ordenacao-padre.type,jesuita-ordenacao-padre,jesuita-ordenacao-padre.date,jesuita-ordenacao-padre.line,jesuita-ordenacao-padre.level,jesuita-ordenacao-padre.obs,jesuita-ordenacao-padre.extra_info,...,jesuita-votos-local.date.comment,nascimento,nascimento.date,nascimento.obs,nascimento.extra_info,nascimento.comment,nascimento.date.comment,nascimento.original,jesuita-votos-loc-sort,name_sort
id,,,,,,,,,,,,,,,,,,,,,
deh-pedro-ramon,Pedro Ramón,n,deh-pedro-ramon-att22-202,jesuita-ordenacao-padre,Coimbra,1573,42,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,e 15910803,Saragoça,1550,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q31926034,None,None,"(7239, 7594, 7239, 7525, 7861, 7793, 7239, 0, ...","(7692, 7338, 7311, 7731, 7645, 521, 7731, 7239..."
deh-duarte-de-sande,Duarte de Sande,n,deh-duarte-de-sande-att220-193,jesuita-ordenacao-padre,Coimbra,1577,293,3,,"{'id': {'kleio_element_name': 'id', 'kleio_ele...",...,None,Guimarães,15471025,,"{'id': {'kleio_element_name': 'id', 'kleio_ele...",@wikidata:Q170903,antes de,None,"(7412, 7645, 7239, 0, 32, 32, 32, 0, 8, 2, 2, 0)","(7311, 7861, 7239, 7731, 7829, 7338, 521, 7311..."
deh-manuel-de-siqueira-tcheng,Manuel de Siqueira Tcheng,n,deh-manuel-de-siqueira-tcheng-att1183-193,jesuita-ordenacao-padre,Coimbra,1664,1654,3,,"{'id': {'kleio_element_name': 'id', 'kleio_ele...",...,NaN,Macau,0,"25 maio 1653 é a data que aparece, mas não pod...","{'id': {'kleio_element_name': 'id', 'kleio_ele...",@wikidata:Q14773,None,«Sinensis natus Macai»,"(614, 0, 32, 0, 2, 0)","(7594, 7239, 7609, 7861, 7338, 7543, 521, 7311..."

## Vows / Votos

In [166]:
import pyuca  # to sort accented characters properly

import pandas as pd
from timelink.pandas import entities_with_attribute
# show 500 rows
pd.set_option('display.max_rows', 550)

jesuita_entrada_full = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname'],
    the_type='jesuita-votos',
    more_attributes=['jesuita-votos-local','nascimento', 'jesuita-entrada'],
    db=tlnb.db,
)
jesuita_entrada_full.info()

coll = pyuca.Collator()

# we use the Collator class to sort the names and countries properly
# since Python does not sort accented characters properly
# we create two new columns with the sort keys

# first we fill the NaN values with empty strings
jesuita_entrada_full['jesuita-votos-local'] = jesuita_entrada_full['jesuita-votos-local'].fillna('?')
jesuita_entrada_full['jesuita-votos-local'] = jesuita_entrada_full['jesuita-votos-local'].fillna('?')

# now we add two columns with sort keys
jesuita_entrada_full['jesuita-votos-loc-sort'] = jesuita_entrada_full['jesuita-votos-local'].apply(coll.sort_key)
jesuita_entrada_full['name_sort'] = jesuita_entrada_full['name'].apply(coll.sort_key)

<class 'pandas.core.frame.DataFrame'>
Index: 628 entries, deh-paul-banhes-wan to deh-giovanni-antonio-grassi
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   name                              628 non-null    object
 1   groupname                         628 non-null    object
 2   jesuita-votos.attr_id             628 non-null    object
 3   jesuita-votos.type                628 non-null    object
 4   jesuita-votos                     628 non-null    object
 5   jesuita-votos.date                628 non-null    object
 6   jesuita-votos.line                628 non-null    int64
 7   jesuita-votos.level               628 non-null    int64
 8   jesuita-votos.obs                 628 non-null    object
 9   jesuita-votos.extra_info          628 non-null    object
 10  jesuita-votos.date.comment        31 non-null     object
 11  jesuita-votos.date.original       2 non-null      object
 12  jesuita-votos.comment             5 non-null      object
 13  jesuita-votos-local               528 non-null    object
 14  jesuita-votos-local.date          528 non-null    object
 15  jesuita-votos-local.obs           528 non-null    object
 16  jesuita-votos-local.extra_info    528 non-null    object
 17  jesuita-votos-local.comment       503 non-null    object
 18  jesuita-votos-local.original      42 non-null     object
 19  jesuita-votos-local.date.comment  13 non-null     object
 20  nascimento                        603 non-null    object
 21  nascimento.date                   603 non-null    object
 22  nascimento.obs                    603 non-null    object
 23  nascimento.extra_info             603 non-null    object
 24  nascimento.comment                578 non-null    object
 25  nascimento.original               32 non-null     object
 26  nascimento.date.comment           109 non-null    object
 27  jesuita-entrada                   599 non-null    object
 28  jesuita-entrada.date              599 non-null    object
 29  jesuita-entrada.obs               599 non-null    object
 30  jesuita-entrada.extra_info        599 non-null    object
 31  jesuita-entrada.comment           353 non-null    object
 32  jesuita-entrada.original          49 non-null     object
 33  jesuita-entrada.date.comment      66 non-null     object
dtypes: int64(2), object(32)
memory usage: 171.7+ KB

In [167]:
# filter dataframe with rows with index in place_of_entry_ids

In [168]:
from timelink.kleio.utilities import convert_timelink_date

df = jesuita_entrada_full[jesuita_entrada_full.index.isin(place_of_entry_ids)].copy()
# calculate age at date "jesuita-votos.date" considering "nascimento.date" as date of birth
# and using the function convert_timelink_date to convert the Timelink date to a Python datetime
df['nascimento.date_2'] = df['nascimento.date'].fillna('0').apply(convert_timelink_date)
df['jesuita-votos.date_2'] = df['jesuita-votos.date'].fillna('0').apply(convert_timelink_date)
# calculate diference in years between the two dates
df['age_at_votos'] = df.apply(lambda row: calc_age_at(row['nascimento.date_2'], row['jesuita-votos.date_2']), axis=1)
df['age_at_votos'] = df['age_at_votos'].fillna(0).astype(int)
df[['nascimento.date','jesuita-votos.date','jesuita-votos','age_at_votos']].head(50)

,nascimento.date,jesuita-votos.date,jesuita-votos,age_at_votos
id,,,,
deh-tiburcio-de-quadros,15280000,15531001,4V,25
deh-belchior-miguel-carneiro-leitao,1519,15540624,4V,34
deh-joao-rodrigues-de-sainan,1531,1557,Primeiros votos,26
deh-belchior-nunes-barreto,15190000,15570921,4V,38
deh-cristovao-da-costa,1529,1558,3V,28
deh-francisco-perez,15140000,15600106,3V,45
deh-goncalo-alvares,15270000,15600609,4V,32
deh-pedro-martins,15420000,15700423,4V,27
deh-lourenco-mexia,15390800,15700423,4V,30
deh-nicolau-pimenta,15461206,15860528,4V,39
deh-francisco-vieira,15550,15950709,4V,40
deh-joao-rodrigues-girao,1558,1599,Coadjutor Espiritual,40
deh-manuel-gaspar,1554,16010419,4V,46
deh-mateus-de-couros,1569,16021208,4V,33
deh-francisco-pacheco,15680000,16030706,4V,35
deh-andre-palmeiro,15690000,16030727,4V,34
deh-joao-soeiro,1566,1604,4V,38
deh-joao-da-rocha,1565,16040426,4V,38
deh-diogo-correia-valente,1568,16050130,4V,36
deh-sebastiao-vieira,1574,16111127,4V,37
deh-antonio-de-andrade,15800000,16121014,4V,32
deh-gaspar-ferreira,1571,16121121,4V,41
deh-manuel-dias-o-novo,15740000,16160918,4V,42
deh-francisco-furtado,1589,16260503,4V,36
deh-simao-da-cunha,1589,16261202,4V,37
deh-sebastiao-da-maia,15970000,16321208,4V,35
deh-gaspar-do-amaral,15920000,16380106,4v,45
deh-antonio-de-gouvea,1592,16460714,4V,54
deh-goncalo-da-fonseca,1618,16490815,Coadjutor Espiritual,31
deh-matias-da-maia,16160000,16500325,4V,33
deh-manuel-jorge,16210000,16581112,4V,37
deh-manuel-jorge,16210000,16581112,4V,37
deh-andre-ferrao,1625,16590116,4V,33
deh-gabriel-de-magalhaes,1610,16600205,4V,49
deh-tome-pereira,16451101,16800815,4V,34
deh-andre-carneiro,1650,16821208,4V,32
deh-joao-da-silva,1647,16850202,4V,37
deh-antonio-da-silva,16540113,16870815,4V,33
deh-manuel-mendes,16560101,16900815,4V,34
deh-manuel-mendes,16560101,16900815,4V,34
deh-miguel-do-amaral,16571213,16910815,4V,33
deh-manuel-de-sa,16580422,16930815,4V,35
deh-manuel-osorio-i,16630305,16950815,4V,32
deh-francisco-pinto-i,16620529,16950815,4V,33
deh-estanislau-machado,16670000,17000202,4V,32
deh-antonio-de-magalhaes,16770000,17110202,4V,33
deh-antao-dantas,16741102,17110815,4V,36
deh-antonio-de-melo,16810803,17191203,4V,38
deh-estevao-lopes,16930321,17260616,4V,33
deh-jose-montanha-ii,17080103,17400325,4V,32

## Voyages

In [169]:
import pandas as pd
from timelink.pandas import entities_with_attribute
# show 500 rows
pd.set_option('display.max_rows', 550)

voyage_of_interest = 25

voyage = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname'],
    the_type='wicky-viagem',
    the_value=str(voyage_of_interest),
    more_attributes=['embarque','chegada','partida',],
    db=tlnb.db,
)
voyage

,name,groupname,wicky-viagem.attr_id,wicky-viagem.type,wicky-viagem,wicky-viagem.date,wicky-viagem.line,wicky-viagem.level,wicky-viagem.obs,wicky-viagem.extra_info,...,chegada.obs,chegada.extra_info,chegada.comment,chegada.date.comment,partida,partida.date,partida.obs,partida.extra_info,partida.comment,partida.date.comment
id,,,,,,,,,,,,,,,,,,,,,
deh-duarte-de-sande,Duarte de Sande,n,deh-duarte-de-sande-att205-193,wicky-viagem,25,15780324,293,3,,"{'id': {'kleio_element_name': 'id', 'kleio_ele...",...,NaN,NaN,NaN,NaN,Macau,15850501,,"{'id': {'kleio_element_name': 'id', 'kleio_ele...",@wikidata:Q14773,None
deh-francesco-pasio,Francesco Pasio,n,deh-francesco-pasio-att275-201,wicky-viagem,25,15780324,365,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q14773,"início, fica doente a 15 de Julho",Macau,16120322,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q14773,None
deh-matteo-ricci,Matteo Ricci,n,deh-matteo-ricci-att349-202,wicky-viagem,25,15780324,557,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q1171,None,Pequim,16000519,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q956,None
deh-matteo-ricci,Matteo Ricci,n,deh-matteo-ricci-att349-202,wicky-viagem,25,15780324,557,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q14773,None,Pequim,16000519,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q956,None
deh-matteo-ricci,Matteo Ricci,n,deh-matteo-ricci-att349-202,wicky-viagem,25,15780324,557,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q956,None,Pequim,16000519,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q956,None
deh-michele-ruggiere,Michele (Pompilio) Ruggiere,n,deh-michele-ruggiere-att1383-202,wicky-viagem,25,15780324,1947,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q14773,None,Roma,15881100,,"{'the_value': {'kleio_element_name': 'valor', ...",@wikidata:Q220,chamado para projectar uma embaixada do papa
deh-giovanni-gerardino,Giovanni Gerardino,n,deh-giovanni-gerardino-att269-182,wicky-viagem,25,15780324,388,3,,"{'the_value': {'kleio_element_name': 'valor', ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Visualizar registos / View records

### Visualizar uma pessoa / View a person

#### Atributos de uma pessoa numa tabela, uma linha por attributo

---

#### Person attributes in a dataframe, one line per attribute

In [175]:
import pandas as pd
from timelink.pandas import group_attributes as person_attributes

pd.set_option('display.max_rows',1000)

id = 'deh-bento-de-gois'
pdf = person_attributes([id],db=tlnb.db)  # note id in a list
pdf[['the_date','the_type','the_value','attr_obs']].sort_values(['the_date','the_type'])

,the_date,the_type,the_value,attr_obs
id,,,,
deh-bento-de-gois,0,dehergne,366,"""""""Góis (Goes), Bento (= Benoît) de (port.) f..."
deh-bento-de-gois,0,jesuita-estatuto,Frade Coadjutor,
deh-bento-de-gois,0,jesuita-tarefa,Sai da Companhia,
deh-bento-de-gois,0,nacionalidade,Portugal,
deh-bento-de-gois,0,nome,Bento de Goes,
deh-bento-de-gois,0,nome,Bento de Goesio,
deh-bento-de-gois,0,nome,Bento de Goëz,
deh-bento-de-gois,0,nome-chines,Ngo Pen-tou,
deh-bento-de-gois,0,profissao,Soldado,
deh-bento-de-gois,0,pseudonimo,Abdullah Isai,
deh-bento-de-gois,0,pseudonimo,Banda Abdullah,
deh-bento-de-gois,0,tarefa,Identifica o Grão Cataio com a China e Cambali...,
deh-bento-de-gois,1563,nascimento,"Vila Franca do Campo, ilha de S. Miguel, Açores",
deh-bento-de-gois,15630000,nascimento@wikidata,https://www.wikidata.org/wiki/Q565290,
deh-bento-de-gois,15839999.7,estadia@wikidata,https://www.wikidata.org/wiki/Q668,
deh-bento-de-gois,1584,jesuita-entrada,?,
deh-bento-de-gois,1588,jesuita-entrada,?,
deh-bento-de-gois,1588,jesuita-tarefa,Pede para ir para as missões do Grão Mogol,
deh-bento-de-gois,1598,chegada,Lahora (corte do Grão Mogol),
deh-bento-de-gois,15980000,chegada@wikidata,https://www.wikidata.org/wiki/Q11739,
deh-bento-de-gois,15980613,jesuita-votos,Coadjutor Temporal,
deh-bento-de-gois,15980613,jesuita-votos-local,Lahore,
deh-bento-de-gois,15980613,jesuita-votos-local@wikidata,https://www.wikidata.org/wiki/Q11739,
deh-bento-de-gois,16010500,cargo,Embaixador do Grão Mogol,
deh-bento-de-gois,16021029,estadia,Agra,
deh-bento-de-gois,16021029,estadia@wikidata,https://www.wikidata.org/wiki/Q42941,
deh-bento-de-gois,16021029,partida,China,disfarçado de mercador arménio
deh-bento-de-gois,16021029,partida@wikidata,https://www.wikidata.org/wiki/Q148,
deh-bento-de-gois,16021208,estadia,Lahore,
deh-bento-de-gois,16021208,estadia@wikidata,https://www.wikidata.org/wiki/Q11739,
deh-bento-de-gois,16031099.7,estadia@wikidata,https://www.wikidata.org/wiki/Q161750,
deh-bento-de-gois,16031100,estadia,Yarkand,
deh-bento-de-gois,16031100,estadia@wikidata,https://www.wikidata.org/wiki/Q857618,
deh-bento-de-gois,16031100.3,estadia@wikidata,https://www.wikidata.org/wiki/Q868527,
deh-bento-de-gois,16051017,estadia,Hami,
deh-bento-de-gois,16051017,estadia@wikidata,https://www.wikidata.org/wiki/Q989892,
deh-bento-de-gois,16051017.3,estadia@wikidata,https://www.wikidata.org/wiki/Q532560,
deh-bento-de-gois,16051222,estadia,Suchou,
deh-bento-de-gois,16051222,estadia@wikidata,https://www.wikidata.org/wiki/Q131962,
deh-bento-de-gois,16070411,morte,Sou-tcheou do Kan-sou,
deh-bento-de-gois,16070411,morte@wikidata,https://www.wikidata.org/wiki/Q131962,
deh-bento-de-gois,<1584,estadia,Índia,
deh-bento-de-gois,<16031100,estadia,Pamir,
deh-bento-de-gois,>1603-11,estadia,Tourphan,
deh-bento-de-gois,>16051017,estadia,Kia-yu-louan,

In [171]:
tlnb.db.pperson(id)

n$Bento de Góis/m/id=deh-bento-de-gois
  ls$nacionalidade/Portugal/
  ls$jesuita-estatuto/Frade Coadjutor/
  ls$nome/Bento de Goes/
  ls$nome/Bento de Goesio/
  ls$nome/Bento de Goëz/
  ls$nome-chines/Ngo Pen-tou/
  ls$profissao/Soldado/
  ls$jesuita-tarefa/Sai da Companhia#para se tornar padre/
  ls$pseudonimo/Abdullah Isai/
  ls$pseudonimo/Banda Abdullah/
  ls$tarefa/Identifica o Grão Cataio com a China e Cambalik com Pequim/
  ls$dehergne/366//obs="""Góis (Goes), Bento (= Benoît) de (port.) fr. coadj. 366
            Gôis est la forme moderne du nom (cf Verbo).,
            Goesio., de Goëz. Ngo Pen-tou (Pf.).
            N. 1563, Villa Franca do Campos, île S. Miguel, Açores.
            Soldat aux Indes.,
            E. comme fr. coadj. en 1584 et sorti pour devenir prêtre,
               il entre de nouveau en 1588 et demande les missions du Grand Mogol.
            Arr. 1598, Lahore, à la cour du Grand Mogol Akbar.,
               devient son ambassadeur à Goa, mai 1601.,
            revient Agra.,
            en repart le 29 oct. 1602 pour le « Cathay »,
               déguisé en marchand arménien sous le nom d'ABDULLAH Isai et de Banda Abdullah (cf AHSI 22 (1953) p. 157 n° 320).,
            Lahore, 8 déc. 1602.,
            Yarkand, fin nov. 1603.,
            le Pamir.,
            Tourphan.,
            Hami, 17 oct. 1605.,
            Kia-yu-louan., Suchow du Kan-sou (Sou-tcheou, actuel Kiuchûan),
               à l'extrémité de la Grande Muraille, 22 déc. 1605
               (D'Elia II, 396 et III, 152).
            Ricci lui envoie le fr. Jean Fernandes.
            Gôis a identifié « le Cathay » avec la Chine, et « Cambalik (Kambalucq) » avec Pékin.
            V. « Lahor » cité du Grand Mogol, 13 juin 1598,
            coadj. temp. (Lus. 25, 119. Il signe B. de Goes.
            M. Sou-tcheou du Kan-sou, 11 avril 1607 «in Cathaio» (HS 43, 58).
            Pf. 95., EC (Cel. Testore).,
            Verbo (D. Mauricio).,
            Koch. TV Centenario de Bento de Goes (léffl-lWl), Homagem da Sociedade de Geographia de Lisboa, 1907.,
            Yule-Cordier, Cathay t. IV, London, 1916, p. 169-259.,
            Wessels, Early Travellers in Central Asia, The Hague, 1924, p. 1-41.,
            Wessels, The Grave of Bento de Goes,
            AHSI IV, 1935, p. 337-339.,
            Maclagan, E., The Jesuits and the Great Mogul, London, 1932, 51-54, 331-340, 363-372.,
            Bernard-Maître, H., Le Frère Bento de Goez chez tes Musulmans de la Haute Asie, Tientsin, 1934.,
            Sir Percy M. Sykes, The Quest for Cathay, London, 1936, trad. française A la recherche du Cathay, Paris, 1938., et trad. allem. Leipzig 1938.,
            Brazâo, Eduardo, A viagem de Bento de Goes a China, Lisboa, 1954
            Candido, Armando, Exaltaçâo de Bento de Gois, Lisboa, Imprensa Nacional, 1962.,
            Cronin, Vincent, The Wise Man from the West, Londres, 1955, 236-256.,
            Lach, 277-278.,
            Streit V, n° 2035., XIII n° 1921.,
            RBS 405. Statue (en costume de marchand persan) à Villa-Franca do Campos. Timbres édités en Portugal en 1968.
"""
  ls$nascimento/Vila Franca do Campo, ilha de S. Miguel, Açores#@wikidata:Q565290/1563
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q565290"%Vila Franca do Campo, ilha de S. Miguel, Açores/1563
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q668"%Índia/15839999.7
  ls$jesuita-entrada/?#suponho que na Índia/1584#entra como frade coadjutor
  ls$jesuita-entrada/?#suponho que na Índia/1588
  ls$jesuita-tarefa/Pede para ir para as missões do Grão Mogol/1588
  ls$chegada/Lahora (corte do Grão Mogol)#@wikidata:Q11739 (hoje no Paquistão)/1598
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q11739"%Lahora (corte do Grão Mogol)/1598
  ls$jesuita-votos/Coadjutor Temporal/1598-06-13
  ls$jesuita-votos-local@wikidata/"https://www.wikidata.org/wiki/Q11739"%Lahore/1598-06-13
  ls$jesuita-votos-local/Lahore#@wikidata:Q11739 (hoje no Paquistão)%« Lahor » cité du Grand Mogol/1598-06-13
  rel$profissional/Embaixador/Akbar/deh-bento-de-gois/1601-05
  ls$cargo/Embaixador do Grão Mogol/1601-05
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q42941"%Agra/1602-10-29
  ls$estadia/Agra#@wikidata:Q42941/1602-10-29#até
  ls$partida@wikidata/"https://www.wikidata.org/wiki/Q148"%China/1602-10-29
  ls$partida/China#@wikidata:Q148%le Cathay/1602-10-29/obs=disfarçado de mercador arménio
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q11739"%Lahore/1602-12-08
  ls$estadia/Lahore#@wikidata:Q11739 (hoje no Paquistão)/1602-12-08
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q161750"%Pamir/16031099.7
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q857618"%Yarkand/1603-11
  ls$estadia/Yarkand#@wikidata:Q857618/1603-11#fim do mês
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q868527"%Tourphan/16031100.3
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q989892"%Hami/1605-10-17
  ls$estadia/Hami#@wikidata:Q989892/1605-10-17
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q532560"%Kia-yu-louan/16051017.3
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q131962"%Suchou/1605-12-22
  ls$estadia/Suchou#@wikidata:Q131962%Suchow du Kan-sou (Sou-tcheou, actuel Kiuchûan)/1605-12-22
  rel$sociabilidade/Companheiro/Jean Fernandes Tchong/deh-bento-de-gois/1606/obs=a data vem da entrada de Jean Fernandes Tchong
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q131962"%Sou-tcheou do Kan-sou/1607-04-11
  ls$morte/Sou-tcheou do Kan-sou#@wikidata:Q131962/1607-04-11
  ls$estadia/Índia#@wikidata:Q668/<1584
  ls$estadia/Pamir#@wikidata:Q161750/<16031100#Pamir antes de Yarkand
  ls$estadia/Tourphan#Turpan @wikidata:Q868527/>1603-11
  ls$estadia/Kia-yu-louan#@wikidata:Q532560/>16051017
  referido$Akbar/m/id=deh-bento-de-gois-ref1
    ls$titulo/Grão-Mogol/
    <rel$profissional/Embaixador/Bento de Góis/deh-bento-de-gois/1601-05
  referido$Matteo Ricci/m/id=deh-bento-de-gois-ref2
    rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
    rel$sociabilidade/Envia em auxílio de Bento de Góis/Jean Fernandes Tchong/deh-bento-de-gois-ref2/1606/obs=a data vem da entrada de Jean Fernandes Tchong
  rel$identification/same as/Matteo Ricci/deh-matteo-ricci/
  referido$Jean Fernandes Tchong/m/id=deh-bento-de-gois-ref3/obs=Dehergne 291
    ls$jesuita-estatuto/Frade Coadjutor/
    <rel$sociabilidade/Companheiro/Bento de Góis/deh-bento-de-gois/1606/obs=a data vem da entrada de Jean Fernandes Tchong
    <rel$sociabilidade/Envia em auxílio de Bento de Góis/Matteo Ricci/deh-bento-de-gois-ref2/1606/obs=a data vem da entrada de Jean Fernandes Tchong

#### Atributos de uma pessoa numa tabela, attributos em colunas

---

#### Person attributes in a dataframe, attributes in columns

In [172]:
# Get list of people with with a certain value in a specific attribute

id = 'deh-andre-palmeiro'  # João Pedro Ribeiro
# id = '234295'  # Alexandre Metelo de Sousa
df = entities_with_attribute(
                    entity_type='person',
                    the_type='jesuita-entrada',  # we need a base attribute
                    show_elements=['name'],
                    more_attributes=['jesuita-votos','jesuita-votos-local'],
                    db=tlnb.db,
                    filter_by=[id],
                    sql_echo=False)
view_cols = ['name','jesuita-entrada','jesuita-entrada.date','jesuita-votos','jesuita-votos-local']
df.info()
df[view_cols].sort_values('jesuita-entrada.date')

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, deh-andre-palmeiro to deh-andre-palmeiro
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            1 non-null      object
 1   jesuita-entrada.attr_id         1 non-null      object
 2   jesuita-entrada.type            1 non-null      object
 3   jesuita-entrada                 1 non-null      object
 4   jesuita-entrada.date            1 non-null      object
 5   jesuita-entrada.line            1 non-null      int64
 6   jesuita-entrada.level           1 non-null      int64
 7   jesuita-entrada.obs             1 non-null      object
 8   jesuita-entrada.extra_info      1 non-null      object
 9   jesuita-entrada.original        1 non-null      object
 10  jesuita-entrada.comment         1 non-null      object
 11  jesuita-votos                   1 non-null      object
 12  jesuita-votos.date              1 non-null      object
 13  jesuita-votos.obs               1 non-null      object
 14  jesuita-votos.extra_info        1 non-null      object
 15  jesuita-votos-local             1 non-null      object
 16  jesuita-votos-local.date        1 non-null      object
 17  jesuita-votos-local.obs         1 non-null      object
 18  jesuita-votos-local.extra_info  1 non-null      object
 19  jesuita-votos-local.original    1 non-null      object
 20  jesuita-votos-local.comment     1 non-null      object
dtypes: int64(2), object(19)
memory usage: 284.0+ bytes

,name,jesuita-entrada,jesuita-entrada.date,jesuita-votos,jesuita-votos-local
id,,,,,
deh-andre-palmeiro,André Palmeiro,Coimbra,15840114,4V,Coimbra

# Examinar potenciais duplicados

---

## Examine potentital duplicates

In [173]:
from timelink.pandas import display_group_attributes
pd.set_option('display.max_rows',250)

no_show=['código-de-referência','data-do-registo','url','faculdade.ano','naturalidade.ano',
         'matricula-faculdade.ano','nome-apelido','nome-primeiro','nome-geografico.ano',
         'grau.ano','matricula-outra.ano','nome-geografico','instituta.ano']

dup_ids = ['deh-joao-barradas-ref1','deh-lazzaro-cattaneo-ref1','deh-matteo-ricci'] 

display_group_attributes(dup_ids,
                             header_attributes=['jesuita-entrada','nacionalidade'],
                             exclude_attributes=no_show,
                             sort_attributes=['the_date','the_type','the_value'],
                             cmap_name='Pastel1',
                             db=tlnb.db,)

In [174]:
# print current timestamp
from datetime import datetime

# print current timestamp
print(f"Analysis completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

Analysis completed at: 2025-12-25 23:04:35