# Location Analysis (new version)

This notebook processes and enriches location data from the Dehergne dataset to prepare it for geographic visualization and analysis.

**Workflow Stages:**

1.  **Data Extraction**:
    It gathers personal attributes related to locations (e.g., `nascimento`, `jesuita-entrada`, `morte`, `estadia`) into a unified DataFrame.

2.  **Date Inference**:
    Because many location attributes lack explicit dates, it infers them based on the chronological order of events in each person's biography (`ffill` method). It flags these inferred dates (`place.date_is_inferred`) for transparency.

3.  **Wikidata Enrichment**:
    It extracts Wikidata IDs from the source comments (e.g., `@wikidata:Q123`) to link historical place names to modern geodata.

4.  **Exports & Reports**:
    Generates several datasets in `../inferences/` for further use:
    *   `places_of_stay.xlsx`: Comprehensive list of stays with Wikidata IDs.
    *   `locations_names_places_dates_only.xlsx`: Simplified list for timeline visualization.
    *   `wikidata-references/locations_names_wikidata.csv`: Unique list of Wikidata IDs for the geocoding pipeline.
    *   `locations_names_no_wikidata.xlsx`: "To-do" list of places missing Wikidata links.
    *   `locations_totals.xlsx`: Frequency analysis of places (visit counts, date ranges).

5.  **Specific Analysis**:
    *   Filters missionaries by a specific place of entry (defaul: *Coimbra*).
    *   Exports individual markdown summaries associated with a specific place for review.

In [2]:
import os
import re
import pandas as pd
from timelink.notebooks import TimelinkNotebook
from timelink.pandas import entities_with_attribute
from timelink.kleio.utilities import format_timelink_date

pd.set_option("display.max_rows", 150)

tlnb = TimelinkNotebook()
db = tlnb.db
tlnb.print_info()

WARNING:root:Reusing existing container affectionate_nobel

Timelink version: 1.1.33
Project name: dehergne
Project home: /Users/jrc/mhk-home/sources/dehergne
Database type: sqlite
Database name: dehergne
Kleio image: timelinkserver/kleio-server
Kleio server token: G9cKJ...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/mhk-home/sources/dehergne
Kleio server container: affectionate_nobel
Kleio version requested: latest
Kleio server container status: running
Kleio server version: 12.9.592 (2026-03-19 23:14:02)
SQLite directory: /Users/jrc/mhk-home/sources/dehergne/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne, project_home=/Users/jrc/mhk-home/sources/dehergne, db_type=sqlite, db_name=dehergne, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

## Attribute configuration
Attributes that store place names.

In [3]:
ATTRIBUTES_WITH_PLACE_NAMES = [
    'nascimento',
    'jesuita-entrada',
    'partida',
    'chegada',
    'estadia',
    'estadia-x',
    'jesuita-votos-local',
    'jesuita-ordenacao-padre',
    'morte',
]

## Visualization parameters

Columns to show in dataframe visualization

In [4]:

PREVIEW_COLS = [
    'place',
    'wikidata_id',
    'place.date_inferred.formatted',
    'place.date_inferred',
    'place.date_is_inferred',
    'name',
    'groupname',
    'place.type',
    'place.original',
    'place.line',
]

## Load place attributes and infer missing dates

We try to infer attributes with missing dates.
Sometimes the dates of some attribute are missing in the transcription, because in the original data they were not explicitly mentioned. 

But mostly the attributes are mentioned in cronological order so we can infer a relative date for attributes with missing dates (after date of the previous attribute).

This is the purpose of the following cell. It will create a new column called `place.date_inferred` which will recieve the an explicit date, if available or an inferred date. Another column called `place.date_is_inferred` with record if the date in `place.date_inferred` was inferred or not.

In [5]:
places_of_stay = entities_with_attribute(
    entity_type='person',
    show_elements=['name', 'groupname', 'the_line', 'the_order', 'extra_info'],
    the_type=[
        'jesuita-entrada',
        'partida',
        'chegada',
        'estadia',
        'estadia-x',
        'jesuita-votos-local',
        'jesuita-ordenacao-padre',
        'morte',
    ],
    column_name='place',
    db=db,
)

places_of_stay.place = places_of_stay.place.fillna('?')
places_of_stay = places_of_stay[places_of_stay.place != '?'].copy()

places_of_stay['id_col'] = places_of_stay.index
places_of_stay = places_of_stay.sort_values(by=['id_col', 'place.line'])

# Infer missing dates using the previous known date for each person
places_of_stay['place.date_inferred'] = places_of_stay['place.date'].replace('0', pd.NA)
places_of_stay['place.date_inferred'] = places_of_stay.groupby('id_col')['place.date_inferred'].ffill()
places_of_stay['place.date_is_inferred'] = places_of_stay['place.date_inferred'] != places_of_stay['place.date']
places_of_stay['place.date_inferred'] = places_of_stay['place.date_inferred'].fillna('')
places_of_stay['place.date_is_inferred'] = places_of_stay['place.date_inferred'] != places_of_stay['place.date']

places_of_stay.reset_index(inplace=True)
# if data_is_inferred set date_inferred to date_inferrred+">"
places_of_stay.loc[places_of_stay['place.date_is_inferred'], 'place.date_inferred'] = places_of_stay['place.date_inferred'] + '>'
places_of_stay['place.date_inferred'] = places_of_stay['place.date_inferred'].fillna('')
places_of_stay['place.date_inferred.formatted'] = places_of_stay['place.date_inferred'].apply(format_timelink_date)

places_of_stay.set_index('id_col', inplace=True)

places_of_stay.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6225 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             6225 non-null   object
 1   name                           6225 non-null   object
 2   groupname                      6225 non-null   object
 3   the_line                       6225 non-null   int64
 4   the_order                      6225 non-null   int64
 5   extra_info                     6225 non-null   object
 6   place.attr_id                  6225 non-null   object
 7   place.type                     6225 non-null   object
 8   place                          6225 non-null   object
 9   place.date                     6225 non-null   object
 10  place.line                     6225 non-null   int64
 11  place.level                    6225 non-null   int64
 12  place.groupname                6225 non-null   object
 13  place.obs                      6225 non-null   object
 14  place.extra_info               6225 non-null   object
 15  place.comment                  6134 non-null   object
 16  place.original                 223 non-null    object
 17  place.type.comment             1 non-null      object
 18  place.date.comment             1002 non-null   object
 19  place.date.original            12 non-null     object
 20  place.obs.original             1 non-null      object
 21  place.date_inferred            6225 non-null   object
 22  place.date_is_inferred         6225 non-null   bool
 23  place.date_inferred.formatted  6225 non-null   object
dtypes: bool(1), int64(4), object(19)
memory usage: 1.1+ MB

## Extract wikidata IDs from extra info

This will extract the wikidata id from the comments of attribute values

In [6]:
import pandas as pd

from dehergne_util import extract_wikidata_id

places_of_stay['wikidata_id'] = places_of_stay['place.extra_info'].apply(extract_wikidata_id, if_missing=pd.NA)
places_of_stay.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6225 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             6225 non-null   object
 1   name                           6225 non-null   object
 2   groupname                      6225 non-null   object
 3   the_line                       6225 non-null   int64
 4   the_order                      6225 non-null   int64
 5   extra_info                     6225 non-null   object
 6   place.attr_id                  6225 non-null   object
 7   place.type                     6225 non-null   object
 8   place                          6225 non-null   object
 9   place.date                     6225 non-null   object
 10  place.line                     6225 non-null   int64
 11  place.level                    6225 non-null   int64
 12  place.groupname                6225 non-null   object
 13  place.obs                      6225 non-null   object
 14  place.extra_info               6225 non-null   object
 15  place.comment                  6134 non-null   object
 16  place.original                 223 non-null    object
 17  place.type.comment             1 non-null      object
 18  place.date.comment             1002 non-null   object
 19  place.date.original            12 non-null     object
 20  place.obs.original             1 non-null      object
 21  place.date_inferred            6225 non-null   object
 22  place.date_is_inferred         6225 non-null   bool
 23  place.date_inferred.formatted  6225 non-null   object
 24  wikidata_id                    6077 non-null   object
dtypes: bool(1), int64(4), object(20)
memory usage: 1.2+ MB

In [7]:
def dataframe_overview(df, df_name="df", print_report=True):
    info_df = pd.DataFrame({
        '#': range(len(df.columns)),
        'Column': df.columns,
        'Non-Null Count': df.notna().sum().values,
        'Dtype': df.dtypes.astype(str).values,
    })

    info_df['Non-Null Count'] = info_df['Non-Null Count'].astype(str) + ' non-null'

    dtype_summary = df.dtypes.astype(str).value_counts().sort_index()
    dtype_text = ", ".join(f"{k}({v})" for k, v in dtype_summary.items())
    mem_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)

    if print_report:
        if len(df.index) > 0:
            try:
                idx_min, idx_max = df.index.min(), df.index.max()
            except TypeError:
                idx_min, idx_max = df.index[0], df.index[-1]
            print(f"{df_name} -> Index: {len(df)} entries, {idx_min} to {idx_max}")
        else:
            print(f"{df_name} -> Index: 0 entries")

        print(f"Data columns (total {df.shape[1]} columns):")
        print(info_df.to_markdown(index=False))
        print(f"\ndtypes: {dtype_text}")
        print(f"memory usage: {mem_mb:.2f} MB")

    return info_df, dtype_summary, dtype_text, mem_mb


# Example with current dataframe
info_df, dtype_summary, dtype_text, mem_mb = dataframe_overview(places_of_stay, "places_of_stay")

places_of_stay -> Index: 6225 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 25 columns):
|   # | Column                        | Non-Null Count   | Dtype   |
|----:|:------------------------------|:-----------------|:--------|
|   0 | id                            | 6225 non-null    | object  |
|   1 | name                          | 6225 non-null    | object  |
|   2 | groupname                     | 6225 non-null    | object  |
|   3 | the_line                      | 6225 non-null    | int64   |
|   4 | the_order                     | 6225 non-null    | int64   |
|   5 | extra_info                    | 6225 non-null    | object  |
|   6 | place.attr_id                 | 6225 non-null    | object  |
|   7 | place.type                    | 6225 non-null    | object  |
|   8 | place                         | 6225 non-null    | object  |
|   9 | place.date                    | 6225 non-null    | object  |
|  10 | place.line                    | 6225 non-null    | int64   |
|  11 | place.level                   | 6225 non-null    | int64   |
|  12 | place.groupname               | 6225 non-null    | object  |
|  13 | place.obs                     | 6225 non-null    | object  |
|  14 | place.extra_info              | 6225 non-null    | object  |
|  15 | place.comment                 | 6134 non-null    | object  |
|  16 | place.original                | 223 non-null     | object  |
|  17 | place.type.comment            | 1 non-null       | object  |
|  18 | place.date.comment            | 1002 non-null    | object  |
|  19 | place.date.original           | 12 non-null      | object  |
|  20 | place.obs.original            | 1 non-null       | object  |
|  21 | place.date_inferred           | 6225 non-null    | object  |
|  22 | place.date_is_inferred        | 6225 non-null    | bool    |
|  23 | place.date_inferred.formatted | 6225 non-null    | object  |
|  24 | wikidata_id                   | 6077 non-null    | object  |

dtypes: bool(1), int64(4), object(20)
memory usage: 8.87 MB

### Preview sample

Show place names of people in the Dehergne repertoire, avoiding the people "referred to" in the individual biographies, and so keeping just the missionaries names. These are the people registred under the group name "n".

In [8]:
(
    places_of_stay[places_of_stay.groupname == 'n'][PREVIEW_COLS]
    .sort_values(by=['place', 'place.date_inferred', 'name'])
    .sample(50)
 )

,place,wikidata_id,place.date_inferred.formatted,place.date_inferred,place.date_is_inferred,name,groupname,place.type,place.original,place.line
id_col,,,,,,,,,,
deh-jean-francois-gerbillon,Molsheim,Q22697,1682-12-16,16821216,False,Jean-François Gerbillon,n,jesuita-ordenacao-padre,None,445
deh-pierre-foureau,Pequim,Q956,1735,1735,False,Pierre Foureau,n,estadia,None,1584
deh-alessandro-fillippucci,Macau,Q14773,1663,1663,False,Alessandro Fillippucci,n,estadia,None,1106
deh-andre-pereira,Macau,Q14773,1716-08-31,17160831,False,André Pereira,n,chegada,None,529
deh-miguel-vieira,Goa,Q1171,>1713,>1713,False,Miguel Vieira,n,estadia,None,1343
deh-aloys-kao,Paris (colégio Louis-le-Grand),Q90,>1751-01-07,>17510107,False,Aloys Kao,n,estadia,None,73
deh-giuseppe-candone,Macau,Q14773,1678->0,1678>,True,Giuseppe Candone,n,partida,None,234
deh-andre-pereira,Cantão,Q16572,1722,17220000,False,André Pereira,n,estadia,None,531
deh-jacques-niva-ni,Macau,Q14773,1638-10-26,16381026,False,Jacques Niva Ni,n,morte,None,110
deh-joseph-francois-tissanier,Macau,Q14773,1688-12-24,16881224,False,Joseph François Tissanier,n,morte,None,845
deh-joseph-labbe,Cantão,Q16572,1717-02-02,17170202,False,Joseph Labbe,n,jesuita-votos-local,None,59
deh-pierre-de-goville,Versailles,Q621,1725-02-02,17250202,False,Pierre de Goville,n,estadia,None,1177
deh-joao-duarte,Hunan,Q45761,1703,17030000,False,João Duarte,n,estadia,None,932
deh-jose-pereira,Shanghai,Q8686,1724,17240000,False,José Pereira,n,estadia,None,757
deh-pedro-de-meireles,Lisboa,Q597,1699-07-15,16990715,False,Pedro de Meireles,n,jesuita-entrada,None,1264
deh-onofrio-villiani,China,Q148,>,>,True,Onofrio Villiani,n,estadia,None,1531
deh-conrad-terpilowski,Vilnius,Q216,1672-08-11,16720811,False,Conrad Terpiłowski,n,jesuita-entrada,Vilna,557
deh-manuel-teixeira,Goa,Q1171,1560,15600000,False,Manuel Teixeira,n,jesuita-ordenacao-padre,None,455
deh-michel-trigault,Kiangchow,Q1197219,1660,16600000,False,Michel Trigault,n,estadia,None,1001
deh-amador-fernandes,"[No mar, a caminho da China]",<NA>,,00,False,Amador Fernandes,n,morte,None,265
deh-jean-testard,Hou-tcheou fou,Q42664,1718,17180000,False,Jean Testard,n,morte,None,599
deh-joao-simoes,Macau,Q14773,1747-07-02,17470702,False,João Simões,n,chegada,None,1583
deh-isidoro-lucci,Tonquim,Q622778,1719-11-04,17191104,False,Isidoro Lucci,n,morte,None,1830
deh-jean-etienne-kao,Macau,Q14773,1746,17460000,False,Jean-Etienne Kao,n,estadia,None,160
deh-charles-francois-xavier-de-brevedent,"Barko, Etiópia",Q218861,1699-07-09,16990709,False,Charles-François Xavier de Brévedent,n,morte,None,1376
deh-paul-banhes-wan,Hukwang,Q2235155,1689,16890000,False,Paul Banhes Wan,n,estadia,None,191
deh-nicolas-marie-roy,"Lao chan oua, Hou-kouang",<NA>,1759-08-15,17590815,False,Nicolas-Marie Roy,n,jesuita-votos-local,None,1910
deh-jose-montanha-ii,Coimbra,Q45412,1753,17530000,False,José Montanha,n,estadia,None,1812
deh-antoine-de-beauvollier,Roma,Q220,1706-10-17,17061017,False,Antoine de Beauvollier,n,partida,None,776
deh-paul-banhes-wan,Kwangtung,Q15175,1691-07-02,16910000>,True,Paul Banhes Wan,n,estadia,None,193
deh-louis-fan,Macau,Q14773,1720,1720,False,Louis Fan,n,estadia,None,160
deh-xavier-duarte,"Rufinella, Itália",Q3558780,1775,17750000,False,Xavier Duarte,n,estadia,None,997
deh-joao-mourao,Macau,Q14773,1700,17000000,False,João Mourão,n,chegada,None,2366
deh-miguel-vieira,Lisboa,Q597,1702-09-12,17020912,False,Miguel Vieira,n,jesuita-entrada,None,1336
deh-jean-francois-gerbillon,Brest,Q12193,1685-03-03,16850303,False,Jean-François Gerbillon,n,estadia,None,416
deh-pierre-bonet,[A caminho da China],<NA>,1707,17070000,False,Pierre Bonet,n,estadia,None,994
deh-giovanni-antonio-grassi,Georgetown (colégio),Q1468648,1812-08-15,18120815,False,Giovanni Antonio Grassi,n,jesuita-votos-local,None,1355
deh-wenzel-paleczeck,China,Q148,1738,17380000,False,Wenzel Paleczeck,n,chegada,None,191
deh-tristano-attimis,"Tch'ang-chou, Changshu (igreja de Tong ko)",Q113497198,1747-12-11,17471211,False,Tristano Attimis,n,estadia,None,1381
deh-lodovico-buglio,Pequim,Q956,1682-10-07,16821007,False,Lodovico Buglio,n,morte,None,1619
deh-francisco-xavier-rosario-ho,Cantão,Q16572,1691-03,16910300,False,Francisco Xavier Rosario Ho,n,jesuita-ordenacao-padre,None,1706
deh-bartolomeu-de-roboredo,Índia,Q668,1635,1635,False,Bartolomeu de Roboredo,n,estadia,None,709
deh-antonio-francisco-cardim,Goa,Q1171,1621-02-01,16210201,False,António Francisco Cardim,n,jesuita-ordenacao-padre,None,387
deh-miguel-monteiro,Macau,Q14773,1657-02-05,16570205,False,Miguel Monteiro,n,jesuita-votos-local,None,1960
deh-pierre-faure,ilhas Nicobar,Q157286,1711-01-05,17110105>,True,Pierre Faure,n,estadia,None,225
deh-sabatino-de-ursis,Pequim,Q956,1617-03-18,16170318,False,Sabatino De Ursis,n,estadia,None,419
deh-jean-baborier,Hukwang,Q2235155,1716-08-15,17160800>,True,Jean Baborier,n,estadia,None,50
deh-francois-noel,Roma,Q220,1708,17080000,False,François Noël,n,estadia,None,216
deh-francisco-de-lagea,"Namyung (Nan-hiong), Kwangtung",Q934465,1645,1645,False,Francisco de Lagea,n,estadia,None,267
deh-antonio-da-costa-iii,Macau,Q14773,1700,1700,False,António da Costa,n,estadia,None,2242

## Save enriched datasets

In [9]:
(
    places_of_stay[PREVIEW_COLS]
    .sort_values(by=['place', 'place.date_inferred'])
    .to_excel('../inferences/locations_places_of_stay.xlsx', sheet_name='wikidata', index=True)
 )

(
    places_of_stay[['place', 'place.date_inferred.formatted', 'name', 'place.type', 'place.original']]
    .sort_values(by=['place', 'place.date_inferred.formatted'])
    .to_excel('../inferences/locations_names_places_dates_only.xlsx', sheet_name='locations', index=True)
 )

(
    places_of_stay['wikidata_id']
    .dropna()
    .drop_duplicates()
    .to_csv('../inferences/wikidata-references/locations_wikidata_ids.csv', index=False)
 )

## Locations missing wikidata IDs

In [10]:
places_without_wikidata = places_of_stay[
    places_of_stay['wikidata_id'].isna()
    & ~places_of_stay['place'].astype(str).str.startswith('[')
].copy()

(
    places_without_wikidata[PREVIEW_COLS]
    .sort_values(by=['place', 'place.date_inferred'])
    .sample(60)
 )

,place,wikidata_id,place.date_inferred.formatted,place.date_inferred,place.date_is_inferred,name,groupname,place.type,place.original,place.line
id_col,,,,,,,,,,
deh-antonio-posateri,Chang-si,<NA>,1691->0,1691>,True,Antonio Posateri,n,estadia,None,1836
deh-etienne-faber,"Siao-tchai de Han-tchong, Shensi",<NA>,1657-05-10,16570510,False,Etienne Faver,n,morte,None,52
deh-dionisio-ferreira,"Ko-li-tsem do Kiating, Kiangnan",<NA>,1753-12-08,17531208,False,Dionísio Ferreira,n,estadia,None,720
deh-simao-da-silveira,Aquilon,<NA>,1709-03-11,17090311>,True,Simão da Silveira,n,estadia,None,1443
deh-nicolas-marie-roy,"Lao chan oua, Hou-kouang",<NA>,1759-08-15,17590815,False,Nicolas-Marie Roy,n,jesuita-votos-local,None,1910
deh-manuel-da-motta,"U cham fu, Hou-kouang",<NA>,1767-12-13,17671213,False,Manuel da Motta,n,jesuita-votos-local,None,2336
deh-joao-barradas,Rio Kan,<NA>,1594,15940000,False,João Barradas,n,morte,None,356
deh-manswet-skokowski,Mscislaviae,<NA>,1798-02-08,17980208,False,Manswet Skokowvski,n,morte,None,1751
deh-louis-joseph-le-febure,San kiao hou kia,<NA>,1741-03-19,17410319,False,Louis-Joseph Le Febure,n,jesuita-votos-local,None,884
deh-magnani-ref1,Czerczerse,<NA>,1794-04-21,17940421,False,Agostino Magnani,referido,morte,None,340
deh-miguel-vieira,Aquilon,<NA>,>1713->0,>1713>,True,Miguel Vieira,n,estadia,None,1346
deh-mathurin-lamathe,"Chang-tsin do Yüansi, Hou-pei",<NA>,1786-12-03,17861203,False,Mathurin Lamathe,n,morte,None,355
deh-gaspar-coelho,"Kasuza, Arima, Japão",<NA>,1590-05-25,15900525,False,Gaspar Coelho,n,morte,None,1763
deh-giulio-aleni,"Yean-sam, perto do monte chamado da Cruz, Yenp...",<NA>,1649-06-10,16490610,False,Giulio Aleni,n,morte,None,422
deh-gottfried-xaver-von-laimbeckhoven,Wouho,<NA>,1772,1772,False,Gottfried Xaver von Laimbeckhoven,n,estadia,None,321
deh-paulo-de-campos,"Ké Diet, Tonquim",<NA>,1754-08-15,17540815,False,Paulo de Campos,n,jesuita-votos-local,None,216
deh-pieter-thomas-van-hamme,"Tarahumaras, México",<NA>,1689,1689,False,Pieter Thomas van Hamme,n,estadia,None,494
deh-manuel-jose-ref2,Ascitano,<NA>,1765,17650000,False,Emmanuel Josephus,referido,morte,None,237
deh-inacio-francisco,"«in Tum cheu missionis Kim tum», au T'ong-tche...",<NA>,1767-11-04,17671104,False,Inácio Francisco,n,jesuita-votos-local,None,1664
deh-nicolas-zarate,Maxagongdong,<NA>,1725,17250000,False,Nicolás Zárate,n,estadia,None,73
deh-dionisio-ferreira,"Ko-li-tsem do Kiating, Kiangnan",<NA>,1745,1745,False,Dionísio Ferreira,n,estadia,None,719
deh-johann-siebert,"Sinhoua, Hué",<NA>,1741-05-28,17410528,False,Johann Siebert,n,jesuita-votos-local,None,1079
deh-etienne-yang,"Pé-pou, Linkiang fou",<NA>,1787-05,17870500,False,Etienne Yang,n,estadia,None,31
deh-francisco-xavier-rosario-ho,Yuwei do Shansi,<NA>,1727,1727,False,Francisco Xavier Rosario Ho,n,estadia,None,1700
deh-pierre-tchen,Choui tcheou San Kia (capela da Beata Virgem M...,<NA>,1745-09-08,17450908,False,Pierre T'chen,n,jesuita-votos-local,None,263
deh-martim-correa,Sum Kiam (casa de um cristão),<NA>,1732-08-03,17320803,False,Martim Correa,n,jesuita-votos-local,None,2071
deh-aloys-moriz,Tonkosz,<NA>,1805-01-24,18050124,False,Aloys Moriz,n,morte,None,2084
deh-manuel-da-mata,17010220,<NA>,1722-07-02,17220000>,True,Manuel da Mata,n,jesuita-votos-local,None,1073
deh-joao-barradas-ref1,rio Kan,<NA>,1594,15940000,False,Matteo Ricci,referido,estadia,None,361
deh-joao-duarte,Sian tan hien,<NA>,1706-08-15,17060815,False,João Duarte,n,jesuita-votos-local,None,941
deh-charles-dolze,«apud Sinas»,<NA>,1699-02-02,16990202,False,Charles Dolzé,n,jesuita-votos-local,None,714
deh-romain-hinderer,Lofeu,<NA>,1722-12-28,17221228,False,Romain Hinderer,n,estadia,None,333
deh-mathurin-lamathe,"Chayüankow, Hukwang",<NA>,1759-04-01,17590401,False,Mathurin Lamathe,n,jesuita-votos-local,None,354
deh-francesco-pasio,"Katsusa, Japão",<NA>,1591-07-01,15910701,False,Francesco Pasio,n,jesuita-votos-local,None,430
deh-filippo-felice-carrocci,«Ponti (in valle Tellina),<NA>,1685-02-02,16850202,False,Filippo-Felice Carrocci,n,jesuita-votos-local,None,620
deh-joseph-louis-desrobert,"Pé-tsiuen-chan, Hukwang",<NA>,1737-08-22,17370822>,True,Joseph-Louis Desrobert,n,estadia,None,361
deh-julien-placide-hervieu,À missão,<NA>,1701-09-16,17010916,False,Julien-Placide Hervieu,n,chegada,None,263
deh-pierre-amys,Moulins,<NA>,1689-02-02,16890202,False,Pierre Amys,n,jesuita-votos-local,None,1089
deh-joseph-saraiva-chen,Leou-kia-tchouang do Chou-lou hien,<NA>,1744-06-07,17440607,False,Joseph Saraiva Chen,n,jesuita-votos-local,None,436
deh-gottfried-xaver-von-laimbeckhoven,« Pe tsien schan »,<NA>,1740-02-02,17400202,False,Gottfried Xaver von Laimbeckhoven,n,jesuita-votos-local,None,328
deh-maur-tsao,Tcha-yuen-keou,<NA>,1759-03-26,17590326,False,Maur Ts'ao,n,jesuita-votos-local,None,1132
deh-romain-hinderer,Lofeu,<NA>,1723-04-14,17230414,False,Romain Hinderer,n,estadia,None,336
deh-juan-miguel-de-irigoyen,"Monzei, Filipinas",<NA>,1699-10-13,16991013,False,Juan Miguel de Irigoyen,n,morte,None,186
deh-melchior-mora,"Katsusa, Japão",<NA>,1591-06-30,15910630,False,Melchior Mora,n,jesuita-votos-local,None,2008
deh-tome-vaz,Missão dos Rios de Cuama,<NA>,1664->0,1664>,True,Tomé Vaz,n,estadia,None,757
deh-pieter-thomas-van-hamme,"Tarahumaras, México",<NA>,1684,1684,False,Pieter Thomas van Hamme,n,estadia,None,493
deh-adrien-grelon,"« Pe-chieh » du Sinfeng, Kiangsi",<NA>,1696-03-03,16960303,False,Adrien Grelon,n,morte,None,1441
deh-germain-macret,"Zumbae, Tchamp-pa",<NA>,1659,16590000,False,Germain Macret,n,estadia,None,93
deh-manuel-de-carvalho,"Làngòi, Tonquim",<NA>,1741-11-12,17411112,False,Manuel de Carvalho,n,jesuita-votos-local,None,743
deh-antonio-jose-henriques,Tongko (casa de Philippe Wang),<NA>,1747-12-21,17471221,False,António-José Henriques,n,estadia,None,134
deh-pierre-quenein,Oriente,<NA>,1696,16960000,False,Pierre Quenein,n,estadia,None,72
deh-gottfried-xaver-von-laimbeckhoven,T'ang-kia-hiang,<NA>,1787-05-22,17870522,False,Gottfried Xaver von Laimbeckhoven,n,morte,None,329
deh-joseph-henry-marie-de-premare,Residência francesa «Vuen ngan juxta murum qui...,<NA>,1714-07-02,17140000>,True,Joseph Henry-Marie de Prémare,n,estadia,None,1906
deh-felix-da-rocha,Petit Tibet «Kinchuen»,<NA>,1774,1774,False,Félix da Rocha,n,estadia,None,807
deh-baltasar-caldeira,Mogor,<NA>,>,>,True,Baltasar Caldeira,n,estadia,None,148
deh-louis-marie-dugad,"Pe-tsien-chan, China",<NA>,1740-08-15,17400815,False,Louis-Marie Dugad,n,jesuita-votos-local,None,1084
deh-cyr-contancin,Shaohing,<NA>,1706-01-14,17060114,False,Cyr Contancin,n,jesuita-votos-local,None,1926
deh-manuel-rodrigues-ii-ref4,"Hirubale, Misore",<NA>,1675-08-15,16750815,False,Emanuel Rodriguez,referido,jesuita-votos-local,"« Kubale (Hirubale?, le mot est peu lisible), ...",1415
deh-leon-pascal-baron,"Petsiuenchan, Houkouang (Oratório)",<NA>,1771-08-15,17710815,False,Léon-Pascal Baron,n,jesuita-votos-local,None,342
deh-felix-da-rocha,Petit Tibet «Kinchuen»,<NA>,1777,1777,False,Félix da Rocha,n,estadia,None,808

In [11]:
(
    places_without_wikidata[PREVIEW_COLS]
    .sort_values(by=['place', 'place.date_inferred'])
    .to_excel('../inferences/wikidata-references/locations_names_no_wikidata.xlsx', sheet_name='no_wikidata', index=True)
 )


## Important

For this to work make sure that notebook `wikidata-linked-data.ipynb` has been run. It will read the wikidate exported above to `../inferences/wikidata-references/` and fetch the information of each location to locations_wikidata_info.xlsx which is used in the next cell to provide extra information about each location

## Frequency of places

### Merge places with wikidata information

In [12]:
# get information about wikidata locations. See notebooks/wikidata-linked-data.ipynb for how this file was created
locations_wikidata_info = pd.read_excel(
    "../inferences/wikidata-references/locations_wikidata_info.xlsx"
)

# Normalize join keys
locations_wikidata_info["wikidata_id"] = locations_wikidata_info["wikidata_id"].astype("string").str.strip()
places_of_stay["wikidata_id"] = places_of_stay["wikidata_id"].astype("string").str.strip()

# Ensure many-to-one join (one row per wikidata_id on lookup table)
locations_wikidata_info = locations_wikidata_info.drop_duplicates(subset=["wikidata_id"], keep="first")

# Left join: keep all rows from places_of_stay and copy columns from locations_wikidata_info
places_of_stay = (
    places_of_stay.reset_index()
    .merge(
        locations_wikidata_info,
        how="left",
        left_on="wikidata_id",
        right_on="wikidata_id",
        suffixes=("", "_wikidata"),
    )
    .set_index("id_col")
)

places_of_stay.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6225 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 41 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              6225 non-null   object
 1   name                            6225 non-null   object
 2   groupname                       6225 non-null   object
 3   the_line                        6225 non-null   int64
 4   the_order                       6225 non-null   int64
 5   extra_info                      6225 non-null   object
 6   place.attr_id                   6225 non-null   object
 7   place.type                      6225 non-null   object
 8   place                           6225 non-null   object
 9   place.date                      6225 non-null   object
 10  place.line                      6225 non-null   int64
 11  place.level                     6225 non-null   int64
 12  place.groupname                 6225 non-null   object
 13  place.obs                       6225 non-null   object
 14  place.extra_info                6225 non-null   object
 15  place.comment                   6134 non-null   object
 16  place.original                  223 non-null    object
 17  place.type.comment              1 non-null      object
 18  place.date.comment              1002 non-null   object
 19  place.date.original             12 non-null     object
 20  place.obs.original              1 non-null      object
 21  place.date_inferred             6225 non-null   object
 22  place.date_is_inferred          6225 non-null   bool
 23  place.date_inferred.formatted   6225 non-null   object
 24  wikidata_id                     6077 non-null   string
 25  chinese_label                   6034 non-null   object
 26  english_label                   6077 non-null   object
 27  portuguese_label                5708 non-null   object
 28  english_description             6055 non-null   object
 29  chinese_description             5691 non-null   object
 30  portuguese_description          4941 non-null   object
 31  coordinates                     5859 non-null   object
 32  latitude                        5859 non-null   float64
 33  longitude                       5859 non-null   float64
 34  administrative_entity_id        5125 non-null   object
 35  administrative_entity_label_en  5124 non-null   object
 36  administrative_entity_label_zh  4991 non-null   object
 37  country_id                      5995 non-null   object
 38  country_label                   5995 non-null   object
 39  label                           4664 non-null   object
 40  administrative_entity_type      1413 non-null   object
dtypes: bool(1), float64(2), int64(4), object(33), string(1)
memory usage: 2.0+ MB

### Show sample records

In [13]:
cols = [ 'name', 'place', 'place.type','portuguese_label','chinese_label','label','country_label','wikidata_id','english_description', 'administrative_entity_id', 'administrative_entity_label_en']
places_of_stay[cols].sample(10)

,name,place,place.type,portuguese_label,chinese_label,label,country_label,wikidata_id,english_description,administrative_entity_id,administrative_entity_label_en
id_col,,,,,,,,,,,
deh-simon-xavier-a-cunha-wou-li,Simon-Xavier a Cunha Wou Li,Shanghai,estadia,Xangai,上海市,Shanghai / 上海市,People's Republic of China,Q8686,provincial-level municipality in China,Q148,People's Republic of China
deh-etienne-joseph-le-couteulx,Etienne-Joseph Le Couteulx,Hankow,estadia,NaN,汉口,Hankou / 汉口,Republic of China,Q1208250,"former town, now part of Wuhan",Q13426199,Republic of China
deh-jean-francois-foucquet,Jean-François Foucquet,Port-Louis,estadia,Port-Louis,路易港,Port-Louis / 路易港,France,Q128223,"commune in Morbihan, France",Q178875,canton of Port-Louis
deh-antoine-thomas,Antoine Thomas,Namur,estadia,Namur,那慕爾,Namur / 那慕爾,Belgium,Q134121,"capital of Wallonia, Belgium",Q93782,Arrondissement of Namur
deh-afonso-aires,Afonso Aires,"[No mar, depois do Cabo da Boa Esperança]",morte,Cabo da Boa Esperança,好望角,Cape of Good Hope / 好望角,South Africa,Q4092,"headland of Cape Peninsula, South Africa",Q127167,Western Cape
deh-jean-francois-pelisson,Jean-François Pélisson,Toulouse,morte,Toulouse,圖盧茲,Toulouse / 圖盧茲,France,Q7880,"French commune and city in Haute-Garonne, Occi...",Q12538,Haute-Garonne
deh-houang-francisco-martins,Houang Francisco Martins,Shiuchow,estadia,NaN,曲江区,Qujiang District / 曲江区,People's Republic of China,Q1346617,"district in Guangdong, People's Republic of China",Q59107,Shaoguan
deh-pedro-de-alcacova,Pedro de Alcáçova,Japão,estadia,Japão,日本,Japan / 日本,Japan,Q17,island country in East Asia,NaN,NaN
deh-joao-de-borgia-kouo,João de Borgia Kouo,Macau,morte,Macau,澳門,NaN,People's Republic of China,Q14773,city and special administrative region of China,Q148,People's Republic of China
deh-giuseppe-baudino-ref1,K'ang Hi,Sul da China,estadia,China,中华人民共和国,People's Republic of China / 中华人民共和国,People's Republic of China,Q148,country in East Asia,NaN,NaN

In [14]:
df_totals = (
    places_of_stay.reset_index()
    .groupby(['portuguese_label','chinese_label','english_label'])
    .agg(id_unique=('id_col', 'nunique'), first_date=('place.date_inferred', 'min'), last_date=('place.date_inferred', 'max'))
    .sort_values('id_unique', ascending=False)
)

df_totals.head(100)

,,,id_unique,first_date,last_date
portuguese_label,chinese_label,english_label,,,
Macau,澳門,Macau,476,1561,>1652
Pequim,北京市,Beijing,253,00,>17410115
Goa,果阿邦,Goa,223,00,>1713
Cantão,广州市,Guangzhou,204,1555,>16590123
China,中华人民共和国,People's Republic of China,184,15540000,>
Lisboa,里斯本,Lisbon,150,1546,>
Roma,罗马,Rome,113,15480311,>16851112
Coimbra,科英布拉,Coimbra,79,15420000,<16230324
Paris,巴黎,Paris,72,1527,>17510107
Nanquim,南京市,Nanjing,66,15950521,>1648>
Japão,日本,Japan,63,15490815,>
Tonkin,東京,Tonkin,58,16230000,>
Índia,印度,India,58,15510000,>
Tailândia,泰國,Thailand,55,1568,>
Hangzhou,杭州市,Hangzhou,52,1611,>1636
Xangai,上海市,Shanghai,51,1610,17460000>
Cochinchina,交趾支那,Cochinchina,47,16190000,>
Huguang,湖廣省,Huguang,46,1619,>1666:<1685
Lorient,洛里昂,Lorient,43,17321110,17750627
Nanchang,南昌市,Nanchang,43,15911100>,>
Évora,埃武拉,Évora,40,15451225,>1707:<17160314
Jiangxi,江西省,Jiangxi,37,1621,>1659
Hainan,海南省,Hainan,36,15601100,>1659:<1660
Manila,马尼拉市,Manila,32,15810900,>16850206
Malaca,马六甲市,Malacca,32,15480000,>
Europa,欧洲,Europe,29,1573,>1773
Filipinas,菲律賓,Philippines,26,15420000,<1682
Fuzhou,福州市,Fuzhou,23,16300000,>1626:1631
França,法國,France,23,16810000>,>17390000
Portugal,葡萄牙,Portugal,23,15480613,17820500
Nagasaki,长崎市,Nagasaki,22,15830725,16430322
Bordéus,波尔多,Bordeaux,22,16540830,>
Moscovo,莫斯科,Moscow,22,16850000,>
Tartária,韃靼利亞,Tartary,21,16820323,>
Ganzhou,赣州市,Ganzhou,21,1657,>1660
Cochim,科契,Kochi,20,15540416,>16240325
Vannes,瓦讷,Vannes,20,16540000,16541000
Fujian,福建省,Fujian,19,16110000,17550000>
Cantão,广东省,Guangdong,19,15551123,>1701
México,墨西哥,Mexico,19,15380000,>
Xiamen,厦门市,Xiamen,18,16780600,1702>
Xian,西安市,Xi'an,18,1625,17120000
Brest,布雷斯特,Brest,18,1685030,17141201
Itália,意大利,Italy,18,17590000>,>
Pérsia,波斯,Persian Empire,15,16130209>,<1701
Avinhão,亞維農,Avignon,15,16150926,17671113
Nancy,南锡,Nancy,15,16270929,17510827
Suzhou,苏州市,Suzhou,15,1660,17590000
Nápoles,那不勒斯,Naples,14,15560120,18060420
Landsberg am Lech,莱希河畔兰茨贝格,Landsberg am Lech,14,16230729,17770411
Shaanxi,陕西省,Shaanxi,14,1619,1698
Sanchoão,上川岛,Shangchuan Island,14,1552,17010807
Viena,維也納,Vienna,14,16271016,17880000
Moçambique,莫桑比克,Mozambique,14,15840000>,17490705
Génova,热那亚,Genoa,13,16390915,17680930
Foshan,佛山市,Foshan,13,16810000>,>
Camboja,柬埔寨,Cambodia,13,16160000,>
Kaifeng,開封市,Kaifeng,12,1607,1722
Lyon,里昂,Lyon,12,16160500>,17310116
Saint-Malo,圣马洛,Saint-Malo,12,17010905,17301210
Zhejiang,浙江省,Zhejiang,12,16171002,>1710
Shanxi,山西省,Shanxi,12,1626,>1666:<1685
Jinan,济南市,Jinan,11,1636,>1660
Henan,河南省,Henan,11,1630>,17660000
Ningbo,宁波市,Ningbo,11,1627,17480000
Tréveris,特里尔,Trier,11,16770821,17730228
Zhaoqing,肇庆市,Zhaoqing,11,15820000,16560917
Isfahan,伊斯法罕,Isfahan,10,1651,17470000
Mechelen,梅赫伦,Mechelen,10,16341015,16720424
Shandong,山東省,Shandong,10,1628>,1711
La Rochelle,拉罗谢尔,La Rochelle,10,16420200,17090202
Jiading,嘉定區,Jiading,9,16190715>,>1616
Port-Louis,路易港,Port-Louis,9,16980221,17670315
Península de Liaodong,辽东半岛,Liaodong Peninsula,9,16820323,17430000
Brasil,巴西,Brazil,9,16531014>,>
Nanxiong,南雄市,Nanxiong,9,16070427,>
Toulouse,圖盧茲,Toulouse,9,1642,>1642
Milão,米蘭,Milan,9,16160614,17170000
Batávia (região),巴达维亚,Batavia,9,16420000,>
Tournai,图尔奈,Tournai,9,15960705,16960929
Mysore,迈索尔,Mysore,8,16231013>,>
Madurai,马杜赖,Madurai,8,16390000,17141102
Guangxi,广西壮族自治区,Guangxi,8,16500000,>1708
Douai,杜埃,Douai,8,15941109,1678
Agra,阿格拉,Agra,8,16021029,>
Istambul,伊斯坦堡,Istanbul,8,1662>,1723
Marselha,马赛,Marseille,8,16370607,17250104
Guilin,桂林市,Guilin,8,1587,17280000
Alcalá de Henares,埃纳雷斯堡,Alcalá de Henares,7,15550925,1690
Concepción,康塞普西翁,Concepción,7,17040513,17110000
Chennai,金奈,Chennai,7,1692,>
Hubei,湖北省,Hubei,7,17120000,1778
Huai’an,淮安市,Huai'an,7,1659,1706
Arménia,亞美尼亞,Armenia,7,16800000,>1689
Bengala,孟加拉,Bengal,7,1576,>1661
Chongming,崇明区,Chongming District,7,1677,17781113
Londres,倫敦,London,6,17031004,17050000
Países Baixos,荷蘭,Netherlands,6,16740000>,>
Jiujiang,九江市,Jiujiang,6,17000000,17210000
Lovaina,鲁汶,Leuven,6,16050000,>

In [15]:
df_totals.to_excel('../inferences/locations_totals.xlsx', sheet_name='totals', index=True)

### By country or region

In [16]:
df_countries = (
    places_of_stay.reset_index()
    .groupby(['country_label'])
    .agg(id_unique=('id_col', 'nunique'), first_date=('place.date_inferred', 'min'), last_date=('place.date_inferred', 'max'))
    .sort_values('id_unique', ascending=False)
)

df_countries

                            id_unique first_date        last_date
country_label
People's Republic of China        887         00        >17410115
India                             322         00            >1713
Portugal                          264   15420000  >1707:<17160314
France                            238       1527        >17510107
Italy                             195   15370624        >16851112
Vietnam                            94   16190000                >
Qing dynasty                       91       1619            >1710
Japan                              78   15490815                >
Thailand                           56       1568                >
Philippines                        48   15420000        >16850206
Germany                            39  16160500>         17770411
Malaysia                           34   15480000                >
Spain                              33   15380000                >
Belgium                            32   15960705                >
Duchy of Moscow                    22   16850000                >
Mexico                             19   15380000                >
Austria                            17   16271016         17880000
Turkey                             17       1650            >1699
Mozambique                         16  15761230>         17490705
Indonesia                          16  15420000>                >
Duchy of Lorraine                  15   16270929         17510827
Netherlands                        14   16420000                >
Iran                               13       1651         17470000
Cambodia                           13   16160000                >
Brazil                             12       1641         17640516
Poland                             11   16310816                >
Portuguese Empire                  11         00                >
Syria                              10       1639         17151005
Czech Republic                     10   16060000                >
Armenia                             9   16800000            >1689
British Raj                         9       1576            >1661
Belarus                             9   16900815         18050114
Chile                               8  17031226>            >1702
Russia                              7  16840000>                >
United States                       7       1568         18120815
Peru                                7   15680711            >1702
Kingdom of Italy                    6       1648         17140202
United Kingdom                      6   16870000                >
Sri Lanka                           6   15520000         16550621
Kingdom of the Netherlands          6  16740000>                >
Republic of China                   6       1702         17460000
Roman Empire                        6   17031004         17050000
Nepal                               5  16250000>            >1661
South Africa                        5   16570000         17200315
Myanmar                             4     000000         16890000
Canada                              4   16470814        1730:1739
Morocco                             4       1578         15840000
Pakistan                            3       1598             1655
Lithuania                           3   16180531         16720811
Egypt                               2  16130209>         16970000
Greece                              2       1685             1693
Kingdom of Poland                   2   16980202         17050126
Ecuador                             2   17010508                >
Kingdom of Aragon                   2   16740613         16771115
Argentina                           2   17110501         17280817
Dutch East Indies                   2   16241000         17250000
São Tomé and Príncipe               2       1605            1693>
Croatia                             2   15811100         17410801
Slovakia                            1   17291027         17291027
Romania                             1  16710121>        16710121>
Sweden                              1   17080120         17080120
Switzerland                         1   17130202         17130202
Taiwan                              1   17100000         17100000
Three Kingdoms of Korea             1       1640             1640
Tsardom of Russia                   1   18050326         18050326
Abbasid Caliphate                   1       1659             1659
Paraguay                            1          >                >
Norway                              1  16530000>         16530831
Angola                              1       1681             1681
Azerbaijan                          1   17211218         17211218
Bolivia                             1   16260307         16260307
Champa                              1          >                >
Cuba                                1      1572>            1572>
Dominican Republic                  1   17180000         17180000
Ethiopia                            1   16990709         16990709
Guinea                              1   17040523         17040523
Hungary                             1   16800930         16800930
Kazakhstan                          1       1688             1688
Kingdom of Hungary                  1   17340000         17340000
Kingdom of Romania                  1   17690000         17850108
Afghanistan                         1   17000000         17000000
Latvia                              1   17920528         17920528
Lebanon                             1   16950000         16960000
Ming dynasty                        1       1607             1607
Mughal Empire                       1   17050000         17050000
Kyrgyzstan                          1  <16031100        <16031100

In [17]:
df_countries.to_excel('../inferences/locations_countries.xlsx', sheet_name='countries', index=True)

## Analysis of name variations

In [18]:
df_variations = (
    places_of_stay.reset_index()
    .groupby(['country_label','portuguese_label','chinese_label','english_label','wikidata_id','place'])
    .agg(id_unique=('id_col', 'nunique'), first_date=('place.date_inferred', 'min'), last_date=('place.date_inferred', 'max'))
)
df_variations.head(100)

                                                                                                                                      id_unique  \
country_label      portuguese_label           chinese_label english_label              wikidata_id place
Abbasid Caliphate  Coração                    呼罗珊           Khorasan                   Q2352322    Khorasan                                   1
Afghanistan        Afeganistão                阿富汗           Afghanistan                Q889        Afeganistão                                1
Angola             Angola                     安哥拉           Angola                     Q916        Angola                                     1
Argentina          Argentina                  阿根廷           Argentina                  Q414        Missão de Santa Ana, dos Guaranis          1
                   Buenos Aires               布宜諾斯艾利斯       Buenos Aires               Q1486       Buenos Aires                               1
Armenia            Arménia                    亞美尼亞          Armenia                    Q399        Arménia                                    6
                                                                                                   Arménia (residência de Chamakii)           1
                   Erevã                      葉里溫           Yerevan                    Q1953       Yerevan                                    2
Austria            Graz                       格拉茨           Graz                       Q13298      Graz                                       2
                   Krems an der Donau         多瑙河畔克雷姆斯      Krems                      Q131266     Krems                                      1
                   Leoben                     萊奧本           Leoben                     Q485294     Leoben                                     2
                   Viena                      維也納           Vienna                     Q1741       Viena                                     14
Azerbaijan         Shamakhi                   沙馬基           Shamakhi                   Q388224     Shamakhi                                   1
Belarus            Bielorrússia               白俄羅斯          Belarus                    Q184        Rússia Branca                              4
                   Minsk                      明斯克           Minsk                      Q2280       Minsk                                      1
                   Polatsk                    波洛茨克          Polatsk                    Q200797     Polotsk                                    5
Belgium            Antuérpia                  安特卫普          Antwerp                    Q12892      Antuérpia                                  6
                   Bruges                     布鲁日           Bruges                     Q12994      Bruges                                     1
                   Bruxelas                   布鲁塞尔          City of Brussels           Q239        Bruxelas                                   5
                   Courtrai                   科特赖克          Kortrijk                   Q12995      Courtrai                                   2
                   Liège                      列日            Liège                      Q3992       Liège                                      1
                                                                                                   Liége                                      1
                   Lovaina                    鲁汶            Leuven                     Q118958     Leuven                                     6
                   Mechelen                   梅赫伦           Mechelen                   Q162022     Mechelen                                  10
                   Namur                      那慕爾           Namur                      Q134121     Namur                                      1
                   Oostende                   奥斯坦德          Ostend                     Q12996      Ostende                                    1
                   Região de Bruxelas-Capital 布鲁塞尔首都大区      Brussels-Capital Region    Q240        Bruxelas                                   2
                   Tournai                    图尔奈           Tournai                    Q173219     Tournai                                    9
Bolivia            Santa Cruz de la Sierra    圣克鲁斯-德拉谢拉     Santa Cruz de la Sierra    Q170688     Santa Cruz de la Sierra, Peru              1
Brazil             Bahia                      巴伊亚州          Bahia                      Q40430      Bahia                                      1
                                                                                                   Baía                                       1
                                                                                                   Baía, Brasil                               2
                                                                                                   [No mar, perto da Baía]                    1
                   Brasília                   巴西利亚          Brasília                   Q2844       Brasília                                   1
                   Maranhão                   马拉尼昂州         Maranhão                   Q42362      Maranhão, Brasil                           1
                   Olinda                     奧林達           Olinda                     Q28301      Olinda                                     1
                   Recife                     累西腓           Recife                     Q48344      Recife                                     2
                   Rio de Janeiro             里约热内卢         Rio de Janeiro             Q8678       Rio de Janeiro                             2
                   Salvador                   萨尔瓦多          Salvador                   Q36947      Salvador                                   1
British Raj        Bengala                    孟加拉           Bengal                     Q80338      Bengala                                    6
                                                                                                   Bengala (colégio «Hogulensi»)              1
                                                                                                   Bengala (universidade de Nadia)            1
                   Travancore                 特拉凡哥尔         Kingdom of Thiruvithamkoor Q150058     Travancore                                 2
Cambodia           Camboja                    柬埔寨           Cambodia                   Q424        Cambodja                                  13
Canada             Canadá                     加拿大           Canada                     Q16         Canadá                                     4
                   Quebec                     魁北克市          Quebec City                Q2145       Québec                                     1
Champa             Reino de Champa            占城            Champa                     Q216786     Tchampa                                    1
Chile              Cabo Horn                  合恩角           Cape Horn                  Q4078       Cabo Horn                                  5
                   Chile                      智利            Chile                      Q298        Chile                                      1
                   Concepción                 康塞普西翁         Concepción                 Q1880       Concépcion, Chile                          7
                   Santiago                   圣地亚哥          Santiago                   Q2887       Santiago do Chile                          1
Croatia            Požega                     波熱加           Požega                     Q273114     Požega                                     1
Cuba               Havana                     哈瓦那           Havana                     Q1563       Havana                                     1
Czech Republic     Boémia                     波希米亚          Bohemia                    Q39193      Boémia                                     2
                   Brno                       布尔诺           Brno                       Q14960      Brno                                       6
                   Olomouc                    奥洛莫乌茨         Olomouc                    Q81137      Olomouc                                    3
                   Praga                      布拉格           Prague                     Q1085       Praga                                      1
                                                                                                   Praga (colégio)                            1
                                                                                                   Praga, Boémia                              1
Dominican Republic São Domingos               圣多明各          Santo Domingo              Q34820      Santo Domingo                              1
Duchy of Lorraine  Nancy                      南锡            Nancy                      Q40898      Nancy                                     15
Duchy of Moscow    Moscovo                    莫斯科           Moscow                     Q649        Moscovo                                   22
Dutch East Indies  Batavia                    巴達維亞          Batavia                    Q1199713    Batavia                                    1
                                                                                                   Batávia                                    1
Ecuador            Equador                    厄瓜多尔          Ecuador                    Q736        [No mar, perto do Equador]                 1
                   Quito                      基多            Quito                      Q2900       Quito, Equador                             1
Egypt              Cairo                      開羅            Cairo                      Q85         Cairo                                      1
                   Egito                      埃及            Egypt                      Q79         Egipto                                     1
Ethiopia           Gondar                     貢德爾           Gondar                     Q218861     Barko, Etiópia                             1
France             Agen                       阿让            Agen                       Q6625       Agen                                       2
                   Aix-en-Provence            普罗旺斯地区艾克斯     Aix-en-Provence            Q47465      Aix                                        2
                                                                                                   Aix-en-Provence                            1
                   Ajaccio                    阿雅克肖          Ajaccio                    Q40104      Ajaccio, Córsega                           1
                   Angoulême                  昂古莱姆          Angoulême                  Q134346     Angoulême                                  1
                   Anjou                      安茹            Anjou                      Q107426     Anjou                                      1
                   Armentières                阿尔芒蒂耶尔        Armentières                Q193925     Armentières                                1
                   Arras                      阿拉斯           Arras                      Q131329     Arras                                      1
                                                                                                   Arras (colégio)                            1
                   Auch                       欧什            Auch                       Q181725     Auch                                       1
                   Aurillac                   欧里亚克          Aurillac                   Q174234     Aurillac                                   1
                   Autun                      歐坦            Autun                      Q190827     Autun                                      1
                   Auxerre                    欧塞尔           Auxerre                    Q167600     Auxerre                                    1
                   Avinhão                    亞維農           Avignon                    Q6397       Avignon                                   14
                                                                                                   Avignon (igreja do noviciado)              1
                   Awala-Yalimapo             阿瓦拉-亚利马波      Awala-Yalimapo             Q791602     Senna, província de Goa                    1
                   Bar-le-Duc                 巴勒迪克          Bar-le-Duc                 Q185721     Bar-le-Duc                                 1
                   Billom                     比永            Billom                     Q246257     Billom, França                             1
                   Bordéus                    波尔多           Bordeaux                   Q1479       Bordeaux                                  21
                                                                                                   Bordeaux (noviciado)                       1
                   Bourges                    布尔日           Bourges                    Q132404     Bourges                                    2
                                                                                                   Bourges (colégio)                          1
                   Brest                      布雷斯特          Brest                      Q12193      Brest                                     16
                                                                                                   Brest (seminário)                          1
                                                                                                   Brest, Bielorrússia                        1
                   Cadix                      卡迪            Cadix                      Q1152302    Cadix, França                              1
                   Caen                       卡昂            Caen                       Q41185      Caen                                       2
                   Cahors                     卡奥尔           Cahors                     Q23047      Cahors                                     1
                   Cambrai                    康布雷           Cambrai                    Q181285     Cambrai                                    1
                   Carcassonne                卡尔卡松          Carcassonne                Q6582       Carcassone                                 1
                   Carpentras                 卡庞特拉          Carpentras                 Q202560     Carpentras                                 1

                                                                                                                                     first_date  \
country_label      portuguese_label           chinese_label english_label              wikidata_id place
Abbasid Caliphate  Coração                    呼罗珊           Khorasan                   Q2352322    Khorasan                                1659
Afghanistan        Afeganistão                阿富汗           Afghanistan                Q889        Afeganistão                         17000000
Angola             Angola                     安哥拉           Angola                     Q916        Angola                                  1681
Argentina          Argentina                  阿根廷           Argentina                  Q414        Missão de Santa Ana, dos Guaranis   17280817
                   Buenos Aires               布宜諾斯艾利斯       Buenos Aires               Q1486       Buenos Aires                        17110501
Armenia            Arménia                    亞美尼亞          Armenia                    Q399        Arménia                             16800000
                                                                                                   Arménia (residência de Chamakii)    16960000
                   Erevã                      葉里溫           Yerevan                    Q1953       Yerevan                             16920500
Austria            Graz                       格拉茨           Graz                       Q13298      Graz                                16941225
                   Krems an der Donau         多瑙河畔克雷姆斯      Krems                      Q131266     Krems                               16641031
                   Leoben                     萊奧本           Leoben                     Q485294     Leoben                              16871224
                   Viena                      維也納           Vienna                     Q1741       Viena                               16271016
Azerbaijan         Shamakhi                   沙馬基           Shamakhi                   Q388224     Shamakhi                            17211218
Belarus            Bielorrússia               白俄羅斯          Belarus                    Q184        Rússia Branca                       17460828
                   Minsk                      明斯克           Minsk                      Q2280       Minsk                               16900815
                   Polatsk                    波洛茨克          Polatsk                    Q200797     Polotsk                             17860903
Belgium            Antuérpia                  安特卫普          Antwerp                    Q12892      Antuérpia                           16401115
                   Bruges                     布鲁日           Bruges                     Q12994      Bruges                                 1703>
                   Bruxelas                   布鲁塞尔          City of Brussels           Q239        Bruxelas                            16541125
                   Courtrai                   科特赖克          Kortrijk                   Q12995      Courtrai                            16440926
                   Liège                      列日            Liège                      Q3992       Liège                               16540000
                                                                                                   Liége                               17620913
                   Lovaina                    鲁汶            Leuven                     Q118958     Leuven                              16050000
                   Mechelen                   梅赫伦           Mechelen                   Q162022     Mechelen                            16341015
                   Namur                      那慕爾           Namur                      Q134121     Namur                               16600908
                   Oostende                   奥斯坦德          Ostend                     Q12996      Ostende                             16721214
                   Região de Bruxelas-Capital 布鲁塞尔首都大区      Brussels-Capital Region    Q240        Bruxelas                            16540702
                   Tournai                    图尔奈           Tournai                    Q173219     Tournai                             15960705
Bolivia            Santa Cruz de la Sierra    圣克鲁斯-德拉谢拉     Santa Cruz de la Sierra    Q170688     Santa Cruz de la Sierra, Peru       16260307
Brazil             Bahia                      巴伊亚州          Bahia                      Q40430      Bahia                                   1641
                                                                                                   Baía                                17080701
                                                                                                   Baía, Brasil                        17300929
                                                                                                   [No mar, perto da Baía]             17640507
                   Brasília                   巴西利亚          Brasília                   Q2844       Brasília                            17470908
                   Maranhão                   马拉尼昂州         Maranhão                   Q42362      Maranhão, Brasil                    16550516

In [19]:
df_variations.reset_index().to_excel('../inferences/wikidata-references/locations_variations.xlsx', sheet_name='variations', index=True)

## Produce a Gazeeter 

Same data but alphabetical order of place, place in the first column, followed by wikidata_id, first_date, last_date, unique_id, and the labels

In [20]:
df_variations.reset_index()[['place', 'wikidata_id', 'country_label', 'portuguese_label', 'chinese_label', 'english_label', 'id_unique','first_date','last_date']].sort_values(by=['place']).to_excel('../inferences/locations_geonames.xlsx', index=False)

### Place names variations for a specific country

In [21]:
unique_countries = (
    df_variations.index.get_level_values("country_label")
    .dropna()
    .unique()
    .tolist()
)

sorted(unique_countries)

['Abbasid Caliphate',
 'Afghanistan',
 'Angola',
 'Argentina',
 'Armenia',
 'Austria',
 'Azerbaijan',
 'Belarus',
 'Belgium',
 'Bolivia',
 'Brazil',
 'British Raj',
 'Cambodia',
 'Canada',
 'Champa',
 'Chile',
 'Croatia',
 'Cuba',
 'Czech Republic',
 'Dominican Republic',
 'Duchy of Lorraine',
 'Duchy of Moscow',
 'Dutch East Indies',
 'Ecuador',
 'Egypt',
 'Ethiopia',
 'France',
 'Germany',
 'Greece',
 'Guinea',
 'Hungary',
 'India',
 'Indonesia',
 'Iran',
 'Italy',
 'Japan',
 'Kazakhstan',
 'Kingdom of Hungary',
 'Kingdom of Italy',
 'Kingdom of Poland',
 'Kingdom of Romania',
 'Kingdom of the Netherlands',
 'Kyrgyzstan',
 'Lebanon',
 'Lithuania',
 'Malaysia',
 'Mexico',
 'Morocco',
 'Mozambique',
 'Mughal Empire',
 'Myanmar',
 'Nepal',
 'Netherlands',
 'Norway',
 'Pakistan',
 'Paraguay',
 "People's Republic of China",
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Portuguese Empire',
 'Qing dynasty',
 'Roman Empire',
 'Romania',
 'Russia',
 'Slovakia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Príncipe',
 'Taiwan',
 'Thailand',
 'Three Kingdoms of Korea',
 'Tsardom of Russia',
 'Turkey',
 'United Kingdom',
 'United States',
 'Vietnam']

In [22]:
country_of_interest = "People's Republic of China"
country_of_interest_df = df_variations[df_variations.index.get_level_values('country_label') == country_of_interest]
country_of_interest_df.head(100)

                                                                                                                                                          id_unique  \
country_label              portuguese_label        chinese_label english_label              wikidata_id place
People's Republic of China Anlu                    安陆市           Anlu                       Q557934     Anlo (Ngan-lo), Hupeh                                     1
                                                                                                        Anlu (Ngan-lou), Hupei                                    1
                           Anqing                  安庆市           Anqing                     Q360374     Anking (Ngan-k'ing fou)                                   1
                           Cantão                  广东省           Guangdong                  Q15175      Kouang-tong                                               2
                                                                                                        Kwangtung                                                16
                                                                                                        Kwangtung, China                                          1
                                                   广州市           Guangzhou                  Q16572      Cantão                                                  197
                                                                                                        Cantão (enfermaria dos franciscanos, extramuros)          1
                                                                                                        Cantão (feira)                                            3
                                                                                                        Cantão (igreja Ti-lo-pu)                                  1
                                                                                                        Cantão (igreja de Ty-lo-po)                               1
                                                                                                        Cantão (in sancello resid. Gallicae S.J.)                 1
                                                                                                        Cantão (missão)                                           1
                                                                                                        Cantão (porto, navio Amphitrite)                          1
                                                                                                        Cantão (residência francesa)                              1
                                                                                                        Cantão (residência)                                       1
                                                                                                        Guangzhou                                                 1
                                                                                                        [Costa de Cantão]                                         1
                           Cemitério de Chala      滕公栅栏          Zhalan Cemetery            Q4578286    Chala                                                     1
                           Changsha                长沙市           Changsha                   Q174091     Changsha                                                  1
                           Changzhou               常州市           Changzhou                  Q57970      Changchow, China                                          1
                           Chengde                 承德市           Chengde                    Q58675      Jehol                                                     3
                                                                                                        Jéhol                                                     1
                           Chengdu                 成都市           Chengdu                    Q30002      Chengdu, Sichuan                                          2
                           Chifeng                 赤峰市           Chifeng                    Q570829     Chihfeng (Tch'e-fong), Manchúria                          1
                           China                   中华人民共和国       People's Republic of China Q148        China                                                   179
                                                                                                        China (rio Coam [Yang-tseu-kiang?])                       1
                                                                                                        China central                                             1
                                                                                                        Sul da China                                              2
                                                                                                        [Perto da China]                                          1
                           Chongming               崇明区           Chongming District         Q788812     Ilha de Tsongming (Tch'ong-ming)                          1
                                                                                                        Ilha de Tsung-ming                                        1
                                                                                                        Ilha de Tsungming (Tch'ong-ming)                          2
                                                                                                        Kiangnan, Tsungmming (Tch'ong-ming)                       1
                                                                                                        Tsungming                                                 1
                                                                                                        Tsungming (Tch'ong-ming)                                  1
                           Chongqing               重庆市           Chongqing                  Q11725      Chungking (Tch'ong-k'ing, Sseu-tch0ouan)                  1
                           Condado Yongjia         永嘉县           Yongjia County             Q703818     Suian, Souei-ngan hien                                    1
                           Condado de Lianjiang    连江县           Lianjiang County           Q204827     Lienkong (igreja)                                         1
                           Dzungaria               北疆            Dzungaria                  Q284027     Dzungaria                                                 1
                           Foshan                  佛山市           Foshan                     Q34412      Fatshan                                                   7
                                                                                                        Fatshan (igreja de S. José)                               1
                                                                                                        Fatshan (igreja)                                          1
                                                                                                        Fatshan, Fo-chan-tchen, sudeste de Cantão                 1
                                                                                                        Fatshan, Kwangtung                                        4
                           Fujian                  福建省           Fujian                     Q41705      Costa de Fukien                                           1
                                                                                                        Fou-kien                                                  1
                                                                                                        Foukien                                                   2
                                                                                                        Fukien                                                   15
                           Fuzhou                  抚州市           Fuzhou                     Q363391     Fou-tcheou, Kiangsi                                       1
                                                                                                        Fuchow (Fou-tcheou)                                       1
                                                                                                        Fuchow (Fou-tcheou) do Kiangsi                            1
                                                                                                        Fuchow (Fou-tcheou), Kiangsi                              1
                                                                                                        Fuchow fou                                                1
                                                   福州市           Fuzhou                     Q68481      Foochow                                                   9
                                                                                                        Foochow (Fou-tcheou fou)                                  2
                                                                                                        Foochow (Fou-tcheou fou), Fukien                          1
                                                                                                        Foochow (Fou-tcheou fou, Fukien)                          1
                                                                                                        Foochow fou, Fukien                                       1
                                                                                                        Foochow, Fou-kien                                         1
                                                                                                        Foochow, Fou-tcheou fu, Fukien                            1
                                                                                                        Foochow, Fukien                                           8
                                                                                                        Foochow, Fukien (residência)                              1
                                                                                                        Fou-tcheou fou                                            1
                                                                                                        Fukien                                                    1
                                                                                                        [No mar, perto de Foochow]                                1
                           Gansu                   甘肃省           Gansu                      Q42392      Kan-sou                                                   1
                                                                                                        Kansu (Kan-sou)                                           1
                           Ganzhou                 赣州市           Ganzhou                    Q363166     Can cheu (Kanchow)                                        1
                                                                                                        Ganzhou, província de Jiangxi                             1
                                                                                                        Kan-tcheou, Kiangsi                                       1
                                                                                                        Kanchow                                                   5
                                                                                                        Kanchow (Kan-tcheou fou)                                  1
                                                                                                        Kanchow (Kan-tcheou fou, Kiangsi)                         1
                                                                                                        Kanchow (Kan-tcheou) do Kiangsi                           1
                                                                                                        Kanchow (Kan-tcheou) fou, Kiangsi                         1
                                                                                                        Kanchow do Kiangsi                                        2
                                                                                                        Kanchow fou                                               1
                                                                                                        Kanchow, Kiang-si                                         2
                                                                                                        Kanchow, Kiangsi                                          3
                                                                                                        Kanchow, Kiangxi                                          2
                                                                                                        Kangchow, Kiangsi                                         1
                           Grande Muralha da China 长城            Great Wall of China        Q12501      Grande Muralha da China                                   3
                           Guangxi                 广西壮族自治区       Guangxi                    Q15176      Kwangsi                                                   6
                                                                                                        Kwangsi (Kouang-si)                                       1
                                                                                                        Kwangsi (corte de Yong-li)                                1
                           Guilin                  桂林市           Guilin                     Q189633     Kweilin                                                   1
                                                                                                        Kweilin (Kouei-lin) fou, Kwangsi                          1
                                                                                                        Kweilin, Kouang-si                                        3
                                                                                                        Kweilin, Kwangsi                                          4
                           Guiyang                 貴陽市           Guiyang                    Q192271     Kweiyang fou, Kweichow                                    1
                           Guizhou                 贵州省           Guizhou                    Q47097      Kweichow                                                  2
                           Hainan                  海南省           Hainan                     Q42200      Golfo de Hainan                                           1
                                                                                                        Hainan                                                   33
                                                                                                        [No mar, perto de Hainan]                                 1
                                                                                                        [Perto de Hainan]                                         2
                           Hangzhou                杭州市           Hangzhou                   Q4970       Ham cheu                                                  1
                                                                                                        Ham cheu, Che Kiam                                        2
                                                                                                        Hang-tcheou                                               1
                                                                                                        Hangchow                                                 43

                                                                                                                                                         first_date  \
country_label              portuguese_label        chinese_label english_label              wikidata_id place
People's Republic of China Anlu                    安陆市           Anlu                       Q557934     Anlo (Ngan-lo), Hupeh                             17231009>
                                                                                                        Anlu (Ngan-lou), Hupei                             17040000
                           Anqing                  安庆市           Anqing                     Q360374     Anking (Ngan-k'ing fou)                           >16710908
                           Cantão                  广东省           Guangdong                  Q15175      Kouang-tong                                       16590000>
                                                                                                        Kwangtung                                          15551123
                                                                                                        Kwangtung, China                                   16991000
                                                   广州市           Guangzhou                  Q16572      Cantão                                                 1555
                                                                                                        Cantão (enfermaria dos franciscanos, extramuros)   17030317
                                                                                                        Cantão (feira)                                     15641118
                                                                                                        Cantão (igreja Ti-lo-pu)                           17100815
                                                                                                        Cantão (igreja de Ty-lo-po)                        17080914
                                                                                                        Cantão (in sancello resid. Gallicae S.J.)          17060815
                                                                                                        Cantão (missão)                                    16630319
                                                                                                        Cantão (porto, navio Amphitrite)                   16990815
                                                                                                        Cantão (residência francesa)                           1692
                                                                                                        Cantão (residência)                                17320000
                                                                                                        Guangzhou                                          16841100
                                                                                                        [Costa de Cantão]                                  17010909

### Export country of interest places

In [23]:
filename = f"../inferences/locations_{country_of_interest}_name_variations.xlsx"

country_of_interest_df.to_excel(filename, sheet_name='variations', index=True)

## Who was at a specific place

In [24]:
place_of_interest = 'Coimbra'

In [25]:
cols_place_detail = ['place', 'wikidata_id', 'name', 'place.type', 'place.date_inferred', 'place.obs']
(
    places_of_stay[places_of_stay.place == place_of_interest][cols_place_detail]
    .sort_values(by=['place.date_inferred'])
    .head(10)
)

,place,wikidata_id,name,place.type,place.date_inferred,place.obs
id_col,,,,,,
deh-pedro-de-alcacova,Coimbra,Q45412,Pedro de Alcáçova,jesuita-entrada,15420000,saiu a primeira vez
deh-belchior-nunes-barreto,Coimbra,Q45412,Belchior Nunes Barreto,jesuita-entrada,15430311,
deh-belchior-miguel-carneiro-leitao,Coimbra,Q45412,Belchior Miguel Carneiro Leitão,jesuita-entrada,15430425,
deh-francisco-perez,Coimbra,Q45412,Francisco Pérez,jesuita-entrada,15440125,
deh-tiburcio-de-quadros,Coimbra,Q45412,Tibúrcio de Quadros,jesuita-entrada,15440418,
deh-goncalo-alvares,Coimbra,Q45412,Gonçalo Álvares,jesuita-entrada,15490101,
deh-cristovao-da-costa,Coimbra,Q45412,Cristóvão da Costa,jesuita-entrada,15500103,
deh-joao-rodrigues-de-sainan,Coimbra,Q45412,João Rodrigues de Sainan,jesuita-entrada,1555,
deh-pedro-martins,Coimbra,Q45412,Pedro Martins,jesuita-entrada,15560525,
deh-lourenco-mexia,Coimbra,Q45412,Lourenço Mexia,jesuita-entrada,15600314,

In [26]:
wikidata_id_of_interest='Q1207099'
cols_place_detail = ['place', 'wikidata_id', 'name', 'place.type', 'place.date_inferred', 'place.obs']
(
    places_of_stay[places_of_stay.wikidata_id == wikidata_id_of_interest][cols_place_detail]
    .sort_values(by=['place.date_inferred'])
    .head(100)
)

,place,wikidata_id,name,place.type,place.date_inferred,place.obs
id_col,,,,,,
deh-jean-valat,Lin-ts'ing,Q1207099,Jean Valat,estadia,1685,
deh-jean-charles-etienne-froissard-de-broissia,"[No mar, para lá de Lin-tsing (Lin-ts'ing, Sha...",Q1207099,Jean-Charles Etienne Froissard de Broissia,morte,17040918,
deh-jose-simoes,Lintsing,Q1207099,José Simões,estadia,17070600,
deh-pierre-tchen,"Linkiang, Kiangsi",Q1207099,Pierre T'chen,estadia,17430000,

### Export markdown stubs for persons at that place

In [27]:
markdown_directory = f"../inferences/{place_of_interest}/markdown"
os.makedirs(markdown_directory, exist_ok=True)

for person_id, name in places_of_stay[places_of_stay.place == place_of_interest][['name']].sort_values('name').itertuples(index=True):
    with tlnb.db.session() as session:
        person = tlnb.db.get_person(person_id, session=session)
        session.add(person)
        kleio_text = person.to_kleio()

    note = f"""## {name}
^[In Edit mode, select title (including the ##), right click and "Extract selection"]

---
### {name} @ timelink
```
{kleio_text}
```

---
Select title, right click on selected title, choose extract note
"""
    
    with open(f"{markdown_directory}/{person_id}.md", "w", encoding="utf-8") as handle:
        handle.write(note)

## Recover missing Wikidata IDs from variations

Try to find candidate Wikidata IDs for locations missing them, using the variations file that contains variations of names for known Wikidata IDs.

In [28]:
import pandas as pd
import os
from difflib import SequenceMatcher

# Define file paths
no_wikidata_path = '../inferences/wikidata-references/locations_names_no_wikidata.xlsx'
variations_path = '../inferences/wikidata-references/locations_variations.xlsx'
output_path = '../inferences/wikidata-references/locations_names_no_wikidata_with_candidates.xlsx'

# Check if files exist
if not os.path.exists(no_wikidata_path):
    print(f"File not found: {no_wikidata_path}")
    # Try alternative path based on notebook logic
    no_wikidata_path = '../inferences/locations_names_no_wikidata.xlsx'
    print(f"Trying: {no_wikidata_path}")

if not os.path.exists(variations_path):
    print(f"File not found: {variations_path}")
    # Try alternative path
    variations_path = '../inferences/locations_variations.xlsx'
    print(f"Trying: {variations_path}")

try:
    df_missing = pd.read_excel(no_wikidata_path)
    df_variations = pd.read_excel(variations_path)

    print(f"Loaded {len(df_missing)} rows with missing Wikidata IDs.")
    print(f"Loaded {len(df_variations)} known location variations.")

    # 1. Basic Cleaning
    df_missing['place_clean'] = df_missing['place'].astype(str).str.strip()
    df_variations['place_clean'] = df_variations['place'].astype(str).str.strip()

    # 2. Prepare candidates
    # We only care about variations that actually have a Wikidata ID
    valid_variations = df_variations.dropna(subset=['wikidata_id'])[['place_clean', 'wikidata_id']].drop_duplicates()
    candidate_names = valid_variations['place_clean'].tolist()
    candidate_ids = valid_variations['wikidata_id'].tolist()
    
    # Create an exact lookup first for O(1) matching
    exact_lookup = dict(zip(candidate_names, candidate_ids))

    # 3. Fuzzy matching function
    def find_best_match(query, choices, ids, cutoff=0.6):
        """
        Find best string match using difflib.SequenceMatcher.
        Returns (id, match_name, score)
        """
        # Exact match optimization
        if query in exact_lookup:
            return exact_lookup[query], query, 1.0

        best_match = None
        best_id = None
        best_ratio = 0.0
        
        for choice, wid in zip(choices, ids):
            # SequenceMatcher gives a ratio between 0 and 1
            ratio = SequenceMatcher(None, query, choice).ratio()
            if ratio > best_ratio:
                best_ratio = ratio
                best_match = choice
                best_id = wid
        
        if best_ratio >= cutoff:
            return best_id, best_match, best_ratio
        return None, None, 0.0

    print("Finding matches (this might take a while)...")
    
    # 4. Apply matching
    # Work on unique names to avoid re-calcuating the same name multiple times
    unique_missing = df_missing['place_clean'].unique()
    print(f"Processing {len(unique_missing)} unique missing place names...")
    
    results = []
    for i, place in enumerate(unique_missing):
        wid, match_name, score = find_best_match(place, candidate_names, candidate_ids, cutoff=0.65)
        results.append({
            'place_clean': place,
            'candidate_id': wid,
            'candidate_name': match_name,
            'match_score': score
        })
        if (i + 1) % 50 == 0:
            print(f"Processed {i + 1}/{len(unique_missing)}...")
    
    df_results = pd.DataFrame(results)
    
    # 5. Merge results back
    df_final = df_missing.merge(df_results, on='place_clean', how='left')

    # 6. Report and Save
    found_matches = df_final[df_final['candidate_id'].notna()]
    print(f"Found {len(found_matches)} candidates out of {len(df_missing)} rows.")

    if len(found_matches) > 0:
        print("\nTop matches (by score):")
        cols_to_show = ['place', 'candidate_name', 'match_score', 'candidate_id']
        print(found_matches[cols_to_show].drop_duplicates(subset=['place']).sort_values('match_score', ascending=False).head(15))

    df_final.drop(columns=['place_clean'], inplace=True, errors='ignore')
    df_final.to_excel(output_path, index=False)
    print(f"\nSaved {len(df_final)} rows to {output_path}")

except Exception as e:
    print(f"Error: {e}")
    import traceback
    traceback.print_exc()

Loaded 60 rows with missing Wikidata IDs.
Loaded 843 known location variations.
Finding matches (this might take a while)...
Processing 54 unique missing place names...
Processed 50/54...
Found 11 candidates out of 60 rows.

Top matches (by score):
                              place                candidate_name  \
4                          Chang-si                       Chan-si
15                 Ké Diet, Tonquim                 Hien, Tonquim
20                  Làngòi, Tonquim                 Hien, Tonquim
27                          Oriente                       Lorient
13  Ko-li-tsem do Kiating, Kiangnan  Kiatim (Kiating) do Kiangnan
24                Monzei, Filipinas                     Filipinas
38                    Sian tan hien        Suian, Souei-ngan hien
6               Chayüankow, Hukwang             Hengchow, Hukwang
25                          Moulins                         Minsk
33          Pé-tsiuen-chan, Hukwang             Hengchow, Hukwang

    match_score candidate_id
4      0.933333       Q46913
15     0.758621       Q36485
20     0.714286       Q36485
27     0.714286       Q71724
13     0.711864      Q662101
24     0.692308         Q928
38     0.685714      Q703818
6      0.666667      Q144663
25     0.666667        Q2280
33     0.650000      Q144663

Saved 60 rows to ../inferences/wikidata-references/locations_names_no_wikidata_with_candidates.xlsx

In [29]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_col                         60 non-null     object
 1   place                          60 non-null     object
 2   wikidata_id                    0 non-null      float64
 3   place.date_inferred.formatted  60 non-null     object
 4   place.date_inferred            60 non-null     object
 5   place.date_is_inferred         60 non-null     bool
 6   name                           60 non-null     object
 7   groupname                      60 non-null     object
 8   place.type                     60 non-null     object
 9   place.original                 1 non-null      object
 10  place.line                     60 non-null     int64
 11  candidate_id                   11 non-null     object
 12  candidate_name                 11 non-null     object
 13  match_score                    60 non-null     float64
dtypes: bool(1), float64(2), int64(1), object(10)
memory usage: 6.3+ KB

We generate a document with the biographies of all the peopl with references to non located places